<a href="https://colab.research.google.com/github/gomlfx/ApiaryFund/blob/master/AGC27_1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install autogluon

In [ ]:
#!pip install --upgrade mxnet

In [ ]:
#designed for Jupyter/kaggle/colab
import pandas as pd
import numpy as np
#import matplotlib for plotting 
import matplotlib.pyplot as plt
%matplotlib inline
#import normalization
from sklearn import preprocessing

#autogluon
from autogluon.tabular import TabularDataset, TabularPredictor

In [ ]:
 #MT4 csv 
df_m_5=pd.read_csv('USDJPY1440.csv', names=['d','t','eu_o','eu_h','eu_l','eu_c','eu_v'])


# df2=pd.read_csv('GBPUSD1440.csv', names=['d','t','gu_o','gu_h','gu_l','gu_c','gu_v'])
# df2 = df2.tail(2000)

# df3=pd.read_csv('USDCAD1440.csv', names=['d','t','uc_o','uc_h','uc_l','uc_c','uc_v'])
# df3 = df3.tail(2000)

# df4=pd.read_csv('USDCHF1440.csv', names=['d','t','uf_o','uf_h','uf_l','uf_c','uf_v'])
# df4 = df4.tail(2000)

# df5=pd.read_csv('USDJPY1440.csv', names=['d','t','uj_o','uj_h','uj_l','uj_c','uj_v'])
# df5 = df5.tail(2000)

# df6=pd.read_csv('USDSEK1440.csv', names=['d','t','us_o','us_h','us_l','us_c','us_v'])
# df6 = df6.tail(2000)

# #using merge
# df_m_1 = df1.merge(df2, on='d')
# df_m_2 = df_m_1.merge(df3, on='d')
# df_m_3 = df_m_2.merge(df4, on='d')
# df_m_4 = df_m_3.merge(df5, on='d')
# df_m_5 = df_m_4.merge(df6, on='d')
# df_m_5 = df_m_5.drop(columns='t_x')
# df_m_5 = df_m_5.drop(columns='t_y')

# pd.set_option('display.max_columns', None)
# print(df_m_5)

In [ ]:
df_m_5

               d      t     eu_o     eu_h     eu_l     eu_c   eu_v
0     2013.11.14  00:00   99.220  100.250   99.130  100.210  18887
1     2013.11.15  00:00  100.200  100.430   99.930  100.210  12107
2     2013.11.17  00:00  100.210  100.380  100.200  100.350    639
3     2013.11.18  00:00  100.350  100.350   99.780   99.862  18614
4     2013.11.19  00:00   99.861  100.254   99.570  100.170  64235
...          ...    ...      ...      ...      ...      ...    ...
2199  2022.04.19  00:00  126.964  128.971  126.963  128.887  58062
2200  2022.04.20  00:00  128.883  129.406  127.456  127.876  71228
2201  2022.04.21  00:00  127.826  128.703  127.793  128.382  57395
2202  2022.04.22  00:00  128.333  129.106  127.735  128.531  62386
2203  2022.04.25  00:00  128.553  128.851  128.406  128.766   1914

[2204 rows x 7 columns]

In [ ]:
#Features

#60 days ago
df_m_5['eu_High_last_day60'] = df_m_5['eu_h'].shift(60)
df_m_5['eu_Low_last_day60'] = df_m_5['eu_l'].shift(60)
df_m_5['eu_Close_last_day60'] = df_m_5['eu_c'].shift(60)
#59 days ago
df_m_5['eu_High_last_day59'] = df_m_5['eu_h'].shift(59)
df_m_5['eu_Low_last_day59'] = df_m_5['eu_l'].shift(59)
df_m_5['eu_Close_last_day59'] = df_m_5['eu_c'].shift(59)
#58 days ago
df_m_5['eu_High_last_day58'] = df_m_5['eu_h'].shift(58)
df_m_5['eu_Low_last_day58'] = df_m_5['eu_l'].shift(58)
df_m_5['eu_Close_last_day58'] = df_m_5['eu_c'].shift(58)
#57 days ago
df_m_5['eu_High_last_day57'] = df_m_5['eu_h'].shift(57)
df_m_5['eu_Low_last_day57'] = df_m_5['eu_l'].shift(57)
df_m_5['eu_Close_last_day57'] = df_m_5['eu_c'].shift(57)
#56 days ago
df_m_5['eu_High_last_day56'] = df_m_5['eu_h'].shift(56)
df_m_5['eu_Low_last_day56'] = df_m_5['eu_l'].shift(56)
df_m_5['eu_Close_last_day56'] = df_m_5['eu_c'].shift(56)
#55 days ago
df_m_5['eu_High_last_day55'] = df_m_5['eu_h'].shift(55)
df_m_5['eu_Low_last_day55'] = df_m_5['eu_l'].shift(55)
df_m_5['eu_Close_last_day55'] = df_m_5['eu_c'].shift(55)
#54 days ago
df_m_5['eu_High_last_day54'] = df_m_5['eu_h'].shift(54)
df_m_5['eu_Low_last_day54'] = df_m_5['eu_l'].shift(54)
df_m_5['eu_Close_last_day54'] = df_m_5['eu_c'].shift(54)
#53 days ago
df_m_5['eu_High_last_day53'] = df_m_5['eu_h'].shift(53)
df_m_5['eu_Low_last_day53'] = df_m_5['eu_l'].shift(53)
df_m_5['eu_Close_last_day53'] = df_m_5['eu_c'].shift(53)
#52 days ago
df_m_5['eu_High_last_day52'] = df_m_5['eu_h'].shift(52)
df_m_5['eu_Low_last_day52'] = df_m_5['eu_l'].shift(52)
df_m_5['eu_Close_last_day52'] = df_m_5['eu_c'].shift(52)
#51 days ago
df_m_5['eu_High_last_day51'] = df_m_5['eu_h'].shift(51)
df_m_5['eu_Low_last_day51'] = df_m_5['eu_l'].shift(51)
df_m_5['eu_Close_last_day51'] = df_m_5['eu_c'].shift(51)
#50 days ago
df_m_5['eu_High_last_day50'] = df_m_5['eu_h'].shift(50)
df_m_5['eu_Low_last_day50'] = df_m_5['eu_l'].shift(50)
df_m_5['eu_Close_last_day50'] = df_m_5['eu_c'].shift(50)
#49 days ago
df_m_5['eu_High_last_day49'] = df_m_5['eu_h'].shift(49)
df_m_5['eu_Low_last_day49'] = df_m_5['eu_l'].shift(49)
df_m_5['eu_Close_last_day49'] = df_m_5['eu_c'].shift(49)
#48 days ago
df_m_5['eu_High_last_day48'] = df_m_5['eu_h'].shift(48)
df_m_5['eu_Low_last_day48'] = df_m_5['eu_l'].shift(48)
df_m_5['eu_Close_last_day48'] = df_m_5['eu_c'].shift(48)
#47 days ago
df_m_5['eu_High_last_day47'] = df_m_5['eu_h'].shift(47)
df_m_5['eu_Low_last_day47'] = df_m_5['eu_l'].shift(47)
df_m_5['eu_Close_last_day47'] = df_m_5['eu_c'].shift(47)
#46 days ago
df_m_5['eu_High_last_day46'] = df_m_5['eu_h'].shift(46)
df_m_5['eu_Low_last_day46'] = df_m_5['eu_l'].shift(46)
df_m_5['eu_Close_last_day46'] = df_m_5['eu_c'].shift(46)
#45 days ago
df_m_5['eu_High_last_day45'] = df_m_5['eu_h'].shift(45)
df_m_5['eu_Low_last_day45'] = df_m_5['eu_l'].shift(45)
df_m_5['eu_Close_last_day45'] = df_m_5['eu_c'].shift(45)
#44 days ago
df_m_5['eu_High_last_day44'] = df_m_5['eu_h'].shift(44)
df_m_5['eu_Low_last_day44'] = df_m_5['eu_l'].shift(44)
df_m_5['eu_Close_last_day44'] = df_m_5['eu_c'].shift(44)
#43 days ago
df_m_5['eu_High_last_day43'] = df_m_5['eu_h'].shift(43)
df_m_5['eu_Low_last_day43'] = df_m_5['eu_l'].shift(43)
df_m_5['eu_Close_last_day43'] = df_m_5['eu_c'].shift(43)
#42 days ago
df_m_5['eu_High_last_day42'] = df_m_5['eu_h'].shift(42)
df_m_5['eu_Low_last_day42'] = df_m_5['eu_l'].shift(42)
df_m_5['eu_Close_last_day42'] = df_m_5['eu_c'].shift(42)
#41 days ago
df_m_5['eu_High_last_day41'] = df_m_5['eu_h'].shift(41)
df_m_5['eu_Low_last_day41'] = df_m_5['eu_l'].shift(41)
df_m_5['eu_Close_last_day41'] = df_m_5['eu_c'].shift(41)
#40 days ago
df_m_5['eu_High_last_day40'] = df_m_5['eu_h'].shift(40)
df_m_5['eu_Low_last_day40'] = df_m_5['eu_l'].shift(40)
df_m_5['eu_Close_last_day40'] = df_m_5['eu_c'].shift(40)
#39 days ago
df_m_5['eu_High_last_day39'] = df_m_5['eu_h'].shift(39)
df_m_5['eu_Low_last_day39'] = df_m_5['eu_l'].shift(39)
df_m_5['eu_Close_last_day39'] = df_m_5['eu_c'].shift(39)
#38 days ago
df_m_5['eu_High_last_day38'] = df_m_5['eu_h'].shift(38)
df_m_5['eu_Low_last_day38'] = df_m_5['eu_l'].shift(38)
df_m_5['eu_Close_last_day38'] = df_m_5['eu_c'].shift(38)
#37 days ago
df_m_5['eu_High_last_day37'] = df_m_5['eu_h'].shift(37)
df_m_5['eu_Low_last_day37'] = df_m_5['eu_l'].shift(37)
df_m_5['eu_Close_last_day37'] = df_m_5['eu_c'].shift(37)
#36 days ago
df_m_5['eu_High_last_day36'] = df_m_5['eu_h'].shift(36)
df_m_5['eu_Low_last_day36'] = df_m_5['eu_l'].shift(36)
df_m_5['eu_Close_last_day36'] = df_m_5['eu_c'].shift(36)
#35 days ago
df_m_5['eu_High_last_day35'] = df_m_5['eu_h'].shift(35)
df_m_5['eu_Low_last_day35'] = df_m_5['eu_l'].shift(35)
df_m_5['eu_Close_last_day35'] = df_m_5['eu_c'].shift(35)
#34 days ago
df_m_5['eu_High_last_day34'] = df_m_5['eu_h'].shift(34)
df_m_5['eu_Low_last_day34'] = df_m_5['eu_l'].shift(34)
df_m_5['eu_Close_last_day34'] = df_m_5['eu_c'].shift(34)
#33 days ago
df_m_5['eu_High_last_day33'] = df_m_5['eu_h'].shift(33)
df_m_5['eu_Low_last_day33'] = df_m_5['eu_l'].shift(33)
df_m_5['eu_Close_last_day33'] = df_m_5['eu_c'].shift(33)
#32 days ago
df_m_5['eu_High_last_day32'] = df_m_5['eu_h'].shift(32)
df_m_5['eu_Low_last_day32'] = df_m_5['eu_l'].shift(32)
df_m_5['eu_Close_last_day32'] = df_m_5['eu_c'].shift(32)
#31 days ago
df_m_5['eu_High_last_day31'] = df_m_5['eu_h'].shift(31)
df_m_5['eu_Low_last_day31'] = df_m_5['eu_l'].shift(31)
df_m_5['eu_Close_last_day31'] = df_m_5['eu_c'].shift(31)
#30 days ago
df_m_5['eu_High_last_day30'] = df_m_5['eu_h'].shift(30)
df_m_5['eu_Low_last_day30'] = df_m_5['eu_l'].shift(30)
df_m_5['eu_Close_last_day30'] = df_m_5['eu_c'].shift(30) 
#29 days ago 
df_m_5['eu_High_last_day29'] = df_m_5['eu_h'].shift(29)
df_m_5['eu_Low_last_day29'] = df_m_5['eu_l'].shift(29)
df_m_5['eu_Close_last_day29'] = df_m_5['eu_c'].shift(29)
#28 days ago
df_m_5['eu_High_last_day28'] = df_m_5['eu_h'].shift(28)
df_m_5['eu_Low_last_day28'] = df_m_5['eu_l'].shift(28)
df_m_5['eu_Close_last_day28'] = df_m_5['eu_c'].shift(28) 
#27 days ago
df_m_5['eu_High_last_day27'] = df_m_5['eu_h'].shift(27)
df_m_5['eu_Low_last_day27'] = df_m_5['eu_l'].shift(27)
df_m_5['eu_Close_last_day27'] = df_m_5['eu_c'].shift(27)
#26 day ago
df_m_5['eu_High_last_day26'] = df_m_5['eu_h'].shift(26)
df_m_5['eu_Low_last_day26'] = df_m_5['eu_l'].shift(26)
df_m_5['eu_Close_last_day26'] = df_m_5['eu_c'].shift(26)
#25 days ago
df_m_5['eu_High_last_day25'] = df_m_5['eu_h'].shift(25)
df_m_5['eu_Low_last_day25'] = df_m_5['eu_l'].shift(25)
df_m_5['eu_Close_last_day25'] = df_m_5['eu_c'].shift(25) 
#24 days ago 
df_m_5['eu_High_last_day24'] = df_m_5['eu_h'].shift(24)
df_m_5['eu_Low_last_day24'] = df_m_5['eu_l'].shift(24)
df_m_5['eu_Close_last_day24'] = df_m_5['eu_c'].shift(24) 
#23 days ago
df_m_5['eu_High_last_day23'] = df_m_5['eu_h'].shift(23)
df_m_5['eu_Low_last_day23'] = df_m_5['eu_l'].shift(23)
df_m_5['eu_Close_last_day23'] = df_m_5['eu_c'].shift(23) 
#22 days ago
df_m_5['eu_High_last_day22'] = df_m_5['eu_h'].shift(22)
df_m_5['eu_Low_last_day22'] = df_m_5['eu_l'].shift(22)
df_m_5['eu_Close_last_day22'] = df_m_5['eu_c'].shift(22) 
#21 day ago
df_m_5['eu_High_last_day21'] = df_m_5['eu_h'].shift(21)
df_m_5['eu_Low_last_day21'] = df_m_5['eu_l'].shift(21)
df_m_5['eu_Close_last_day21'] = df_m_5['eu_c'].shift(21)
#20 days ago
df_m_5['eu_High_last_day20'] = df_m_5['eu_h'].shift(20)
df_m_5['eu_Low_last_day20'] = df_m_5['eu_l'].shift(20)
df_m_5['eu_Close_last_day20'] = df_m_5['eu_c'].shift(20) 
#19 days ago 
df_m_5['eu_High_last_day19'] = df_m_5['eu_h'].shift(19)
df_m_5['eu_Low_last_day19'] = df_m_5['eu_l'].shift(19)
df_m_5['eu_Close_last_day19'] = df_m_5['eu_c'].shift(19)
#18 days ago
df_m_5['eu_High_last_day18'] = df_m_5['eu_h'].shift(18)
df_m_5['eu_Low_last_day18'] = df_m_5['eu_l'].shift(18)
df_m_5['eu_Close_last_day18'] = df_m_5['eu_c'].shift(18) 
#17 days ago
df_m_5['eu_High_last_day17'] = df_m_5['eu_h'].shift(17)
df_m_5['eu_Low_last_day17'] = df_m_5['eu_l'].shift(17)
df_m_5['eu_Close_last_day17'] = df_m_5['eu_c'].shift(17) 
#16 day ago
df_m_5['eu_High_last_day16'] = df_m_5['eu_h'].shift(16)
df_m_5['eu_Low_last_day16'] = df_m_5['eu_l'].shift(16)
df_m_5['eu_Close_last_day16'] = df_m_5['eu_c'].shift(16)
#15 days ago
df_m_5['eu_High_last_day15'] = df_m_5['eu_h'].shift(15)
df_m_5['eu_Low_last_day15'] = df_m_5['eu_l'].shift(15)
df_m_5['eu_Close_last_day15'] = df_m_5['eu_c'].shift(15)
#14 days ago 
df_m_5['eu_High_last_day14'] = df_m_5['eu_h'].shift(14)
df_m_5['eu_Low_last_day14'] = df_m_5['eu_l'].shift(14)
df_m_5['eu_Close_last_day14'] = df_m_5['eu_c'].shift(14) 
#13 days ago
df_m_5['eu_High_last_day13'] = df_m_5['eu_h'].shift(13)
df_m_5['eu_Low_last_day13'] = df_m_5['eu_l'].shift(13)
df_m_5['eu_Close_last_day13'] = df_m_5['eu_c'].shift(13) 
#12 days ago
df_m_5['eu_High_last_day12'] = df_m_5['eu_h'].shift(12)
df_m_5['eu_Low_last_day12'] = df_m_5['eu_l'].shift(12)
df_m_5['eu_Close_last_day12'] = df_m_5['eu_c'].shift(12) 
#11 day ago 
df_m_5['eu_High_last_day11'] = df_m_5['eu_h'].shift(11)
df_m_5['eu_Low_last_day11'] = df_m_5['eu_l'].shift(11)
df_m_5['eu_Close_last_day11'] = df_m_5['eu_c'].shift(11) 
#10 days ago
df_m_5['eu_High_last_day10'] = df_m_5['eu_h'].shift(10)
df_m_5['eu_Low_last_day10'] = df_m_5['eu_l'].shift(10)
df_m_5['eu_Close_last_day10'] = df_m_5['eu_c'].shift(10)
#9 days ago 
df_m_5['eu_High_last_day9'] = df_m_5['eu_h'].shift(9)
df_m_5['eu_Low_last_day9'] = df_m_5['eu_l'].shift(9)
df_m_5['eu_Close_last_day9'] = df_m_5['eu_c'].shift(9) 
#8 days ago
df_m_5['eu_High_last_day8'] = df_m_5['eu_h'].shift(8)
df_m_5['eu_Low_last_day8'] = df_m_5['eu_l'].shift(8)
df_m_5['eu_Close_last_day8'] = df_m_5['eu_c'].shift(8)
#7 days ago
df_m_5['eu_High_last_day7'] = df_m_5['eu_h'].shift(7)
df_m_5['eu_Low_last_day7'] = df_m_5['eu_l'].shift(7)
df_m_5['eu_Close_last_day7'] = df_m_5['eu_c'].shift(7) 
#6 day ago 
df_m_5['eu_High_last_day6'] = df_m_5['eu_h'].shift(6)
df_m_5['eu_Low_last_day6'] = df_m_5['eu_l'].shift(6)
df_m_5['eu_Close_last_day6'] = df_m_5['eu_c'].shift(6)
#5 days ago
df_m_5['eu_High_last_day5'] = df_m_5['eu_h'].shift(5)
df_m_5['eu_Low_last_day5'] = df_m_5['eu_l'].shift(5)
df_m_5['eu_Close_last_day5'] = df_m_5['eu_c'].shift(5) 
#4 days ago 
df_m_5['eu_High_last_day4'] = df_m_5['eu_h'].shift(4)
df_m_5['eu_Low_last_day4'] = df_m_5['eu_l'].shift(4)
df_m_5['eu_Close_last_day4'] = df_m_5['eu_c'].shift(4) 
#3 days ago
df_m_5['eu_High_last_day3'] = df_m_5['eu_h'].shift(3)
df_m_5['eu_Low_last_day3'] = df_m_5['eu_l'].shift(3)
df_m_5['eu_Close_last_day3'] = df_m_5['eu_c'].shift(3)
#2 days ago
df_m_5['eu_High_last_day2'] = df_m_5['eu_h'].shift(2)
df_m_5['eu_Low_last_day2'] = df_m_5['eu_l'].shift(2)
df_m_5['eu_Close_last_day2'] = df_m_5['eu_c'].shift(2) 
#1 day ago 
df_m_5['eu_High_last_day1'] = df_m_5['eu_h'].shift(1)
df_m_5['eu_Low_last_day1'] = df_m_5['eu_l'].shift(1)
df_m_5['eu_Close_last_day1'] = df_m_5['eu_c'].shift(1)     

#Target
#1 day forward 
df_m_5['eu_High_next_day1'] = df_m_5['eu_h'].shift(-1)
df_m_5['eu_Low_next_day1'] = df_m_5['eu_l'].shift(-1)
df_m_5['eu_Close_next_day1'] = df_m_5['eu_c'].shift(-1) 

#drop null and useless columns
df_m_5 = df_m_5.dropna()
df_m_5 = df_m_5.drop(['d','t','eu_o','eu_h','eu_l','eu_c','eu_v'], axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:133: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:134: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:136: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:137: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:138: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:140: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:144: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:145: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:146: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:148: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:149: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:150: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:152: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:153: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:154: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:156: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:157: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:158: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:160: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:161: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:162: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:164: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:165: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:166: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:168: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:172: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:173: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:176: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:177: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:178: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:182: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:184: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:185: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:186: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:188: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:190: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:192: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:193: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:194: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:197: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:198: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:200: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:201: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:202: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:204: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:205: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:206: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:208: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:209: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [ ]:
df_m_5

,eu_High_last_day60,eu_Low_last_day60,eu_Close_last_day60,eu_High_last_day59,eu_Low_last_day59,eu_Close_last_day59,eu_High_last_day58,eu_Low_last_day58,eu_Close_last_day58,eu_High_last_day57,...,eu_Close_last_day3,eu_High_last_day2,eu_Low_last_day2,eu_Close_last_day2,eu_High_last_day1,eu_Low_last_day1,eu_Close_last_day1,eu_High_next_day1,eu_Low_next_day1,eu_Close_next_day1
60,100.250,99.130,100.210,100.430,99.930,100.210,100.380,100.200,100.350,100.350,...,104.244,104.749,104.024,104.225,104.690,103.971,104.653,103.582,102.000,102.267
61,100.430,99.930,100.210,100.380,100.200,100.350,100.350,99.780,99.862,100.254,...,104.225,104.690,103.971,104.653,104.839,102.972,103.385,102.193,101.765,102.103
62,100.380,100.200,100.350,100.350,99.780,99.862,100.254,99.570,100.170,100.254,...,104.653,104.839,102.972,103.385,103.582,102.000,102.267,102.931,102.057,102.666
63,100.350,99.780,99.862,100.254,99.570,100.170,100.254,99.786,100.247,101.352,...,103.385,103.582,102.000,102.267,102.193,101.765,102.103,103.439,102.524,103.241
64,100.254,99.570,100.170,100.254,99.786,100.247,101.352,100.170,101.291,101.353,...,102.267,102.193,101.765,102.103,102.931,102.057,102.666,103.364,101.842,102.282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2198,113.996,113.467,113.975,114.152,113.666,113.858,114.691,113.774,114.667,115.487,...,125.646,126.011,125.083,125.883,126.679,125.857,126.346,128.971,126.963,128.887
2199,114.152,113.666,113.858,114.691,113.774,114.667,115.487,114.470,115.355,115.683,...,125.883,126.679,125.857,126.346,126.994,126.233,126.993,129.406,127.456,127.876
2200,114.691,113.774,114.667,115.487,114.470,115.355,115.683,115.120,115.233,115.588,...,126.346,126.994,126.233,126.993,128.971,126.963,128.887,128.703,127.793,128.382
2201,115.487,114.470,115.355,115.683,115.120,115.233,115.588,114.920,115.131,115.190,...,126.993,128.971,126.963,128.887,129.406,127.456,127.876,129.106,127.735,128.531
2202,115.683,115.120,115.233,115.588,114.920,115.131,115.190,114.563,114.680,114.799,...,128.887,129.406,127.456,127.876,128.703,127.793,128.382,128.851,128.406,128.766

In [ ]:
extra_clone = pd.DataFrame(data=df_m_5)
print(extra_clone)

      eu_High_last_day60  eu_Low_last_day60  eu_Close_last_day60  \
60               100.250             99.130              100.210
61               100.430             99.930              100.210
62               100.380            100.200              100.350
63               100.350             99.780               99.862
64               100.254             99.570              100.170
...                  ...                ...                  ...
2198             113.996            113.467              113.975
2199             114.152            113.666              113.858
2200             114.691            113.774              114.667
2201             115.487            114.470              115.355
2202             115.683            115.120              115.233

      eu_High_last_day59  eu_Low_last_day59  eu_Close_last_day59  \
60               100.430             99.930              100.210
61               100.380            100.200              100.350
62               100.350             99.780               99.862
63               100.254             99.570              100.170
64               100.254             99.786              100.247
...                  ...                ...                  ...
2198             114.152            113.666              113.858
2199             114.691            113.774              114.667
2200             115.487            114.470              115.355
2201             115.683            115.120              115.233
2202             115.588            114.920              115.131

      eu_High_last_day58  eu_Low_last_day58  eu_Close_last_day58  \
60               100.380            100.200              100.350
61               100.350             99.780               99.862
62               100.254             99.570              100.170
63               100.254             99.786              100.247
64               101.352            100.170              101.291
...                  ...                ...                  ...
2198             114.691            113.774              114.667
2199             115.487            114.470              115.355
2200             115.683            115.120              115.233
2201             115.588            114.920              115.131
2202             115.190            114.563              114.680

      eu_High_last_day57  ...  eu_Close_last_day3  eu_High_last_day2  \
60               100.350  ...             104.244            104.749
61               100.254  ...             104.225            104.690
62               100.254  ...             104.653            104.839
63               101.352  ...             103.385            103.582
64               101.353  ...             102.267            102.193
...                  ...  ...                 ...                ...
2198             115.487  ...             125.646            126.011
2199             115.683  ...             125.883            126.679
2200             115.588  ...             126.346            126.994
2201             115.190  ...             126.993            128.971
2202             114.799  ...             128.887            129.406

      eu_Low_last_day2  eu_Close_last_day2  eu_High_last_day1  \
60             104.024             104.225            104.690
61             103.971             104.653            104.839
62             102.972             103.385            103.582
63             102.000             102.267            102.193
64             101.765             102.103            102.931
...                ...                 ...                ...
2198           125.083             125.883            126.679
2199           125.857             126.346            126.994
2200           126.233             126.993            128.971
2201           126.963             128.887            129.406
2202           127.456             127.876            128.703

      eu_Low_last_day1  eu_Close_last_day1  eu_High_next_day1  \
60             103.971             104.653            103.582
61             102.972             103.385            102.193
62             102.000             102.267            102.931
63             101.765             102.103            103.439
64             102.057             102.666            103.364
...                ...                 ...                ...
2198           125.857             126.346            128.971
2199           126.233             126.993            129.406
2200           126.963             128.887            128.703
2201           127.456             127.876            129.106
2202           127.793             128.382            128.851

      eu_Low_next_day1  eu_Close_next_day1
60             102.000             102.267
61             101.765             102.103
62             102.057             102.666
63             102.524             103.241
64             101.842             102.282
...                ...                 ...
2198           126.963             128.887
2199           127.456             127.876
2200           127.793             128.382
2201           127.735             128.531
2202           128.406             128.766

[2143 rows x 183 columns]

In [ ]:
extra_clone.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2143 entries, 60 to 2202
Columns: 183 entries, eu_High_last_day60 to eu_Close_next_day1
dtypes: float64(183)
memory usage: 3.0 MB

In [ ]:
#extract yesterday's row to predict today's row
#check if needs to be pd.DataFrame
last_row = pd.DataFrame(data=extra_clone.iloc[-10:,np.r_[0:93]])
last_row

,eu_High_last_day60,eu_Low_last_day60,eu_Close_last_day60,eu_High_last_day59,eu_Low_last_day59,eu_Close_last_day59,eu_High_last_day58,eu_Low_last_day58,eu_Close_last_day58,eu_High_last_day57,...,eu_Close_last_day33,eu_High_last_day32,eu_Low_last_day32,eu_Close_last_day32,eu_High_last_day31,eu_Low_last_day31,eu_Close_last_day31,eu_High_last_day30,eu_Low_last_day30,eu_Close_last_day30
2193,114.647,114.145,114.608,115.056,114.446,114.585,114.785,114.203,114.323,114.543,...,115.010,115.694,114.404,115.529,115.757,115.144,115.528,115.775,114.858,114.972
2194,115.056,114.446,114.585,114.785,114.203,114.323,114.543,113.960,114.096,114.149,...,115.529,115.757,115.144,115.528,115.775,114.858,114.972,115.288,114.697,114.908
2195,114.785,114.203,114.323,114.543,113.960,114.096,114.149,113.600,113.689,113.996,...,115.528,115.775,114.858,114.972,115.288,114.697,114.908,115.685,114.790,115.517
2196,114.543,113.960,114.096,114.149,113.600,113.689,113.996,113.467,113.975,114.152,...,114.972,115.288,114.697,114.908,115.685,114.790,115.517,115.803,115.381,115.458
2197,114.149,113.600,113.689,113.996,113.467,113.975,114.152,113.666,113.858,114.691,...,114.908,115.685,114.790,115.517,115.803,115.381,115.458,115.555,114.648,114.850
2198,113.996,113.467,113.975,114.152,113.666,113.858,114.691,113.774,114.667,115.487,...,115.517,115.803,115.381,115.458,115.555,114.648,114.850,115.469,114.818,115.311
2199,114.152,113.666,113.858,114.691,113.774,114.667,115.487,114.470,115.355,115.683,...,115.458,115.555,114.648,114.850,115.469,114.818,115.311,115.786,115.250,115.668
2200,114.691,113.774,114.667,115.487,114.470,115.355,115.683,115.120,115.233,115.588,...,114.850,115.469,114.818,115.311,115.786,115.250,115.668,115.938,115.555,115.857
2201,115.487,114.470,115.355,115.683,115.120,115.233,115.588,114.920,115.131,115.190,...,115.311,115.786,115.250,115.668,115.938,115.555,115.857,116.194,115.802,116.128
2202,115.683,115.120,115.233,115.588,114.920,115.131,115.190,114.563,114.680,114.799,...,115.668,115.938,115.555,115.857,116.194,115.802,116.128,117.353,116.081,117.292

In [ ]:
df_m_5 = pd.DataFrame(data=df_m_5.tail(2000))
df_m_5

,eu_High_last_day60,eu_Low_last_day60,eu_Close_last_day60,eu_High_last_day59,eu_Low_last_day59,eu_Close_last_day59,eu_High_last_day58,eu_Low_last_day58,eu_Close_last_day58,eu_High_last_day57,...,eu_Close_last_day3,eu_High_last_day2,eu_Low_last_day2,eu_Close_last_day2,eu_High_last_day1,eu_Low_last_day1,eu_Close_last_day1,eu_High_next_day1,eu_Low_next_day1,eu_Close_next_day1
203,102.115,101.312,101.574,101.673,101.361,101.506,101.595,101.100,101.498,101.599,...,102.562,102.923,102.460,102.592,102.640,101.782,102.097,102.142,101.509,102.024
204,101.673,101.361,101.506,101.595,101.100,101.498,101.599,101.187,101.321,101.618,...,102.592,102.640,101.782,102.097,102.459,101.996,102.087,102.227,102.021,102.187
205,101.595,101.100,101.498,101.599,101.187,101.321,101.618,100.822,101.360,101.814,...,102.097,102.459,101.996,102.087,102.142,101.509,102.024,102.361,102.090,102.258
206,101.599,101.187,101.321,101.618,100.822,101.360,101.814,101.355,101.732,102.005,...,102.087,102.142,101.509,102.024,102.227,102.021,102.187,102.544,102.222,102.418
207,101.618,100.822,101.360,101.814,101.355,101.732,102.005,101.593,101.956,102.051,...,102.024,102.227,102.021,102.187,102.361,102.090,102.258,102.655,102.309,102.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2198,113.996,113.467,113.975,114.152,113.666,113.858,114.691,113.774,114.667,115.487,...,125.646,126.011,125.083,125.883,126.679,125.857,126.346,128.971,126.963,128.887
2199,114.152,113.666,113.858,114.691,113.774,114.667,115.487,114.470,115.355,115.683,...,125.883,126.679,125.857,126.346,126.994,126.233,126.993,129.406,127.456,127.876
2200,114.691,113.774,114.667,115.487,114.470,115.355,115.683,115.120,115.233,115.588,...,126.346,126.994,126.233,126.993,128.971,126.963,128.887,128.703,127.793,128.382
2201,115.487,114.470,115.355,115.683,115.120,115.233,115.588,114.920,115.131,115.190,...,126.993,128.971,126.963,128.887,129.406,127.456,127.876,129.106,127.735,128.531
2202,115.683,115.120,115.233,115.588,114.920,115.131,115.190,114.563,114.680,114.799,...,128.887,129.406,127.456,127.876,128.703,127.793,128.382,128.851,128.406,128.766

In [ ]:
#create initial train and test data as pd.DF for close
#final test DF is last_row
df_m_5_train_close = pd.DataFrame(data=df_m_5.iloc[0:1980,:])
df_m_5_test_close = pd.DataFrame(data=df_m_5.iloc[1980:2001,:])

#df_m_5_train_close = pd.DataFrame(data=df_m_5.iloc[0:1980,[2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92]])
#df_m_5_test_close = pd.DataFrame(data=df_m_5.iloc[1980:2001,[2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92]])
print(df_m_5_train_close )
print(df_m_5_test_close )

      eu_High_last_day60  eu_Low_last_day60  eu_Close_last_day60  \
203              102.115            101.312              101.574
204              101.673            101.361              101.506
205              101.595            101.100              101.498
206              101.599            101.187              101.321
207              101.618            100.822              101.360
...                  ...                ...                  ...
2178             114.911            114.307              114.883
2179             114.946            114.703              114.819
2180             115.034            114.664              114.967
2181             115.204            114.912              115.050
2182             115.195            115.002              115.094

      eu_High_last_day59  eu_Low_last_day59  eu_Close_last_day59  \
203              101.673            101.361              101.506
204              101.595            101.100              101.498
205              101.599            101.187              101.321
206              101.618            100.822              101.360
207              101.814            101.355              101.732
...                  ...                ...                  ...
2178             114.946            114.703              114.819
2179             115.034            114.664              114.967
2180             115.204            114.912              115.050
2181             115.195            115.002              115.094
2182             115.364            114.945              115.321

      eu_High_last_day58  eu_Low_last_day58  eu_Close_last_day58  \
203              101.595            101.100              101.498
204              101.599            101.187              101.321
205              101.618            100.822              101.360
206              101.814            101.355              101.732
207              102.005            101.593              101.956
...                  ...                ...                  ...
2178             115.034            114.664              114.967
2179             115.204            114.912              115.050
2180             115.195            115.002              115.094
2181             115.364            114.945              115.321
2182             116.348            115.271              116.127

      eu_High_last_day57  ...  eu_Close_last_day3  eu_High_last_day2  \
203              101.599  ...             102.562            102.923
204              101.618  ...             102.592            102.640
205              101.814  ...             102.097            102.459
206              102.005  ...             102.087            102.142
207              102.051  ...             102.024            102.227
...                  ...  ...                 ...                ...
2178             115.204  ...             118.756            119.022
2179             115.195  ...             118.586            119.398
2180             115.364  ...             119.151            119.497
2181             116.348  ...             119.465            121.029
2182             116.240  ...             120.803            121.411

      eu_Low_last_day2  eu_Close_last_day2  eu_High_last_day1  \
203            102.460             102.592            102.640
204            101.782             102.097            102.459
205            101.996             102.087            102.142
206            101.509             102.024            102.227
207            102.021             102.187            102.361
...                ...                 ...                ...
2178           118.365             118.586            119.398
2179           118.467             119.151            119.497
2180           119.036             119.465            121.029
2181           119.435             120.803            121.411
2182           120.588             121.138            122.404

      eu_Low_last_day1  eu_Close_last_day1  eu_High_next_day1  \
203            101.782             102.097            102.142
204            101.996             102.087            102.227
205            101.509             102.024            102.361
206            102.021             102.187            102.544
207            102.090             102.258            102.655
...                ...                 ...                ...
2178           118.467             119.151            121.029
2179           119.036             119.465            121.411
2180           119.435             120.803            122.404
2181           120.588             121.138            122.432
2182           120.948             122.355            125.100

      eu_Low_next_day1  eu_Close_next_day1
203            101.509             102.024
204            102.021             102.187
205            102.090             102.258
206            102.222             102.418
207            102.309             102.448
...                ...                 ...
2178           119.435             120.803
2179           120.588             121.138
2180           120.948             122.355
2181           121.176             122.089
2182           122.006             123.902

[1980 rows x 183 columns]
      eu_High_last_day60  eu_Low_last_day60  eu_Close_last_day60  \
2183             115.364            114.945              115.321
2184             116.348            115.271              116.127
2185             116.240            115.618              116.099
2186             116.183            115.623              115.841
2187             116.045            115.533              115.549
2188             115.848            115.039              115.189
2189             115.679            115.122              115.293
2190             115.463            114.376              114.631
2191             114.700            113.996              114.157
2192             114.265            113.479              114.198
2193             114.647            114.145              114.608
2194             115.056            114.446              114.585
2195             114.785            114.203              114.323
2196             114.543            113.960              114.096
2197             114.149            113.600              113.689
2198             113.996            113.467              113.975
2199             114.152            113.666              113.858
2200             114.691            113.774              114.667
2201             115.487            114.470              115.355
2202             115.683            115.120              115.233

      eu_High_last_day59  eu_Low_last_day59  eu_Close_last_day59  \
2183             116.348            115.271              116.127
2184             116.240            115.618              116.099
2185             116.183            115.623              115.841
2186             116.045            115.533              115.549
2187             115.848            115.039              115.189
2188             115.679            115.122              115.293
2189             115.463            114.376              114.631
2190             114.700            113.996              114.157
2191             114.265            113.479              114.198
2192             114.647            114.145              114.608
2193             115.056            114.446              114.585
2194             114.785            114.203              114.323
2195             114.543            113.960              114.096
2196             114.149            113.600              113.689
2197             113.996            113.467              113.975
2198             114.152            113.666              113.858
2199             114.691            113.774              114.667
2200             115.487            114.470              115.355
2201             115.683            115.120              115.233
2202             115.588            114.920              115.131

      eu_High_last_day58  eu_Low_last_day58  eu_Close_last_day58  \
2183             116.240            115.618              116.099
2184             116.183            115.623              115.841
2185             116.045            115.533              115.549
2186             115.848            115.039              115.189
2187             115.679            115.122              115.293
2188             115.463            114.376              114.631
2189             114.700            113.996              114.157
2190             114.265            113.479              114.198
2191             114.647            114.145              114.608
2192             115.056            114.446              114.585
2193             114.785            114.203              114.323
2194             114.543            113.960              114.096
2195             114.149            113.600              113.689
2196             113.996            113.467              113.975
2197             114.152            113.666              113.858
2198             114.691            113.774              114.667
2199             115.487            114.470              115.355
2200             115.683            115.120              115.233
2201             115.588            114.920              115.131
2202             115.190            114.563              114.680

      eu_High_last_day57  ...  eu_Close_last_day3  eu_High_last_day2  \
2183             116.183  ...             121.138            122.404
2184             116.045  ...             122.355            122.432
2185             115.848  ...             122.089            125.100
2186             115.679  ...             123.902            124.300
2187             115.463  ...             122.885            123.197
2188             114.700  ...             121.823            122.451
2189             114.265  ...             121.691            123.031
2190             114.647  ...             122.546            122.955
2191             115.056  ...             122.765            123.668
2192             114.785  ...             123.587            124.048
2193             114.543  ...             123.783            124.002
2194             114.149  ...             123.967            124.673
2195             113.996  ...             124.280            125.768
2196             114.152  ...             125.390            125.756
2197             114.691  ...             125.397            126.312
2198             115.487  ...             125.646            126.011
2199             115.683  ...             125.883            126.679
2200             115.588  ...             126.346            126.994
2201             115.190  ...             126.993            128.971
2202             114.799  ...             128.887            129.406

      eu_Low_last_day2  eu_Close_last_day2  eu_High_last_day1  \
2183           120.948             122.355            122.432
2184           121.176             122.089            125.100
2185           122.006             123.902            124.300
2186           121.975             122.885            123.197
2187           121.309             121.823            122.451
2188           121.279             121.691            123.031
2189           121.627             122.546            122.955
2190           122.260             122.765            123.668
2191           122.372             123.587            124.048
2192           123.460             123.783            124.002
2193           123.466             123.967            124.673
2194           123.664             124.280            125.768
2195           124.030             125.390            125.756
2196           124.761             125.397            126.312
2197           125.319             125.646            126.011
2198           125.083             125.883            126.679
2199           125.857             126.346            126.994
2200           126.233             126.993            128.971
2201           126.963             128.887            129.406
2202           127.456             127.876            128.703

      eu_Low_last_day1  eu_Close_last_day1  eu_High_next_day1  \
2183           121.176             122.089            124.300
2184           122.006             123.902            123.197
2185           121.975             122.885            122.451
2186           121.309             121.823            123.031
2187           121.279             121.691            122.955
2188           121.627             122.546            123.668
2189           122.260             122.765            124.048
2190           122.372             123.587            124.002
2191           123.460             123.783            124.673
2192           123.466             123.967            125.768
2193           123.664             124.280            125.756
2194           124.030             125.390            126.312
2195           124.761             125.397            126.011
2196           125.319             125.646            126.679
2197           125.083             125.883            126.994
2198           125.857             126.346            128.971
2199           126.233             126.993            129.406
2200           126.963             128.887            128.703
2201           127.456             127.876            129.106
2202           127.793             128.382            128.851

      eu_Low_next_day1  eu_Close_next_day1
2183           121.975             122.885
2184           121.309             121.823
2185           121.279             121.691
2186           121.627             122.546
2187           122.260             122.765
2188           122.372             123.587
2189           123.460             123.783
2190           123.466             123.967
2191           123.664             124.280
2192           124.030             125.390
2193           124.761             125.397
2194           125.319             125.646
2195           125.083             125.883
2196           125.857             126.346
2197           126.233             126.993
2198           126.963             128.887
2199           127.456             127.876
2200           127.793             128.382
2201           127.735             128.531
2202           128.406             128.766

[20 rows x 183 columns]

In [ ]:
# #create initial train and test data as pd.DF for low
# #final test DF is last_row
# df_m_5_train_low = pd.DataFrame(data=df_m_5.iloc[0:7980,[1,4,7,10,13,16,19,22,25,28,31,34,37,40,43,46,49,52,55,58,61,64,67,70,73,76,79,82,85,88,91]])


# df_m_5_test_low = pd.DataFrame(data=df_m_5.iloc[7980:8001,[1,4,7,10,13,16,19,22,25,28,31,34,37,40,43,46,49,52,55,58,61,64,67,70,73,76,79,82,85,88,91]])
# print(df_m_5_train_low )
# print(df_m_5_test_low )

In [ ]:
# #create initial train and test data as pd.DF for high
# #final test DF is last_row
# df_m_5_train_high = pd.DataFrame(data=df_m_5.iloc[0:7980,[0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90]])

# df_m_5_test_high= pd.DataFrame(data=df_m_5.iloc[7980:8001,[0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90]])
# print(df_m_5_train_high )
# print(df_m_5_test_high )

In [ ]:
# #new column: high vs low
# df_m_5['eu_h_or_l'] = ((df_m_5.eu_h - df_m_5.eu_o) > (df_m_5.eu_o - df_m_5.eu_l)) 
# df_m_5.eu_h_or_l = df_m_5.eu_h_or_l.replace({True:1,False:0})

# #new column: close vs yesterday
# df_m_5['eu_c_vs_c'] = (df_m_5.eu_c > df_m_5.eu_o) 
# df_m_5.eu_c_vs_c = df_m_5.eu_c_vs_c.replace({True:1,False:0})

# #new column: shift tomorrow to today
# df_m_5['eu_High_next_day'] = df_m_5['eu_h'].shift(-1)
# df_m_5['eu_Low_next_day'] = df_m_5['eu_l'].shift(-1)
# df_m_5['eu_Close_next_day'] = df_m_5['eu_c'].shift(-1)
# df_m_5 = df_m_5.dropna()

In [ ]:

print(df_m_5_train_close.isna().sum())
print(df_m_5_test_close.isna().sum())

eu_High_last_day60     0
eu_Low_last_day60      0
eu_Close_last_day60    0
eu_High_last_day59     0
eu_Low_last_day59      0
                      ..
eu_Low_last_day1       0
eu_Close_last_day1     0
eu_High_next_day1      0
eu_Low_next_day1       0
eu_Close_next_day1     0
Length: 183, dtype: int64
eu_High_last_day60     0
eu_Low_last_day60      0
eu_Close_last_day60    0
eu_High_last_day59     0
eu_Low_last_day59      0
                      ..
eu_Low_last_day1       0
eu_Close_last_day1     0
eu_High_next_day1      0
eu_Low_next_day1       0
eu_Close_next_day1     0
Length: 183, dtype: int64

In [ ]:
print(df_m_5_train_close.info())
print(df_m_5_test_close.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1980 entries, 203 to 2182
Columns: 183 entries, eu_High_last_day60 to eu_Close_next_day1
dtypes: float64(183)
memory usage: 2.8 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 2183 to 2202
Columns: 183 entries, eu_High_last_day60 to eu_Close_next_day1
dtypes: float64(183)
memory usage: 28.8 KB
None

In [ ]:
# print(df_m_5_train_high.isna().sum())
# print(df_m_5_test_high.isna().sum())
# print(df_m_5_train_high.info())
# print(df_m_5_test_high.info())

In [ ]:
# print(df_m_5_train_low.isna().sum())
# print(df_m_5_test_low.isna().sum())
# print(df_m_5_train_low.info())
# print(df_m_5_test_low.info())

In [ ]:
train_close = df_m_5_train_close
train_close=train_close.sample(n=2000, replace=True)
train_close.head()

,eu_High_last_day60,eu_Low_last_day60,eu_Close_last_day60,eu_High_last_day59,eu_Low_last_day59,eu_Close_last_day59,eu_High_last_day58,eu_Low_last_day58,eu_Close_last_day58,eu_High_last_day57,...,eu_Close_last_day3,eu_High_last_day2,eu_Low_last_day2,eu_Close_last_day2,eu_High_last_day1,eu_Low_last_day1,eu_Close_last_day1,eu_High_next_day1,eu_Low_next_day1,eu_Close_next_day1
887,117.427,115.220,115.333,117.179,115.067,116.955,117.530,115.964,116.007,116.342,...,110.657,111.197,110.179,111.123,111.311,110.713,111.026,112.193,111.238,111.388
762,104.983,102.447,104.664,104.875,103.908,104.476,105.935,103.974,105.340,106.313,...,101.017,101.779,100.744,101.379,101.667,101.212,101.635,103.666,102.667,103.494
1856,105.731,105.340,105.676,105.801,105.399,105.435,105.724,105.399,105.541,105.663,...,103.078,103.591,103.085,103.308,103.890,103.249,103.283,103.648,103.353,103.536
1419,109.993,109.318,109.554,109.797,109.418,109.611,109.947,109.452,109.554,109.582,...,112.006,112.094,111.886,112.026,112.041,111.842,111.970,112.058,111.762,111.970
1038,111.045,109.841,110.663,110.914,110.641,110.735,110.825,110.243,110.302,110.356,...,113.875,114.240,113.476,113.735,114.073,113.335,113.985,113.829,113.020,113.163

In [ ]:
#predict close
label_c = 'eu_Close_next_day1' 
print("Summary of class variable: \n", train_close[label_c].describe())

Summary of class variable:
 count    2000.000000
mean      111.440481
std         5.281300
min        99.876000
25%       107.938500
50%       110.455000
75%       113.970000
max       125.576000
Name: eu_Close_next_day1, dtype: float64

In [ ]:
train_close = pd.DataFrame(train_close.drop_duplicates(keep=False))

In [ ]:
train_close.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 738 entries, 887 to 374
Columns: 183 entries, eu_High_last_day60 to eu_Close_next_day1
dtypes: float64(183)
memory usage: 1.0 MB

In [ ]:
#predict close
save_path='agModels-predictClose'
predictor = TabularPredictor(label=label_c, path=save_path)
predictor.fit(train_close, hyperparameters={ 'XGB':{} } , presets='best_quality')
#predictor.fit(train_close, excluded_model_types=['CatBoost'], presets='best_quality') #is slower

Warning: path already exists! This predictor may overwrite an existing predictor! path="agModels-predictClose"
Presets specified: ['best_quality']
Beginning AutoGluon training ...
AutoGluon will save models to "agModels-predictClose/"
AutoGluon Version:  0.4.0
Python Version:     3.7.13
Operating System:   Linux
Train Data Rows:    738
Train Data Columns: 182
Label Column: eu_Close_next_day1
Preprocessing data ...
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (124.398, 100.238, 111.36502, 5.29013)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10868.92 MB
	Train Data (Original)  Memory Usage: 1.07 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 182 | ['eu_High_last_day60', 'eu_Low_last_day60', 'eu_Close_last_day60', 'eu_High_last_day59', 'eu_Low_last_day59', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 182 | ['eu_High_last_day60', 'eu_Low_last_day60', 'eu_Close_last_day60', 'eu_High_last_day59', 'eu_Low_last_day59', ...]
	0.7s = Fit runtime
	182 features in original data used to generate 182 features in processed data.
	Train Data (Processed) Memory Usage: 1.07 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.88s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	To change this, specify the eval_metric parameter of Predictor()
Fitting 1 L1 models ...
Fitting model: XGBoost_BAG_L1 ...
	Fitting 7 child models (S1F1 - S1F7) | Fitting with ParallelLocalFoldFittingStrategy

In [ ]:
#contrast leaderboard result of train and test data
predictor.leaderboard(train_close, silent=True)

In [ ]:
#predict close
test_close = TabularDataset(df_m_5_test_close)
y_test = test_close[label_c]
test_close_nolab = test_close.drop(columns=[label_c])
test_close_nolab.tail()

In [ ]:
#predict eu_Close_next_day1
predictor = TabularPredictor.load(save_path)
y_pred = predictor.predict(test_close_nolab)
print("Predictions: \n", y_pred)
perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

In [ ]:
# #predict high
# train_high = df_m_5_train_high
# train_high=train_high.sample(n=7900, replace=True)
# train_high.head()

In [ ]:
# #predict high
# label_h = 'eu_High_next_day1' 
# print("Summary of class variable: \n", train_high[label_h].describe())

In [ ]:
# #predict high
# save_path='agModels-predictHigh'
# predictor = TabularPredictor(label=label_h, path=save_path).fit(train_high,hyperparameters={ 'NN':{} } , presets='high_quality_fast_inference_only_refit')#, presets='best_quality')
# #.fit(presets='best_quality) is slower

In [ ]:
# #contrast leaderboard result of train and test data
# predictor.leaderboard(train_high, silent=True)

In [ ]:
# #predict high
# test_high = TabularDataset(df_m_5_test_high)
# y_test = test_high[label_h]
# test_high_nolab = test_high.drop(columns=[label_h])
# test_high_nolab.tail()

In [ ]:
# #first run to predict eu_High_next_day1
# predictor = TabularPredictor.load(save_path)
# y_pred = predictor.predict(test_high_nolab)
# print("Predictions: \n", y_pred) #try print more rows
# perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

In [ ]:
# #predict low
# train_low = df_m_5_train_low
# train_low=train_low.sample(n=7900, replace=True)
# train_low.head()

In [ ]:
# #predict low
# label_l = 'eu_Low_next_day1' 
# print("Summary of class variable: \n", train_low[label_l].describe())

In [ ]:
# #predict low
# save_path='agModels-predictLow'
# predictor = TabularPredictor(label=label_l, path=save_path).fit(train_low,hyperparameters={ 'NN':{} } , presets='high_quality_fast_inference_only_refit')#, presets='best_quality')
# #.fit(presets='best_quality) is slower

In [ ]:
# #contrast leaderboard result of train and test data
# predictor.leaderboard(train_low, silent=True)

In [ ]:
# #predict low
# test_low = TabularDataset(df_m_5_test_low)
# y_test = test_low[label_l]
# test_low_nolab = test_low.drop(columns=[label_l])
# test_low_nolab.tail()

In [ ]:
# #predict eu_Low_next_day1
# predictor = TabularPredictor.load(save_path)
# y_pred = predictor.predict(test_low_nolab)
# print("Predictions: \n", y_pred)
# perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

In [ ]:
# clears the model after a run so you can contrast new runs.
# predictor.unpersist_models('ag_predict_interval')
# predictor.save_space()
# predictor.delete_models(models_to_keep='best', dry_run=False)
%rm -rf AutogluonModels, ag_predict_interval
!ls