<a href="https://colab.research.google.com/github/gomlfx/ApiaryFund/blob/master/AGC27_1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install autogluon

Requirement already satisfied: autogluon in /usr/local/lib/python3.7/dist-packages (0.4.0)
Requirement already satisfied: autogluon.tabular[all]==0.4.0 in /usr/local/lib/python3.7/dist-packages (from autogluon) (0.4.0)
Requirement already satisfied: autogluon.vision==0.4.0 in /usr/local/lib/python3.7/dist-packages (from autogluon) (0.4.0)
Requirement already satisfied: autogluon.text==0.4.0 in /usr/local/lib/python3.7/dist-packages (from autogluon) (0.4.0)
Requirement already satisfied: autogluon.core[all]==0.4.0 in /usr/local/lib/python3.7/dist-packages (from autogluon) (0.4.0)
Requirement already satisfied: autogluon.features==0.4.0 in /usr/local/lib/python3.7/dist-packages (from autogluon) (0.4.0)
Requirement already satisfied: scikit-learn<1.1,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (1.0.2)
Requirement already satisfied: distributed<=2021.11.2,>=2021.09.1 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (2021.11.2)
Requirement already satisfied: numpy<1.23,>=1.21 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (1.21.6)
Requirement already satisfied: pandas<1.4,>=1.2.5 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (1.3.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (2.23.0)
Requirement already satisfied: autogluon.common==0.4.0 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (0.4.0)
Requirement already satisfied: tqdm>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (4.64.0)
Requirement already satisfied: dask<=2021.11.2,>=2021.09.1 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (2021.11.2)
Requirement already satisfied: boto3 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (1.21.46)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (3.2.2)
Requirement already satisfied: scipy<1.8.0,>=1.5.4 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (1.7.3)
Requirement already satisfied: ray<1.9,>=1.7 in /usr/local/lib/python3.7/dist-packages (from autogluon.core[all]==0.4.0->autogluon) (1.8.0)
Requirement already satisfied: psutil<5.9,>=5.7.3 in /usr/local/lib/python3.7/dist-packages (from autogluon.features==0.4.0->autogluon) (5.8.0)
Requirement already satisfied: networkx<3.0,>=2.3 in /usr/local/lib/python3.7/dist-packages (from autogluon.tabular[all]==0.4.0->autogluon) (2.6.3)
Requirement already satisfied: torch<1.11,>=1.0 in /usr/local/lib/python3.7/dist-packages (from autogluon.tabular[all]==0.4.0->autogluon) (1.10.0+cu111)
Requirement already satisfied: lightgbm<3.4,>=3.3 in /usr/local/lib/python3.7/dist-packages (from autogluon.tabular[all]==0.4.0->autogluon) (3.3.2)
Requirement already satisfied: xgboost<1.5,>=1.4 in /usr/local/lib/python3.7/dist-packages (from autogluon.tabular[all]==0.4.0->autogluon) (1.4.2)
Requirement already satisfied: catboost<1.1,>=1.0 in /usr/local/lib/python3.7/dist-packages (from autogluon.tabular[all]==0.4.0->autogluon) (1.0.5)
Requirement already satisfied: fastai<2.6,>=2.3.1 in /usr/local/lib/python3.7/dist-packages (from autogluon.tabular[all]==0.4.0->autogluon) (2.5.6)
Requirement already satisfied: torchmetrics<0.8.0,>=0.7.2 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (0.7.3)
Requirement already satisfied: scikit-image<0.20.0,>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (0.19.2)
Requirement already satisfied: pytorch-lightning<1.6.0,>=1.5.10 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (1.5.10)
Requirement already satisfied: smart-open<5.3.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (5.2.1)
Requirement already satisfied: nptyping<1.5.0,>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (1.4.4)
Requirement already satisfied: Pillow<9.1.0,>=9.0.0 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (9.0.1)
Requirement already satisfied: omegaconf<2.2.0,>=2.1.1 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (2.1.2)
Requirement already satisfied: fairscale<0.5.0,>=0.4.5 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (0.4.6)
Requirement already satisfied: timm<0.6.0,>=0.5.4 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (0.5.4)
Requirement already satisfied: sentencepiece<0.2.0,>=0.1.95 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (0.1.95)
Requirement already satisfied: autogluon-contrib-nlp==0.0.1b20220208 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (0.0.1b20220208)
Requirement already satisfied: transformers<4.17.0,>=4.16.2 in /usr/local/lib/python3.7/dist-packages (from autogluon.text==0.4.0->autogluon) (4.16.2)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (6.0.1)
Requirement already satisfied: contextvars in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (2.4)
Requirement already satisfied: protobuf in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (3.17.3)
Requirement already satisfied: yacs>=0.1.6 in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (0.1.8)
Requirement already satisfied: tokenizers>=0.9.4 in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (0.12.1)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (2019.12.20)
Requirement already satisfied: sacremoses>=0.0.38 in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (0.0.49)
Requirement already satisfied: sacrebleu in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (2.0.0)
Requirement already satisfied: flake8 in /usr/local/lib/python3.7/dist-packages (from autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (3.9.2)
Requirement already satisfied: gluoncv<0.10.6,>=0.10.5 in /usr/local/lib/python3.7/dist-packages (from autogluon.vision==0.4.0->autogluon) (0.10.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost<1.1,>=1.0->autogluon.tabular[all]==0.4.0->autogluon) (5.5.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost<1.1,>=1.0->autogluon.tabular[all]==0.4.0->autogluon) (0.8.4)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost<1.1,>=1.0->autogluon.tabular[all]==0.4.0->autogluon) (1.15.0)
Requirement already satisfied: partd>=0.3.10 in /usr/local/lib/python3.7/dist-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (1.2.0)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (0.11.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (21.3)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (2022.3.0)
Requirement already satisfied: cloudpickle>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (2.0.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (1.0.3)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (7.1.2)
Requirement already satisfied: tornado>=5 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (5.1.1)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (1.7.0)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (2.4.0)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (2.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (59.5.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from distributed<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (2.11.3)
Requirement already satisfied: fastcore<1.5,>=1.3.27 in /usr/local/lib/python3.7/dist-packages (from fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (1.4.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.7/dist-packages (from fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (1.0.2)
Requirement already satisfied: pip in /usr/local/lib/python3.7/dist-packages (from fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (21.1.3)
Requirement already satisfied: torchvision>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (0.11.1+cu111)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.7/dist-packages (from fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (0.0.5)
Requirement already satisfied: spacy<4 in /usr/local/lib/python3.7/dist-packages (from fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (2.2.4)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/dist-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.4.0->autogluon) (4.1.2.30)
Requirement already satisfied: autocfg in /usr/local/lib/python3.7/dist-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.4.0->autogluon) (0.0.8)
Requirement already satisfied: portalocker in /usr/local/lib/python3.7/dist-packages (from gluoncv<0.10.6,>=0.10.5->autogluon.vision==0.4.0->autogluon) (2.4.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/dist-packages (from lightgbm<3.4,>=3.3->autogluon.tabular[all]==0.4.0->autogluon) (0.37.1)
Requirement already satisfied: typish>=1.7.0 in /usr/local/lib/python3.7/dist-packages (from nptyping<1.5.0,>=1.4.4->autogluon.text==0.4.0->autogluon) (1.9.3)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /usr/local/lib/python3.7/dist-packages (from omegaconf<2.2.0,>=2.1.1->autogluon.text==0.4.0->autogluon) (4.8)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (3.0.8)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<1.4,>=1.2.5->autogluon.core[all]==0.4.0->autogluon) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<1.4,>=1.2.5->autogluon.core[all]==0.4.0->autogluon) (2.8.2)
Requirement already satisfied: locket in /usr/local/lib/python3.7/dist-packages (from partd>=0.3.10->dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (1.0.0)
Requirement already satisfied: tensorboard>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (2.8.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (4.1.1)
Requirement already satisfied: future>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (0.18.2)
Requirement already satisfied: pyDeprecate==0.3.1 in /usr/local/lib/python3.7/dist-packages (from pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (0.3.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/dist-packages (from fsspec>=0.6.0->dask<=2021.11.2,>=2021.09.1->autogluon.core[all]==0.4.0->autogluon) (3.8.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (3.6.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.7/dist-packages (from ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (21.4.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (4.3.3)
Requirement already satisfied: redis>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (4.2.2)
Requirement already satisfied: grpcio>=1.28.1 in /usr/local/lib/python3.7/dist-packages (from ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (1.44.0)
Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.0->ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (4.0.2)
Requirement already satisfied: deprecated>=1.2.3 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.0->ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (1.2.13)
Requirement already satisfied: importlib-metadata>=1.0 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.0->ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (4.11.3)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/dist-packages (from deprecated>=1.2.3->redis>=3.5.0->ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (1.14.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.0->redis>=3.5.0->ray<1.9,>=1.7->autogluon.core[all]==0.4.0->autogluon) (3.8.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses>=0.0.38->autogluon-contrib-nlp==0.0.1b20220208->autogluon.text==0.4.0->autogluon) (1.1.0)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.20.0,>=0.19.1->autogluon.text==0.4.0->autogluon) (1.3.0)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.20.0,>=0.19.1->autogluon.text==0.4.0->autogluon) (2021.11.2)
Requirement already satisfied: imageio>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from scikit-image<0.20.0,>=0.19.1->autogluon.text==0.4.0->autogluon) (2.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.1,>=1.0.0->autogluon.core[all]==0.4.0->autogluon) (3.1.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (3.0.6)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (1.0.6)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (2.0.6)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (0.9.1)
Requirement already satisfied: thinc==7.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (7.4.0)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (1.1.3)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (0.4.1)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (1.0.0)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<4->fastai<2.6,>=2.3.1->autogluon.tabular[all]==0.4.0->autogluon) (1.0.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->autogluon.core[all]==0.4.0->autogluon) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->autogluon.core[all]==0.4.0->autogluon) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->autogluon.core[all]==0.4.0->autogluon) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->autogluon.core[all]==0.4.0->autogluon) (2021.10.8)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (1.0.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (0.4.6)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (1.8.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (3.3.6)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (1.35.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.7/dist-packages (from tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (1.0.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning<1.6.0,>=1.5.10->autogluon.text==0.4.0->autogluon) (4.2.4)

In [ ]:
!pip install --upgrade mxnet

Requirement already satisfied: mxnet in /usr/local/lib/python3.7/dist-packages (1.9.0)
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /usr/local/lib/python3.7/dist-packages (from mxnet) (1.21.6)
Requirement already satisfied: requests<3,>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from mxnet) (2.23.0)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from mxnet) (0.8.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.20.0->mxnet) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.20.0->mxnet) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.20.0->mxnet) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.20.0->mxnet) (3.0.4)

In [ ]:
#designed for Jupyter/kaggle/colab
import pandas as pd
import numpy as np
#import matplotlib for plotting 
import matplotlib.pyplot as plt
%matplotlib inline
#import normalization
from sklearn import preprocessing

#autogluon
from autogluon.tabular import TabularDataset, TabularPredictor

In [ ]:
 #MT4 csv 
df_m_5=pd.read_csv('CHFJPY1440.csv', names=['d','t','eu_o','eu_h','eu_l','eu_c','eu_v'])


# df2=pd.read_csv('GBPUSD1440.csv', names=['d','t','gu_o','gu_h','gu_l','gu_c','gu_v'])
# df2 = df2.tail(2000)

# df3=pd.read_csv('USDCAD1440.csv', names=['d','t','uc_o','uc_h','uc_l','uc_c','uc_v'])
# df3 = df3.tail(2000)

# df4=pd.read_csv('USDCHF1440.csv', names=['d','t','uf_o','uf_h','uf_l','uf_c','uf_v'])
# df4 = df4.tail(2000)

# df5=pd.read_csv('USDJPY1440.csv', names=['d','t','uj_o','uj_h','uj_l','uj_c','uj_v'])
# df5 = df5.tail(2000)

# df6=pd.read_csv('USDSEK1440.csv', names=['d','t','us_o','us_h','us_l','us_c','us_v'])
# df6 = df6.tail(2000)

# #using merge
# df_m_1 = df1.merge(df2, on='d')
# df_m_2 = df_m_1.merge(df3, on='d')
# df_m_3 = df_m_2.merge(df4, on='d')
# df_m_4 = df_m_3.merge(df5, on='d')
# df_m_5 = df_m_4.merge(df6, on='d')
# df_m_5 = df_m_5.drop(columns='t_x')
# df_m_5 = df_m_5.drop(columns='t_y')

# pd.set_option('display.max_columns', None)
# print(df_m_5)

In [ ]:
df_m_5

               d      t     eu_o     eu_h     eu_l     eu_c   eu_v
0     2013.11.04  00:00  108.290  108.470  107.970  108.350  11784
1     2013.11.05  00:00  108.360  108.410  107.540  107.790  14965
2     2013.11.06  00:00  107.790  108.490  107.680  108.140  13621
3     2013.11.07  00:00  108.120  108.290  106.780  107.090  23041
4     2013.11.08  00:00  107.110  107.600  106.790  107.470  19620
...          ...    ...      ...      ...      ...      ...    ...
2188  2022.04.18  00:00  133.975  134.452  133.855  134.397  35497
2189  2022.04.19  00:00  134.377  136.179  134.350  135.348  46502
2190  2022.04.20  00:00  135.330  135.865  134.574  134.820  50170
2191  2022.04.21  00:00  134.640  135.358  134.440  134.645  46633
2192  2022.04.22  00:00  134.576  134.879  133.918  134.331  47288

[2193 rows x 7 columns]

In [ ]:
#Features


#30 days ago
df_m_5['eu_High_last_day30'] = df_m_5['eu_h'].shift(30)
df_m_5['eu_Low_last_day30'] = df_m_5['eu_l'].shift(30)
df_m_5['eu_Close_last_day30'] = df_m_5['eu_c'].shift(30) 
#29 days ago 
df_m_5['eu_High_last_day29'] = df_m_5['eu_h'].shift(29)
df_m_5['eu_Low_last_day29'] = df_m_5['eu_l'].shift(29)
df_m_5['eu_Close_last_day29'] = df_m_5['eu_c'].shift(29)
#28 days ago
df_m_5['eu_High_last_day28'] = df_m_5['eu_h'].shift(28)
df_m_5['eu_Low_last_day28'] = df_m_5['eu_l'].shift(28)
df_m_5['eu_Close_last_day28'] = df_m_5['eu_c'].shift(28) 
#27 days ago
df_m_5['eu_High_last_day27'] = df_m_5['eu_h'].shift(27)
df_m_5['eu_Low_last_day27'] = df_m_5['eu_l'].shift(27)
df_m_5['eu_Close_last_day27'] = df_m_5['eu_c'].shift(27)
#26 day ago
df_m_5['eu_High_last_day26'] = df_m_5['eu_h'].shift(26)
df_m_5['eu_Low_last_day26'] = df_m_5['eu_l'].shift(26)
df_m_5['eu_Close_last_day26'] = df_m_5['eu_c'].shift(26)
#25 days ago
df_m_5['eu_High_last_day25'] = df_m_5['eu_h'].shift(25)
df_m_5['eu_Low_last_day25'] = df_m_5['eu_l'].shift(25)
df_m_5['eu_Close_last_day25'] = df_m_5['eu_c'].shift(25) 
#24 days ago 
df_m_5['eu_High_last_day24'] = df_m_5['eu_h'].shift(24)
df_m_5['eu_Low_last_day24'] = df_m_5['eu_l'].shift(24)
df_m_5['eu_Close_last_day24'] = df_m_5['eu_c'].shift(24) 
#23 days ago
df_m_5['eu_High_last_day23'] = df_m_5['eu_h'].shift(23)
df_m_5['eu_Low_last_day23'] = df_m_5['eu_l'].shift(23)
df_m_5['eu_Close_last_day23'] = df_m_5['eu_c'].shift(23) 
#22 days ago
df_m_5['eu_High_last_day22'] = df_m_5['eu_h'].shift(22)
df_m_5['eu_Low_last_day22'] = df_m_5['eu_l'].shift(22)
df_m_5['eu_Close_last_day22'] = df_m_5['eu_c'].shift(22) 
#21 day ago
df_m_5['eu_High_last_day21'] = df_m_5['eu_h'].shift(21)
df_m_5['eu_Low_last_day21'] = df_m_5['eu_l'].shift(21)
df_m_5['eu_Close_last_day21'] = df_m_5['eu_c'].shift(21)
#20 days ago
df_m_5['eu_High_last_day20'] = df_m_5['eu_h'].shift(20)
df_m_5['eu_Low_last_day20'] = df_m_5['eu_l'].shift(20)
df_m_5['eu_Close_last_day20'] = df_m_5['eu_c'].shift(20) 
#19 days ago 
df_m_5['eu_High_last_day19'] = df_m_5['eu_h'].shift(19)
df_m_5['eu_Low_last_day19'] = df_m_5['eu_l'].shift(19)
df_m_5['eu_Close_last_day19'] = df_m_5['eu_c'].shift(19)
#18 days ago
df_m_5['eu_High_last_day18'] = df_m_5['eu_h'].shift(18)
df_m_5['eu_Low_last_day18'] = df_m_5['eu_l'].shift(18)
df_m_5['eu_Close_last_day18'] = df_m_5['eu_c'].shift(18) 
#17 days ago
df_m_5['eu_High_last_day17'] = df_m_5['eu_h'].shift(17)
df_m_5['eu_Low_last_day17'] = df_m_5['eu_l'].shift(17)
df_m_5['eu_Close_last_day17'] = df_m_5['eu_c'].shift(17) 
#16 day ago
df_m_5['eu_High_last_day16'] = df_m_5['eu_h'].shift(16)
df_m_5['eu_Low_last_day16'] = df_m_5['eu_l'].shift(16)
df_m_5['eu_Close_last_day16'] = df_m_5['eu_c'].shift(16)
#15 days ago
df_m_5['eu_High_last_day15'] = df_m_5['eu_h'].shift(15)
df_m_5['eu_Low_last_day15'] = df_m_5['eu_l'].shift(15)
df_m_5['eu_Close_last_day15'] = df_m_5['eu_c'].shift(15)
#14 days ago 
df_m_5['eu_High_last_day14'] = df_m_5['eu_h'].shift(14)
df_m_5['eu_Low_last_day14'] = df_m_5['eu_l'].shift(14)
df_m_5['eu_Close_last_day14'] = df_m_5['eu_c'].shift(14) 
#13 days ago
df_m_5['eu_High_last_day13'] = df_m_5['eu_h'].shift(13)
df_m_5['eu_Low_last_day13'] = df_m_5['eu_l'].shift(13)
df_m_5['eu_Close_last_day13'] = df_m_5['eu_c'].shift(13) 
#12 days ago
df_m_5['eu_High_last_day12'] = df_m_5['eu_h'].shift(12)
df_m_5['eu_Low_last_day12'] = df_m_5['eu_l'].shift(12)
df_m_5['eu_Close_last_day12'] = df_m_5['eu_c'].shift(12) 
#11 day ago 
df_m_5['eu_High_last_day11'] = df_m_5['eu_h'].shift(11)
df_m_5['eu_Low_last_day11'] = df_m_5['eu_l'].shift(11)
df_m_5['eu_Close_last_day11'] = df_m_5['eu_c'].shift(11) 
#10 days ago
df_m_5['eu_High_last_day10'] = df_m_5['eu_h'].shift(10)
df_m_5['eu_Low_last_day10'] = df_m_5['eu_l'].shift(10)
df_m_5['eu_Close_last_day10'] = df_m_5['eu_c'].shift(10)
#9 days ago 
df_m_5['eu_High_last_day9'] = df_m_5['eu_h'].shift(9)
df_m_5['eu_Low_last_day9'] = df_m_5['eu_l'].shift(9)
df_m_5['eu_Close_last_day9'] = df_m_5['eu_c'].shift(9) 
#8 days ago
df_m_5['eu_High_last_day8'] = df_m_5['eu_h'].shift(8)
df_m_5['eu_Low_last_day8'] = df_m_5['eu_l'].shift(8)
df_m_5['eu_Close_last_day8'] = df_m_5['eu_c'].shift(8)
#7 days ago
df_m_5['eu_High_last_day7'] = df_m_5['eu_h'].shift(7)
df_m_5['eu_Low_last_day7'] = df_m_5['eu_l'].shift(7)
df_m_5['eu_Close_last_day7'] = df_m_5['eu_c'].shift(7) 
#6 day ago 
df_m_5['eu_High_last_day6'] = df_m_5['eu_h'].shift(6)
df_m_5['eu_Low_last_day6'] = df_m_5['eu_l'].shift(6)
df_m_5['eu_Close_last_day6'] = df_m_5['eu_c'].shift(6)
#5 days ago
df_m_5['eu_High_last_day5'] = df_m_5['eu_h'].shift(5)
df_m_5['eu_Low_last_day5'] = df_m_5['eu_l'].shift(5)
df_m_5['eu_Close_last_day5'] = df_m_5['eu_c'].shift(5) 
#4 days ago 
df_m_5['eu_High_last_day4'] = df_m_5['eu_h'].shift(4)
df_m_5['eu_Low_last_day4'] = df_m_5['eu_l'].shift(4)
df_m_5['eu_Close_last_day4'] = df_m_5['eu_c'].shift(4) 
#3 days ago
df_m_5['eu_High_last_day3'] = df_m_5['eu_h'].shift(3)
df_m_5['eu_Low_last_day3'] = df_m_5['eu_l'].shift(3)
df_m_5['eu_Close_last_day3'] = df_m_5['eu_c'].shift(3)
#2 days ago
df_m_5['eu_High_last_day2'] = df_m_5['eu_h'].shift(2)
df_m_5['eu_Low_last_day2'] = df_m_5['eu_l'].shift(2)
df_m_5['eu_Close_last_day2'] = df_m_5['eu_c'].shift(2) 
#1 day ago 
df_m_5['eu_High_last_day1'] = df_m_5['eu_h'].shift(1)
df_m_5['eu_Low_last_day1'] = df_m_5['eu_l'].shift(1)
df_m_5['eu_Close_last_day1'] = df_m_5['eu_c'].shift(1)     

#Target
#1 day forward 
df_m_5['eu_High_next_day1'] = df_m_5['eu_h'].shift(-1)
df_m_5['eu_Low_next_day1'] = df_m_5['eu_l'].shift(-1)
df_m_5['eu_Close_next_day1'] = df_m_5['eu_c'].shift(-1) 

#drop null and useless columns
df_m_5 = df_m_5.dropna()
df_m_5 = df_m_5.drop(['d','t','eu_o','eu_h','eu_l','eu_c','eu_v'], axis=1)

In [ ]:
df_m_5

,eu_High_last_day30,eu_Low_last_day30,eu_Close_last_day30,eu_High_last_day29,eu_Low_last_day29,eu_Close_last_day29,eu_High_last_day28,eu_Low_last_day28,eu_Close_last_day28,eu_High_last_day27,...,eu_Close_last_day3,eu_High_last_day2,eu_Low_last_day2,eu_Close_last_day2,eu_High_last_day1,eu_Low_last_day1,eu_Close_last_day1,eu_High_next_day1,eu_Low_next_day1,eu_Close_next_day1
30,108.470,107.970,108.350,108.410,107.540,107.790,108.490,107.680,108.140,108.290,...,115.530,116.280,115.460,116.220,116.700,115.720,115.970,116.270,115.580,115.990
31,108.410,107.540,107.790,108.490,107.680,108.140,108.290,106.780,107.090,107.600,...,116.220,116.700,115.720,115.970,116.420,115.520,116.090,116.800,115.580,116.610
32,108.490,107.680,108.140,108.290,106.780,107.090,107.600,106.790,107.470,107.990,...,115.970,116.420,115.520,116.090,116.270,115.580,115.990,116.750,115.900,116.070
33,108.290,106.780,107.090,107.600,106.790,107.470,107.990,107.270,107.820,108.790,...,116.090,116.270,115.580,115.990,116.800,115.580,116.610,116.520,115.960,116.070
34,107.600,106.790,107.470,107.990,107.270,107.820,108.790,107.770,108.550,108.690,...,115.990,116.800,115.580,116.610,116.750,115.900,116.070,116.570,115.900,116.450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,125.889,124.819,125.248,125.250,124.255,124.566,124.996,124.284,124.448,125.142,...,134.418,135.422,134.292,134.407,134.464,133.413,133.557,134.452,133.855,134.397
2188,125.250,124.255,124.566,124.996,124.284,124.448,125.142,124.367,125.033,125.278,...,134.407,134.464,133.413,133.557,134.368,133.423,133.890,136.179,134.350,135.348
2189,124.996,124.284,124.448,125.142,124.367,125.033,125.278,124.683,124.820,125.699,...,133.557,134.368,133.423,133.890,134.452,133.855,134.397,135.865,134.574,134.820
2190,125.142,124.367,125.033,125.278,124.683,124.820,125.699,124.758,125.452,126.455,...,133.890,134.452,133.855,134.397,136.179,134.350,135.348,135.358,134.440,134.645
2191,125.278,124.683,124.820,125.699,124.758,125.452,126.455,125.487,125.893,126.145,...,134.397,136.179,134.350,135.348,135.865,134.574,134.820,134.879,133.918,134.331

In [ ]:
extra_clone = pd.DataFrame(data=df_m_5)
print(extra_clone)

      eu_High_last_day30  eu_Low_last_day30  eu_Close_last_day30  \
30               108.470            107.970              108.350
31               108.410            107.540              107.790
32               108.490            107.680              108.140
33               108.290            106.780              107.090
34               107.600            106.790              107.470
...                  ...                ...                  ...
2187             125.889            124.819              125.248
2188             125.250            124.255              124.566
2189             124.996            124.284              124.448
2190             125.142            124.367              125.033
2191             125.278            124.683              124.820

      eu_High_last_day29  eu_Low_last_day29  eu_Close_last_day29  \
30               108.410            107.540              107.790
31               108.490            107.680              108.140
32               108.290            106.780              107.090
33               107.600            106.790              107.470
34               107.990            107.270              107.820
...                  ...                ...                  ...
2187             125.250            124.255              124.566
2188             124.996            124.284              124.448
2189             125.142            124.367              125.033
2190             125.278            124.683              124.820
2191             125.699            124.758              125.452

      eu_High_last_day28  eu_Low_last_day28  eu_Close_last_day28  \
30               108.490            107.680              108.140
31               108.290            106.780              107.090
32               107.600            106.790              107.470
33               107.990            107.270              107.820
34               108.790            107.770              108.550
...                  ...                ...                  ...
2187             124.996            124.284              124.448
2188             125.142            124.367              125.033
2189             125.278            124.683              124.820
2190             125.699            124.758              125.452
2191             126.455            125.487              125.893

      eu_High_last_day27  ...  eu_Close_last_day3  eu_High_last_day2  \
30               108.290  ...             115.530            116.280
31               107.600  ...             116.220            116.700
32               107.990  ...             115.970            116.420
33               108.790  ...             116.090            116.270
34               108.690  ...             115.990            116.800
...                  ...  ...                 ...                ...
2187             125.142  ...             134.418            135.422
2188             125.278  ...             134.407            134.464
2189             125.699  ...             133.557            134.368
2190             126.455  ...             133.890            134.452
2191             126.145  ...             134.397            136.179

      eu_Low_last_day2  eu_Close_last_day2  eu_High_last_day1  \
30             115.460             116.220            116.700
31             115.720             115.970            116.420
32             115.520             116.090            116.270
33             115.580             115.990            116.800
34             115.580             116.610            116.750
...                ...                 ...                ...
2187           134.292             134.407            134.464
2188           133.413             133.557            134.368
2189           133.423             133.890            134.452
2190           133.855             134.397            136.179
2191           134.350             135.348            135.865

      eu_Low_last_day1  eu_Close_last_day1  eu_High_next_day1  \
30             115.720             115.970            116.270
31             115.520             116.090            116.800
32             115.580             115.990            116.750
33             115.580             116.610            116.520
34             115.900             116.070            116.570
...                ...                 ...                ...
2187           133.413             133.557            134.452
2188           133.423             133.890            136.179
2189           133.855             134.397            135.865
2190           134.350             135.348            135.358
2191           134.574             134.820            134.879

      eu_Low_next_day1  eu_Close_next_day1
30             115.580             115.990
31             115.580             116.610
32             115.900             116.070
33             115.960             116.070
34             115.900             116.450
...                ...                 ...
2187           133.855             134.397
2188           134.350             135.348
2189           134.574             134.820
2190           134.440             134.645
2191           133.918             134.331

[2162 rows x 93 columns]

In [ ]:
extra_clone.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2162 entries, 30 to 2191
Data columns (total 93 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   eu_High_last_day30   2162 non-null   float64
 1   eu_Low_last_day30    2162 non-null   float64
 2   eu_Close_last_day30  2162 non-null   float64
 3   eu_High_last_day29   2162 non-null   float64
 4   eu_Low_last_day29    2162 non-null   float64
 5   eu_Close_last_day29  2162 non-null   float64
 6   eu_High_last_day28   2162 non-null   float64
 7   eu_Low_last_day28    2162 non-null   float64
 8   eu_Close_last_day28  2162 non-null   float64
 9   eu_High_last_day27   2162 non-null   float64
 10  eu_Low_last_day27    2162 non-null   float64
 11  eu_Close_last_day27  2162 non-null   float64
 12  eu_High_last_day26   2162 non-null   float64
 13  eu_Low_last_day26    2162 non-null   float64
 14  eu_Close_last_day26  2162 non-null   float64
 15  eu_High_last_day25   2162 non-null   float64
 16  eu_Low_last_day25    2162 non-null   float64
 17  eu_Close_last_day25  2162 non-null   float64
 18  eu_High_last_day24   2162 non-null   float64
 19  eu_Low_last_day24    2162 non-null   float64
 20  eu_Close_last_day24  2162 non-null   float64
 21  eu_High_last_day23   2162 non-null   float64
 22  eu_Low_last_day23    2162 non-null   float64
 23  eu_Close_last_day23  2162 non-null   float64
 24  eu_High_last_day22   2162 non-null   float64
 25  eu_Low_last_day22    2162 non-null   float64
 26  eu_Close_last_day22  2162 non-null   float64
 27  eu_High_last_day21   2162 non-null   float64
 28  eu_Low_last_day21    2162 non-null   float64
 29  eu_Close_last_day21  2162 non-null   float64
 30  eu_High_last_day20   2162 non-null   float64
 31  eu_Low_last_day20    2162 non-null   float64
 32  eu_Close_last_day20  2162 non-null   float64
 33  eu_High_last_day19   2162 non-null   float64
 34  eu_Low_last_day19    2162 non-null   float64
 35  eu_Close_last_day19  2162 non-null   float64
 36  eu_High_last_day18   2162 non-null   float64
 37  eu_Low_last_day18    2162 non-null   float64
 38  eu_Close_last_day18  2162 non-null   float64
 39  eu_High_last_day17   2162 non-null   float64
 40  eu_Low_last_day17    2162 non-null   float64
 41  eu_Close_last_day17  2162 non-null   float64
 42  eu_High_last_day16   2162 non-null   float64
 43  eu_Low_last_day16    2162 non-null   float64
 44  eu_Close_last_day16  2162 non-null   float64
 45  eu_High_last_day15   2162 non-null   float64
 46  eu_Low_last_day15    2162 non-null   float64
 47  eu_Close_last_day15  2162 non-null   float64
 48  eu_High_last_day14   2162 non-null   float64
 49  eu_Low_last_day14    2162 non-null   float64
 50  eu_Close_last_day14  2162 non-null   float64
 51  eu_High_last_day13   2162 non-null   float64
 52  eu_Low_last_day13    2162 non-null   float64
 53  eu_Close_last_day13  2162 non-null   float64
 54  eu_High_last_day12   2162 non-null   float64
 55  eu_Low_last_day12    2162 non-null   float64
 56  eu_Close_last_day12  2162 non-null   float64
 57  eu_High_last_day11   2162 non-null   float64
 58  eu_Low_last_day11    2162 non-null   float64
 59  eu_Close_last_day11  2162 non-null   float64
 60  eu_High_last_day10   2162 non-null   float64
 61  eu_Low_last_day10    2162 non-null   float64
 62  eu_Close_last_day10  2162 non-null   float64
 63  eu_High_last_day9    2162 non-null   float64
 64  eu_Low_last_day9     2162 non-null   float64
 65  eu_Close_last_day9   2162 non-null   float64
 66  eu_High_last_day8    2162 non-null   float64
 67  eu_Low_last_day8     2162 non-null   float64
 68  eu_Close_last_day8   2162 non-null   float64
 69  eu_High_last_day7    2162 non-null   float64
 70  eu_Low_last_day7     2162 non-null   float64
 71  eu_Close_last_day7   2162 non-null   float64
 72  eu_High_last_day6    2162 non-null   float64
 73  eu_Low_last_day6     2162 non-null   float64
 74  eu_Close_last_day6   2162 non-null   float64
 75  eu_High_last_day5    2162 non-null   float64
 76  eu_Low_last_day5     2162 non-null   float64
 77  eu_Close_last_day5   2162 non-null   float64
 78  eu_High_last_day4    2162 non-null   float64
 79  eu_Low_last_day4     2162 non-null   float64
 80  eu_Close_last_day4   2162 non-null   float64
 81  eu_High_last_day3    2162 non-null   float64
 82  eu_Low_last_day3     2162 non-null   float64
 83  eu_Close_last_day3   2162 non-null   float64
 84  eu_High_last_day2    2162 non-null   float64
 85  eu_Low_last_day2     2162 non-null   float64
 86  eu_Close_last_day2   2162 non-null   float64
 87  eu_High_last_day1    2162 non-null   float64
 88  eu_Low_last_day1     2162 non-null   float64
 89  eu_Close_last_day1   2162 non-null   float64
 90  eu_High_next_day1    2162 non-null   float64
 91  eu_Low_next_day1     2162 non-null   float64
 92  eu_Close_next_day1   2162 non-null   float64
dtypes: float64(93)
memory usage: 1.6 MB

In [ ]:
#extract yesterday's row to predict today's row
#check if needs to be pd.DataFrame
last_row = pd.DataFrame(data=extra_clone.iloc[-10:,np.r_[0:93]])
last_row

,eu_High_last_day30,eu_Low_last_day30,eu_Close_last_day30,eu_High_last_day29,eu_Low_last_day29,eu_Close_last_day29,eu_High_last_day28,eu_Low_last_day28,eu_Close_last_day28,eu_High_last_day27,...,eu_Close_last_day3,eu_High_last_day2,eu_Low_last_day2,eu_Close_last_day2,eu_High_last_day1,eu_Low_last_day1,eu_Close_last_day1,eu_High_next_day1,eu_Low_next_day1,eu_Close_next_day1
2182,125.050,124.428,124.825,125.651,124.356,125.383,125.658,124.739,125.060,125.644,...,132.945,133.289,132.506,132.627,132.951,132.352,132.700,134.904,132.807,134.649
2183,125.651,124.356,125.383,125.658,124.739,125.060,125.644,124.931,125.527,125.913,...,132.627,132.951,132.352,132.700,133.258,132.375,133.028,134.872,134.297,134.418
2184,125.658,124.739,125.060,125.644,124.931,125.527,125.913,125.391,125.848,125.889,...,132.700,133.258,132.375,133.028,134.904,132.807,134.649,135.422,134.292,134.407
2185,125.644,124.931,125.527,125.913,125.391,125.848,125.889,124.819,125.248,125.250,...,133.028,134.904,132.807,134.649,134.872,134.297,134.418,134.464,133.413,133.557
2186,125.913,125.391,125.848,125.889,124.819,125.248,125.250,124.255,124.566,124.996,...,134.649,134.872,134.297,134.418,135.422,134.292,134.407,134.368,133.423,133.890
2187,125.889,124.819,125.248,125.250,124.255,124.566,124.996,124.284,124.448,125.142,...,134.418,135.422,134.292,134.407,134.464,133.413,133.557,134.452,133.855,134.397
2188,125.250,124.255,124.566,124.996,124.284,124.448,125.142,124.367,125.033,125.278,...,134.407,134.464,133.413,133.557,134.368,133.423,133.890,136.179,134.350,135.348
2189,124.996,124.284,124.448,125.142,124.367,125.033,125.278,124.683,124.820,125.699,...,133.557,134.368,133.423,133.890,134.452,133.855,134.397,135.865,134.574,134.820
2190,125.142,124.367,125.033,125.278,124.683,124.820,125.699,124.758,125.452,126.455,...,133.890,134.452,133.855,134.397,136.179,134.350,135.348,135.358,134.440,134.645
2191,125.278,124.683,124.820,125.699,124.758,125.452,126.455,125.487,125.893,126.145,...,134.397,136.179,134.350,135.348,135.865,134.574,134.820,134.879,133.918,134.331

In [ ]:
df_m_5 = pd.DataFrame(data=df_m_5.tail(2000))
df_m_5

,eu_High_last_day30,eu_Low_last_day30,eu_Close_last_day30,eu_High_last_day29,eu_Low_last_day29,eu_Close_last_day29,eu_High_last_day28,eu_Low_last_day28,eu_Close_last_day28,eu_High_last_day27,...,eu_Close_last_day3,eu_High_last_day2,eu_Low_last_day2,eu_Close_last_day2,eu_High_last_day1,eu_Low_last_day1,eu_Close_last_day1,eu_High_next_day1,eu_Low_next_day1,eu_Close_next_day1
192,114.130,113.800,113.940,114.040,113.580,113.950,114.220,113.760,114.070,114.170,...,112.570,113.190,112.500,113.080,113.300,113.010,113.100,113.340,112.970,113.110
193,114.040,113.580,113.950,114.220,113.760,114.070,114.170,113.910,114.060,114.080,...,113.080,113.300,113.010,113.100,113.450,113.050,113.200,113.170,112.700,112.840
194,114.220,113.760,114.070,114.170,113.910,114.060,114.080,113.390,113.810,113.890,...,113.100,113.450,113.050,113.200,113.340,112.970,113.110,112.840,112.080,112.480
195,114.170,113.910,114.060,114.080,113.390,113.810,113.890,113.420,113.760,114.260,...,113.200,113.340,112.970,113.110,113.170,112.700,112.840,112.840,112.220,112.320
196,114.080,113.390,113.810,113.890,113.420,113.760,114.260,113.590,114.240,114.580,...,113.110,113.170,112.700,112.840,112.840,112.080,112.480,112.740,111.880,112.630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,125.889,124.819,125.248,125.250,124.255,124.566,124.996,124.284,124.448,125.142,...,134.418,135.422,134.292,134.407,134.464,133.413,133.557,134.452,133.855,134.397
2188,125.250,124.255,124.566,124.996,124.284,124.448,125.142,124.367,125.033,125.278,...,134.407,134.464,133.413,133.557,134.368,133.423,133.890,136.179,134.350,135.348
2189,124.996,124.284,124.448,125.142,124.367,125.033,125.278,124.683,124.820,125.699,...,133.557,134.368,133.423,133.890,134.452,133.855,134.397,135.865,134.574,134.820
2190,125.142,124.367,125.033,125.278,124.683,124.820,125.699,124.758,125.452,126.455,...,133.890,134.452,133.855,134.397,136.179,134.350,135.348,135.358,134.440,134.645
2191,125.278,124.683,124.820,125.699,124.758,125.452,126.455,125.487,125.893,126.145,...,134.397,136.179,134.350,135.348,135.865,134.574,134.820,134.879,133.918,134.331

In [ ]:
#create initial train and test data as pd.DF for close
#final test DF is last_row
df_m_5_train_close = pd.DataFrame(data=df_m_5.iloc[0:1980,[2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92]])


df_m_5_test_close = pd.DataFrame(data=df_m_5.iloc[1980:2001,[2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80,83,86,89,92]])
print(df_m_5_train_close )
print(df_m_5_test_close )

      eu_Close_last_day30  eu_Close_last_day29  eu_Close_last_day28  \
192               113.940              113.950              114.070
193               113.950              114.070              114.060
194               114.070              114.060              113.810
195               114.060              113.810              113.760
196               113.810              113.760              114.240
...                   ...                  ...                  ...
2167              124.442              124.615              124.882
2168              124.615              124.882              125.012
2169              124.882              125.012              125.356
2170              125.012              125.356              124.863
2171              125.356              124.863              124.940

      eu_Close_last_day27  eu_Close_last_day26  eu_Close_last_day25  \
192               114.060              113.810              113.760
193               113.810              113.760              114.240
194               113.760              114.240              114.360
195               114.240              114.360              114.480
196               114.360              114.480              114.380
...                   ...                  ...                  ...
2167              125.012              125.356              124.863
2168              125.356              124.863              124.940
2169              124.863              124.940              124.901
2170              124.940              124.901              125.179
2171              124.901              125.179              124.843

      eu_Close_last_day24  eu_Close_last_day23  eu_Close_last_day22  \
192               114.240              114.360              114.480
193               114.360              114.480              114.380
194               114.480              114.380              114.040
195               114.380              114.040              113.980
196               114.040              113.980              113.720
...                   ...                  ...                  ...
2167              124.940              124.901              125.179
2168              124.901              125.179              124.843
2169              125.179              124.843              124.860
2170              124.843              124.860              125.253
2171              124.860              125.253              124.825

      eu_Close_last_day21  ...  eu_Close_last_day9  eu_Close_last_day8  \
192               114.380  ...             112.890             112.430
193               114.040  ...             112.430             112.440
194               113.980  ...             112.440             112.760
195               113.720  ...             112.760             112.500
196               114.050  ...             112.500             112.660
...                   ...  ...                 ...                 ...
2167              124.843  ...             124.566             124.448
2168              124.860  ...             124.448             125.033
2169              125.253  ...             125.033             124.820
2170              124.825  ...             124.820             125.452
2171              125.231  ...             125.452             125.893

      eu_Close_last_day7  eu_Close_last_day6  eu_Close_last_day5  \
192              112.440             112.760             112.500
193              112.760             112.500             112.660
194              112.500             112.660             112.570
195              112.660             112.570             113.080
196              112.570             113.080             113.100
...                  ...                 ...                 ...
2167             125.033             124.820             125.452
2168             124.820             125.452             125.893
2169             125.452             125.893             125.638
2170             125.893             125.638             126.221
2171             125.638             126.221             126.564

      eu_Close_last_day4  eu_Close_last_day3  eu_Close_last_day2  \
192              112.660             112.570             113.080
193              112.570             113.080             113.100
194              113.080             113.100             113.200
195              113.100             113.200             113.110
196              113.200             113.110             112.840
...                  ...                 ...                 ...
2167             125.893             125.638             126.221
2168             125.638             126.221             126.564
2169             126.221             126.564             127.875
2170             126.564             127.875             127.948
2171             127.875             127.948             129.478

      eu_Close_last_day1  eu_Close_next_day1
192              113.100             113.110
193              113.200             112.840
194              113.110             112.480
195              112.840             112.320
196              112.480             112.630
...                  ...                 ...
2167             126.564             127.948
2168             127.875             129.478
2169             127.948             130.166
2170             129.478             131.535
2171             130.166             131.204

[1980 rows x 31 columns]
      eu_Close_last_day30  eu_Close_last_day29  eu_Close_last_day28  \
2172              124.863              124.940              124.901
2173              124.940              124.901              125.179
2174              124.901              125.179              124.843
2175              125.179              124.843              124.860
2176              124.843              124.860              125.253
2177              124.860              125.253              124.825
2178              125.253              124.825              125.231
2179              124.825              125.231              124.837
2180              125.231              124.837              124.825
2181              124.837              124.825              125.383
2182              124.825              125.383              125.060
2183              125.383              125.060              125.527
2184              125.060              125.527              125.848
2185              125.527              125.848              125.248
2186              125.848              125.248              124.566
2187              125.248              124.566              124.448
2188              124.566              124.448              125.033
2189              124.448              125.033              124.820
2190              125.033              124.820              125.452
2191              124.820              125.452              125.893

      eu_Close_last_day27  eu_Close_last_day26  eu_Close_last_day25  \
2172              125.179              124.843              124.860
2173              124.843              124.860              125.253
2174              124.860              125.253              124.825
2175              125.253              124.825              125.231
2176              124.825              125.231              124.837
2177              125.231              124.837              124.825
2178              124.837              124.825              125.383
2179              124.825              125.383              125.060
2180              125.383              125.060              125.527
2181              125.060              125.527              125.848
2182              125.527              125.848              125.248
2183              125.848              125.248              124.566
2184              125.248              124.566              124.448
2185              124.566              124.448              125.033
2186              124.448              125.033              124.820
2187              125.033              124.820              125.452
2188              124.820              125.452              125.893
2189              125.452              125.893              125.638
2190              125.893              125.638              126.221
2191              125.638              126.221              126.564

      eu_Close_last_day24  eu_Close_last_day23  eu_Close_last_day22  \
2172              125.253              124.825              125.231
2173              124.825              125.231              124.837
2174              125.231              124.837              124.825
2175              124.837              124.825              125.383
2176              124.825              125.383              125.060
2177              125.383              125.060              125.527
2178              125.060              125.527              125.848
2179              125.527              125.848              125.248
2180              125.848              125.248              124.566
2181              125.248              124.566              124.448
2182              124.566              124.448              125.033
2183              124.448              125.033              124.820
2184              125.033              124.820              125.452
2185              124.820              125.452              125.893
2186              125.452              125.893              125.638
2187              125.893              125.638              126.221
2188              125.638              126.221              126.564
2189              126.221              126.564              127.875
2190              126.564              127.875              127.948
2191              127.875              127.948              129.478

      eu_Close_last_day21  ...  eu_Close_last_day9  eu_Close_last_day8  \
2172              124.837  ...             125.893             125.638
2173              124.825  ...             125.638             126.221
2174              125.383  ...             126.221             126.564
2175              125.060  ...             126.564             127.875
2176              125.527  ...             127.875             127.948
2177              125.848  ...             127.948             129.478
2178              125.248  ...             129.478             130.166
2179              124.566  ...             130.166             131.535
2180              124.448  ...             131.535             131.204
2181              125.033  ...             131.204             132.562
2182              124.820  ...             132.562             131.991
2183              125.452  ...             131.991             131.938
2184              125.893  ...             131.938             131.878
2185              125.638  ...             131.878             132.367
2186              126.221  ...             132.367             132.497
2187              126.564  ...             132.497             132.945
2188              127.875  ...             132.945             132.627
2189              127.948  ...             132.627             132.700
2190              129.478  ...             132.700             133.028
2191              130.166  ...             133.028             134.649

      eu_Close_last_day7  eu_Close_last_day6  eu_Close_last_day5  \
2172             126.221             126.564             127.875
2173             126.564             127.875             127.948
2174             127.875             127.948             129.478
2175             127.948             129.478             130.166
2176             129.478             130.166             131.535
2177             130.166             131.535             131.204
2178             131.535             131.204             132.562
2179             131.204             132.562             131.991
2180             132.562             131.991             131.938
2181             131.991             131.938             131.878
2182             131.938             131.878             132.367
2183             131.878             132.367             132.497
2184             132.367             132.497             132.945
2185             132.497             132.945             132.627
2186             132.945             132.627             132.700
2187             132.627             132.700             133.028
2188             132.700             133.028             134.649
2189             133.028             134.649             134.418
2190             134.649             134.418             134.407
2191             134.418             134.407             133.557

      eu_Close_last_day4  eu_Close_last_day3  eu_Close_last_day2  \
2172             127.948             129.478             130.166
2173             129.478             130.166             131.535
2174             130.166             131.535             131.204
2175             131.535             131.204             132.562
2176             131.204             132.562             131.991
2177             132.562             131.991             131.938
2178             131.991             131.938             131.878
2179             131.938             131.878             132.367
2180             131.878             132.367             132.497
2181             132.367             132.497             132.945
2182             132.497             132.945             132.627
2183             132.945             132.627             132.700
2184             132.627             132.700             133.028
2185             132.700             133.028             134.649
2186             133.028             134.649             134.418
2187             134.649             134.418             134.407
2188             134.418             134.407             133.557
2189             134.407             133.557             133.890
2190             133.557             133.890             134.397
2191             133.890             134.397             135.348

      eu_Close_last_day1  eu_Close_next_day1
2172             131.535             132.562
2173             131.204             131.991
2174             132.562             131.938
2175             131.991             131.878
2176             131.938             132.367
2177             131.878             132.497
2178             132.367             132.945
2179             132.497             132.627
2180             132.945             132.700
2181             132.627             133.028
2182             132.700             134.649
2183             133.028             134.418
2184             134.649             134.407
2185             134.418             133.557
2186             134.407             133.890
2187             133.557             134.397
2188             133.890             135.348
2189             134.397             134.820
2190             135.348             134.645
2191             134.820             134.331

[20 rows x 31 columns]

In [ ]:
#create initial train and test data as pd.DF for low
#final test DF is last_row
df_m_5_train_low = pd.DataFrame(data=df_m_5.iloc[0:7980,[1,4,7,10,13,16,19,22,25,28,31,34,37,40,43,46,49,52,55,58,61,64,67,70,73,76,79,82,85,88,91]])


df_m_5_test_low = pd.DataFrame(data=df_m_5.iloc[7980:8001,[1,4,7,10,13,16,19,22,25,28,31,34,37,40,43,46,49,52,55,58,61,64,67,70,73,76,79,82,85,88,91]])
print(df_m_5_train_low )
print(df_m_5_test_low )

      eu_Low_last_day30  eu_Low_last_day29  eu_Low_last_day28  \
192             113.800            113.580            113.760
193             113.580            113.760            113.910
194             113.760            113.910            113.390
195             113.910            113.390            113.420
196             113.390            113.420            113.590
...                 ...                ...                ...
2187            124.819            124.255            124.284
2188            124.255            124.284            124.367
2189            124.284            124.367            124.683
2190            124.367            124.683            124.758
2191            124.683            124.758            125.487

      eu_Low_last_day27  eu_Low_last_day26  eu_Low_last_day25  \
192             113.910            113.390            113.420
193             113.390            113.420            113.590
194             113.420            113.590            114.200
195             113.590            114.200            114.110
196             114.200            114.110            114.250
...                 ...                ...                ...
2187            124.367            124.683            124.758
2188            124.683            124.758            125.487
2189            124.758            125.487            125.387
2190            125.487            125.387            125.520
2191            125.387            125.520            125.974

      eu_Low_last_day24  eu_Low_last_day23  eu_Low_last_day22  \
192             113.590            114.200            114.110
193             114.200            114.110            114.250
194             114.110            114.250            113.970
195             114.250            113.970            113.850
196             113.970            113.850            113.640
...                 ...                ...                ...
2187            125.487            125.387            125.520
2188            125.387            125.520            125.974
2189            125.520            125.974            126.455
2190            125.974            126.455            127.513
2191            126.455            127.513            127.910

      eu_Low_last_day21  ...  eu_Low_last_day9  eu_Low_last_day8  \
192             114.250  ...           112.630           112.400
193             113.970  ...           112.400           112.240
194             113.850  ...           112.240           112.280
195             113.640  ...           112.280           112.470
196             113.620  ...           112.470           112.430
...                 ...  ...               ...               ...
2187            125.974  ...           132.164           132.178
2188            126.455  ...           132.178           132.506
2189            127.513  ...           132.506           132.352
2190            127.910  ...           132.352           132.375
2191            129.027  ...           132.375           132.807

      eu_Low_last_day7  eu_Low_last_day6  eu_Low_last_day5  eu_Low_last_day4  \
192            112.240           112.280           112.470           112.430
193            112.280           112.470           112.430           112.490
194            112.470           112.430           112.490           112.500
195            112.430           112.490           112.500           113.010
196            112.490           112.500           113.010           113.050
...                ...               ...               ...               ...
2187           132.506           132.352           132.375           132.807
2188           132.352           132.375           132.807           134.297
2189           132.375           132.807           134.297           134.292
2190           132.807           134.297           134.292           133.413
2191           134.297           134.292           133.413           133.423

      eu_Low_last_day3  eu_Low_last_day2  eu_Low_last_day1  eu_Low_next_day1
192            112.490           112.500           113.010           112.970
193            112.500           113.010           113.050           112.700
194            113.010           113.050           112.970           112.080
195            113.050           112.970           112.700           112.220
196            112.970           112.700           112.080           111.880
...                ...               ...               ...               ...
2187           134.297           134.292           133.413           133.855
2188           134.292           133.413           133.423           134.350
2189           133.413           133.423           133.855           134.574
2190           133.423           133.855           134.350           134.440
2191           133.855           134.350           134.574           133.918

[2000 rows x 31 columns]
Empty DataFrame
Columns: [eu_Low_last_day30, eu_Low_last_day29, eu_Low_last_day28, eu_Low_last_day27, eu_Low_last_day26, eu_Low_last_day25, eu_Low_last_day24, eu_Low_last_day23, eu_Low_last_day22, eu_Low_last_day21, eu_Low_last_day20, eu_Low_last_day19, eu_Low_last_day18, eu_Low_last_day17, eu_Low_last_day16, eu_Low_last_day15, eu_Low_last_day14, eu_Low_last_day13, eu_Low_last_day12, eu_Low_last_day11, eu_Low_last_day10, eu_Low_last_day9, eu_Low_last_day8, eu_Low_last_day7, eu_Low_last_day6, eu_Low_last_day5, eu_Low_last_day4, eu_Low_last_day3, eu_Low_last_day2, eu_Low_last_day1, eu_Low_next_day1]
Index: []

[0 rows x 31 columns]

In [ ]:
#create initial train and test data as pd.DF for high
#final test DF is last_row
df_m_5_train_high = pd.DataFrame(data=df_m_5.iloc[0:7980,[0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90]])

df_m_5_test_high= pd.DataFrame(data=df_m_5.iloc[7980:8001,[0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90]])
print(df_m_5_train_high )
print(df_m_5_test_high )

      eu_High_last_day30  eu_High_last_day29  eu_High_last_day28  \
192              114.130             114.040             114.220
193              114.040             114.220             114.170
194              114.220             114.170             114.080
195              114.170             114.080             113.890
196              114.080             113.890             114.260
...                  ...                 ...                 ...
2187             125.889             125.250             124.996
2188             125.250             124.996             125.142
2189             124.996             125.142             125.278
2190             125.142             125.278             125.699
2191             125.278             125.699             126.455

      eu_High_last_day27  eu_High_last_day26  eu_High_last_day25  \
192              114.170             114.080             113.890
193              114.080             113.890             114.260
194              113.890             114.260             114.580
195              114.260             114.580             114.540
196              114.580             114.540             114.680
...                  ...                 ...                 ...
2187             125.142             125.278             125.699
2188             125.278             125.699             126.455
2189             125.699             126.455             126.145
2190             126.455             126.145             126.271
2191             126.145             126.271             126.822

      eu_High_last_day24  eu_High_last_day23  eu_High_last_day22  \
192              114.260             114.580             114.540
193              114.580             114.540             114.680
194              114.540             114.680             114.410
195              114.680             114.410             114.170
196              114.410             114.170             114.030
...                  ...                 ...                 ...
2187             126.455             126.145             126.271
2188             126.145             126.271             126.822
2189             126.271             126.822             127.886
2190             126.822             127.886             128.216
2191             127.886             128.216             129.602

      eu_High_last_day21  ...  eu_High_last_day9  eu_High_last_day8  \
192              114.680  ...            112.900            113.050
193              114.410  ...            113.050            112.560
194              114.170  ...            112.560            112.870
195              114.030  ...            112.870            112.930
196              114.160  ...            112.930            112.700
...                  ...  ...                ...                ...
2187             126.822  ...            132.748            133.077
2188             127.886  ...            133.077            133.289
2189             128.216  ...            133.289            132.951
2190             129.602  ...            132.951            133.258
2191             130.187  ...            133.258            134.904

      eu_High_last_day7  eu_High_last_day6  eu_High_last_day5  \
192             112.560            112.870            112.930
193             112.870            112.930            112.700
194             112.930            112.700            112.800
195             112.700            112.800            113.190
196             112.800            113.190            113.300
...                 ...                ...                ...
2187            133.289            132.951            133.258
2188            132.951            133.258            134.904
2189            133.258            134.904            134.872
2190            134.904            134.872            135.422
2191            134.872            135.422            134.464

      eu_High_last_day4  eu_High_last_day3  eu_High_last_day2  \
192             112.700            112.800            113.190
193             112.800            113.190            113.300
194             113.190            113.300            113.450
195             113.300            113.450            113.340
196             113.450            113.340            113.170
...                 ...                ...                ...
2187            134.904            134.872            135.422
2188            134.872            135.422            134.464
2189            135.422            134.464            134.368
2190            134.464            134.368            134.452
2191            134.368            134.452            136.179

      eu_High_last_day1  eu_High_next_day1
192             113.300            113.340
193             113.450            113.170
194             113.340            112.840
195             113.170            112.840
196             112.840            112.740
...                 ...                ...
2187            134.464            134.452
2188            134.368            136.179
2189            134.452            135.865
2190            136.179            135.358
2191            135.865            134.879

[2000 rows x 31 columns]
Empty DataFrame
Columns: [eu_High_last_day30, eu_High_last_day29, eu_High_last_day28, eu_High_last_day27, eu_High_last_day26, eu_High_last_day25, eu_High_last_day24, eu_High_last_day23, eu_High_last_day22, eu_High_last_day21, eu_High_last_day20, eu_High_last_day19, eu_High_last_day18, eu_High_last_day17, eu_High_last_day16, eu_High_last_day15, eu_High_last_day14, eu_High_last_day13, eu_High_last_day12, eu_High_last_day11, eu_High_last_day10, eu_High_last_day9, eu_High_last_day8, eu_High_last_day7, eu_High_last_day6, eu_High_last_day5, eu_High_last_day4, eu_High_last_day3, eu_High_last_day2, eu_High_last_day1, eu_High_next_day1]
Index: []

[0 rows x 31 columns]

In [ ]:
# #new column: high vs low
# df_m_5['eu_h_or_l'] = ((df_m_5.eu_h - df_m_5.eu_o) > (df_m_5.eu_o - df_m_5.eu_l)) 
# df_m_5.eu_h_or_l = df_m_5.eu_h_or_l.replace({True:1,False:0})

# #new column: close vs yesterday
# df_m_5['eu_c_vs_c'] = (df_m_5.eu_c > df_m_5.eu_o) 
# df_m_5.eu_c_vs_c = df_m_5.eu_c_vs_c.replace({True:1,False:0})

# #new column: shift tomorrow to today
# df_m_5['eu_High_next_day'] = df_m_5['eu_h'].shift(-1)
# df_m_5['eu_Low_next_day'] = df_m_5['eu_l'].shift(-1)
# df_m_5['eu_Close_next_day'] = df_m_5['eu_c'].shift(-1)
# df_m_5 = df_m_5.dropna()

In [ ]:

print(df_m_5_train_close.isna().sum())
print(df_m_5_test_close.isna().sum())

eu_Close_last_day30    0
eu_Close_last_day29    0
eu_Close_last_day28    0
eu_Close_last_day27    0
eu_Close_last_day26    0
eu_Close_last_day25    0
eu_Close_last_day24    0
eu_Close_last_day23    0
eu_Close_last_day22    0
eu_Close_last_day21    0
eu_Close_last_day20    0
eu_Close_last_day19    0
eu_Close_last_day18    0
eu_Close_last_day17    0
eu_Close_last_day16    0
eu_Close_last_day15    0
eu_Close_last_day14    0
eu_Close_last_day13    0
eu_Close_last_day12    0
eu_Close_last_day11    0
eu_Close_last_day10    0
eu_Close_last_day9     0
eu_Close_last_day8     0
eu_Close_last_day7     0
eu_Close_last_day6     0
eu_Close_last_day5     0
eu_Close_last_day4     0
eu_Close_last_day3     0
eu_Close_last_day2     0
eu_Close_last_day1     0
eu_Close_next_day1     0
dtype: int64
eu_Close_last_day30    0
eu_Close_last_day29    0
eu_Close_last_day28    0
eu_Close_last_day27    0
eu_Close_last_day26    0
eu_Close_last_day25    0
eu_Close_last_day24    0
eu_Close_last_day23    0
eu_Close_last_day22    0
eu_Close_last_day21    0
eu_Close_last_day20    0
eu_Close_last_day19    0
eu_Close_last_day18    0
eu_Close_last_day17    0
eu_Close_last_day16    0
eu_Close_last_day15    0
eu_Close_last_day14    0
eu_Close_last_day13    0
eu_Close_last_day12    0
eu_Close_last_day11    0
eu_Close_last_day10    0
eu_Close_last_day9     0
eu_Close_last_day8     0
eu_Close_last_day7     0
eu_Close_last_day6     0
eu_Close_last_day5     0
eu_Close_last_day4     0
eu_Close_last_day3     0
eu_Close_last_day2     0
eu_Close_last_day1     0
eu_Close_next_day1     0
dtype: int64

In [ ]:
print(df_m_5_train_close.info())
print(df_m_5_test_close.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1980 entries, 192 to 2171
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   eu_Close_last_day30  1980 non-null   float64
 1   eu_Close_last_day29  1980 non-null   float64
 2   eu_Close_last_day28  1980 non-null   float64
 3   eu_Close_last_day27  1980 non-null   float64
 4   eu_Close_last_day26  1980 non-null   float64
 5   eu_Close_last_day25  1980 non-null   float64
 6   eu_Close_last_day24  1980 non-null   float64
 7   eu_Close_last_day23  1980 non-null   float64
 8   eu_Close_last_day22  1980 non-null   float64
 9   eu_Close_last_day21  1980 non-null   float64
 10  eu_Close_last_day20  1980 non-null   float64
 11  eu_Close_last_day19  1980 non-null   float64
 12  eu_Close_last_day18  1980 non-null   float64
 13  eu_Close_last_day17  1980 non-null   float64
 14  eu_Close_last_day16  1980 non-null   float64
 15  eu_Close_last_day15  1980 non-null   float64
 16  eu_Close_last_day14  1980 non-null   float64
 17  eu_Close_last_day13  1980 non-null   float64
 18  eu_Close_last_day12  1980 non-null   float64
 19  eu_Close_last_day11  1980 non-null   float64
 20  eu_Close_last_day10  1980 non-null   float64
 21  eu_Close_last_day9   1980 non-null   float64
 22  eu_Close_last_day8   1980 non-null   float64
 23  eu_Close_last_day7   1980 non-null   float64
 24  eu_Close_last_day6   1980 non-null   float64
 25  eu_Close_last_day5   1980 non-null   float64
 26  eu_Close_last_day4   1980 non-null   float64
 27  eu_Close_last_day3   1980 non-null   float64
 28  eu_Close_last_day2   1980 non-null   float64
 29  eu_Close_last_day1   1980 non-null   float64
 30  eu_Close_next_day1   1980 non-null   float64
dtypes: float64(31)
memory usage: 495.0 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 2172 to 2191
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   eu_Close_last_day30  20 non-null     float64
 1   eu_Close_last_day29  20 non-null     float64
 2   eu_Close_last_day28  20 non-null     float64
 3   eu_Close_last_day27  20 non-null     float64
 4   eu_Close_last_day26  20 non-null     float64
 5   eu_Close_last_day25  20 non-null     float64
 6   eu_Close_last_day24  20 non-null     float64
 7   eu_Close_last_day23  20 non-null     float64
 8   eu_Close_last_day22  20 non-null     float64
 9   eu_Close_last_day21  20 non-null     float64
 10  eu_Close_last_day20  20 non-null     float64
 11  eu_Close_last_day19  20 non-null     float64
 12  eu_Close_last_day18  20 non-null     float64
 13  eu_Close_last_day17  20 non-null     float64
 14  eu_Close_last_day16  20 non-null     float64
 15  eu_Close_last_day15  20 non-null     float64
 16  eu_Close_last_day14  20 non-null     float64
 17  eu_Close_last_day13  20 non-null     float64
 18  eu_Close_last_day12  20 non-null     float64
 19  eu_Close_last_day11  20 non-null     float64
 20  eu_Close_last_day10  20 non-null     float64
 21  eu_Close_last_day9   20 non-null     float64
 22  eu_Close_last_day8   20 non-null     float64
 23  eu_Close_last_day7   20 non-null     float64
 24  eu_Close_last_day6   20 non-null     float64
 25  eu_Close_last_day5   20 non-null     float64
 26  eu_Close_last_day4   20 non-null     float64
 27  eu_Close_last_day3   20 non-null     float64
 28  eu_Close_last_day2   20 non-null     float64
 29  eu_Close_last_day1   20 non-null     float64
 30  eu_Close_next_day1   20 non-null     float64
dtypes: float64(31)
memory usage: 5.0 KB
None

In [ ]:
print(df_m_5_train_high.isna().sum())
print(df_m_5_test_high.isna().sum())
print(df_m_5_train_high.info())
print(df_m_5_test_high.info())

eu_High_last_day30    0
eu_High_last_day29    0
eu_High_last_day28    0
eu_High_last_day27    0
eu_High_last_day26    0
eu_High_last_day25    0
eu_High_last_day24    0
eu_High_last_day23    0
eu_High_last_day22    0
eu_High_last_day21    0
eu_High_last_day20    0
eu_High_last_day19    0
eu_High_last_day18    0
eu_High_last_day17    0
eu_High_last_day16    0
eu_High_last_day15    0
eu_High_last_day14    0
eu_High_last_day13    0
eu_High_last_day12    0
eu_High_last_day11    0
eu_High_last_day10    0
eu_High_last_day9     0
eu_High_last_day8     0
eu_High_last_day7     0
eu_High_last_day6     0
eu_High_last_day5     0
eu_High_last_day4     0
eu_High_last_day3     0
eu_High_last_day2     0
eu_High_last_day1     0
eu_High_next_day1     0
dtype: int64
eu_High_last_day30    0.0
eu_High_last_day29    0.0
eu_High_last_day28    0.0
eu_High_last_day27    0.0
eu_High_last_day26    0.0
eu_High_last_day25    0.0
eu_High_last_day24    0.0
eu_High_last_day23    0.0
eu_High_last_day22    0.0
eu_High_last_day21    0.0
eu_High_last_day20    0.0
eu_High_last_day19    0.0
eu_High_last_day18    0.0
eu_High_last_day17    0.0
eu_High_last_day16    0.0
eu_High_last_day15    0.0
eu_High_last_day14    0.0
eu_High_last_day13    0.0
eu_High_last_day12    0.0
eu_High_last_day11    0.0
eu_High_last_day10    0.0
eu_High_last_day9     0.0
eu_High_last_day8     0.0
eu_High_last_day7     0.0
eu_High_last_day6     0.0
eu_High_last_day5     0.0
eu_High_last_day4     0.0
eu_High_last_day3     0.0
eu_High_last_day2     0.0
eu_High_last_day1     0.0
eu_High_next_day1     0.0
dtype: float64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 192 to 2191
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   eu_High_last_day30  2000 non-null   float64
 1   eu_High_last_day29  2000 non-null   float64
 2   eu_High_last_day28  2000 non-null   float64
 3   eu_High_last_day27  2000 non-null   float64
 4   eu_High_last_day26  2000 non-null   float64
 5   eu_High_last_day25  2000 non-null   float64
 6   eu_High_last_day24  2000 non-null   float64
 7   eu_High_last_day23  2000 non-null   float64
 8   eu_High_last_day22  2000 non-null   float64
 9   eu_High_last_day21  2000 non-null   float64
 10  eu_High_last_day20  2000 non-null   float64
 11  eu_High_last_day19  2000 non-null   float64
 12  eu_High_last_day18  2000 non-null   float64
 13  eu_High_last_day17  2000 non-null   float64
 14  eu_High_last_day16  2000 non-null   float64
 15  eu_High_last_day15  2000 non-null   float64
 16  eu_High_last_day14  2000 non-null   float64
 17  eu_High_last_day13  2000 non-null   float64
 18  eu_High_last_day12  2000 non-null   float64
 19  eu_High_last_day11  2000 non-null   float64
 20  eu_High_last_day10  2000 non-null   float64
 21  eu_High_last_day9   2000 non-null   float64
 22  eu_High_last_day8   2000 non-null   float64
 23  eu_High_last_day7   2000 non-null   float64
 24  eu_High_last_day6   2000 non-null   float64
 25  eu_High_last_day5   2000 non-null   float64
 26  eu_High_last_day4   2000 non-null   float64
 27  eu_High_last_day3   2000 non-null   float64
 28  eu_High_last_day2   2000 non-null   float64
 29  eu_High_last_day1   2000 non-null   float64
 30  eu_High_next_day1   2000 non-null   float64
dtypes: float64(31)
memory usage: 500.0 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   eu_High_last_day30  0 non-null      float64
 1   eu_High_last_day29  0 non-null      float64
 2   eu_High_last_day28  0 non-null      float64
 3   eu_High_last_day27  0 non-null      float64
 4   eu_High_last_day26  0 non-null      float64
 5   eu_High_last_day25  0 non-null      float64
 6   eu_High_last_day24  0 non-null      float64
 7   eu_High_last_day23  0 non-null      float64
 8   eu_High_last_day22  0 non-null      float64
 9   eu_High_last_day21  0 non-null      float64
 10  eu_High_last_day20  0 non-null      float64
 11  eu_High_last_day19  0 non-null      float64
 12  eu_High_last_day18  0 non-null      float64
 13  eu_High_last_day17  0 non-null      float64
 14  eu_High_last_day16  0 non-null      float64
 15  eu_High_last_day15  0 non-null      float64
 16  eu_High_last_day14  0 non-null      float64
 17  eu_High_last_day13  0 non-null      float64
 18  eu_High_last_day12  0 non-null      float64
 19  eu_High_last_day11  0 non-null      float64
 20  eu_High_last_day10  0 non-null      float64
 21  eu_High_last_day9   0 non-null      float64
 22  eu_High_last_day8   0 non-null      float64
 23  eu_High_last_day7   0 non-null      float64
 24  eu_High_last_day6   0 non-null      float64
 25  eu_High_last_day5   0 non-null      float64
 26  eu_High_last_day4   0 non-null      float64
 27  eu_High_last_day3   0 non-null      float64
 28  eu_High_last_day2   0 non-null      float64
 29  eu_High_last_day1   0 non-null      float64
 30  eu_High_next_day1   0 non-null      float64
dtypes: float64(31)
memory usage: 0.0 bytes
None

In [ ]:
print(df_m_5_train_low.isna().sum())
print(df_m_5_test_low.isna().sum())
print(df_m_5_train_low.info())
print(df_m_5_test_low.info())

eu_Low_last_day30    0
eu_Low_last_day29    0
eu_Low_last_day28    0
eu_Low_last_day27    0
eu_Low_last_day26    0
eu_Low_last_day25    0
eu_Low_last_day24    0
eu_Low_last_day23    0
eu_Low_last_day22    0
eu_Low_last_day21    0
eu_Low_last_day20    0
eu_Low_last_day19    0
eu_Low_last_day18    0
eu_Low_last_day17    0
eu_Low_last_day16    0
eu_Low_last_day15    0
eu_Low_last_day14    0
eu_Low_last_day13    0
eu_Low_last_day12    0
eu_Low_last_day11    0
eu_Low_last_day10    0
eu_Low_last_day9     0
eu_Low_last_day8     0
eu_Low_last_day7     0
eu_Low_last_day6     0
eu_Low_last_day5     0
eu_Low_last_day4     0
eu_Low_last_day3     0
eu_Low_last_day2     0
eu_Low_last_day1     0
eu_Low_next_day1     0
dtype: int64
eu_Low_last_day30    0.0
eu_Low_last_day29    0.0
eu_Low_last_day28    0.0
eu_Low_last_day27    0.0
eu_Low_last_day26    0.0
eu_Low_last_day25    0.0
eu_Low_last_day24    0.0
eu_Low_last_day23    0.0
eu_Low_last_day22    0.0
eu_Low_last_day21    0.0
eu_Low_last_day20    0.0
eu_Low_last_day19    0.0
eu_Low_last_day18    0.0
eu_Low_last_day17    0.0
eu_Low_last_day16    0.0
eu_Low_last_day15    0.0
eu_Low_last_day14    0.0
eu_Low_last_day13    0.0
eu_Low_last_day12    0.0
eu_Low_last_day11    0.0
eu_Low_last_day10    0.0
eu_Low_last_day9     0.0
eu_Low_last_day8     0.0
eu_Low_last_day7     0.0
eu_Low_last_day6     0.0
eu_Low_last_day5     0.0
eu_Low_last_day4     0.0
eu_Low_last_day3     0.0
eu_Low_last_day2     0.0
eu_Low_last_day1     0.0
eu_Low_next_day1     0.0
dtype: float64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000 entries, 192 to 2191
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eu_Low_last_day30  2000 non-null   float64
 1   eu_Low_last_day29  2000 non-null   float64
 2   eu_Low_last_day28  2000 non-null   float64
 3   eu_Low_last_day27  2000 non-null   float64
 4   eu_Low_last_day26  2000 non-null   float64
 5   eu_Low_last_day25  2000 non-null   float64
 6   eu_Low_last_day24  2000 non-null   float64
 7   eu_Low_last_day23  2000 non-null   float64
 8   eu_Low_last_day22  2000 non-null   float64
 9   eu_Low_last_day21  2000 non-null   float64
 10  eu_Low_last_day20  2000 non-null   float64
 11  eu_Low_last_day19  2000 non-null   float64
 12  eu_Low_last_day18  2000 non-null   float64
 13  eu_Low_last_day17  2000 non-null   float64
 14  eu_Low_last_day16  2000 non-null   float64
 15  eu_Low_last_day15  2000 non-null   float64
 16  eu_Low_last_day14  2000 non-null   float64
 17  eu_Low_last_day13  2000 non-null   float64
 18  eu_Low_last_day12  2000 non-null   float64
 19  eu_Low_last_day11  2000 non-null   float64
 20  eu_Low_last_day10  2000 non-null   float64
 21  eu_Low_last_day9   2000 non-null   float64
 22  eu_Low_last_day8   2000 non-null   float64
 23  eu_Low_last_day7   2000 non-null   float64
 24  eu_Low_last_day6   2000 non-null   float64
 25  eu_Low_last_day5   2000 non-null   float64
 26  eu_Low_last_day4   2000 non-null   float64
 27  eu_Low_last_day3   2000 non-null   float64
 28  eu_Low_last_day2   2000 non-null   float64
 29  eu_Low_last_day1   2000 non-null   float64
 30  eu_Low_next_day1   2000 non-null   float64
dtypes: float64(31)
memory usage: 500.0 KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   eu_Low_last_day30  0 non-null      float64
 1   eu_Low_last_day29  0 non-null      float64
 2   eu_Low_last_day28  0 non-null      float64
 3   eu_Low_last_day27  0 non-null      float64
 4   eu_Low_last_day26  0 non-null      float64
 5   eu_Low_last_day25  0 non-null      float64
 6   eu_Low_last_day24  0 non-null      float64
 7   eu_Low_last_day23  0 non-null      float64
 8   eu_Low_last_day22  0 non-null      float64
 9   eu_Low_last_day21  0 non-null      float64
 10  eu_Low_last_day20  0 non-null      float64
 11  eu_Low_last_day19  0 non-null      float64
 12  eu_Low_last_day18  0 non-null      float64
 13  eu_Low_last_day17  0 non-null      float64
 14  eu_Low_last_day16  0 non-null      float64
 15  eu_Low_last_day15  0 non-null      float64
 16  eu_Low_last_day14  0 non-null      float64
 17  eu_Low_last_day13  0 non-null      float64
 18  eu_Low_last_day12  0 non-null      float64
 19  eu_Low_last_day11  0 non-null      float64
 20  eu_Low_last_day10  0 non-null      float64
 21  eu_Low_last_day9   0 non-null      float64
 22  eu_Low_last_day8   0 non-null      float64
 23  eu_Low_last_day7   0 non-null      float64
 24  eu_Low_last_day6   0 non-null      float64
 25  eu_Low_last_day5   0 non-null      float64
 26  eu_Low_last_day4   0 non-null      float64
 27  eu_Low_last_day3   0 non-null      float64
 28  eu_Low_last_day2   0 non-null      float64
 29  eu_Low_last_day1   0 non-null      float64
 30  eu_Low_next_day1   0 non-null      float64
dtypes: float64(31)
memory usage: 0.0 bytes
None

In [ ]:
train_close = df_m_5_train_close
train_close=train_close.sample(n=2000, replace=True)
train_close.head()

,eu_Close_last_day30,eu_Close_last_day29,eu_Close_last_day28,eu_Close_last_day27,eu_Close_last_day26,eu_Close_last_day25,eu_Close_last_day24,eu_Close_last_day23,eu_Close_last_day22,eu_Close_last_day21,...,eu_Close_last_day9,eu_Close_last_day8,eu_Close_last_day7,eu_Close_last_day6,eu_Close_last_day5,eu_Close_last_day4,eu_Close_last_day3,eu_Close_last_day2,eu_Close_last_day1,eu_Close_next_day1
876,113.475,113.507,112.527,112.718,112.546,112.095,111.860,111.232,111.642,112.074,...,113.692,112.870,112.659,112.362,112.100,111.660,112.246,112.243,111.935,111.731
751,104.235,104.019,103.862,103.830,103.942,104.168,104.603,105.117,105.309,105.584,...,103.874,102.914,103.969,104.037,103.494,103.417,103.653,104.530,104.372,105.069
1845,115.317,115.003,114.973,114.855,114.613,114.585,114.294,113.925,113.917,113.961,...,117.160,117.172,117.622,116.907,117.278,117.013,116.845,116.585,116.960,116.487
1408,111.388,111.169,110.275,110.277,109.999,110.465,110.700,111.263,111.243,111.261,...,111.666,111.609,111.690,111.550,111.094,110.691,111.289,111.694,111.564,110.809
1027,114.417,115.491,115.974,115.867,115.679,115.850,115.465,115.573,115.811,116.029,...,114.714,115.004,114.664,115.030,115.233,115.308,115.153,114.915,114.916,113.977

In [ ]:
#predict close
label_c = 'eu_Close_next_day1' 
print("Summary of class variable: \n", train_close[label_c].describe())

Summary of class variable:
 count    2000.000000
mean      115.679064
std         6.090572
min       102.217000
25%       111.481500
50%       114.251000
75%       119.716000
max       133.930000
Name: eu_Close_next_day1, dtype: float64

In [ ]:
train_close = pd.DataFrame(train_close.drop_duplicates(keep=False))

In [ ]:
train_close.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 738 entries, 876 to 363
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   eu_Close_last_day30  738 non-null    float64
 1   eu_Close_last_day29  738 non-null    float64
 2   eu_Close_last_day28  738 non-null    float64
 3   eu_Close_last_day27  738 non-null    float64
 4   eu_Close_last_day26  738 non-null    float64
 5   eu_Close_last_day25  738 non-null    float64
 6   eu_Close_last_day24  738 non-null    float64
 7   eu_Close_last_day23  738 non-null    float64
 8   eu_Close_last_day22  738 non-null    float64
 9   eu_Close_last_day21  738 non-null    float64
 10  eu_Close_last_day20  738 non-null    float64
 11  eu_Close_last_day19  738 non-null    float64
 12  eu_Close_last_day18  738 non-null    float64
 13  eu_Close_last_day17  738 non-null    float64
 14  eu_Close_last_day16  738 non-null    float64
 15  eu_Close_last_day15  738 non-null    float64
 16  eu_Close_last_day14  738 non-null    float64
 17  eu_Close_last_day13  738 non-null    float64
 18  eu_Close_last_day12  738 non-null    float64
 19  eu_Close_last_day11  738 non-null    float64
 20  eu_Close_last_day10  738 non-null    float64
 21  eu_Close_last_day9   738 non-null    float64
 22  eu_Close_last_day8   738 non-null    float64
 23  eu_Close_last_day7   738 non-null    float64
 24  eu_Close_last_day6   738 non-null    float64
 25  eu_Close_last_day5   738 non-null    float64
 26  eu_Close_last_day4   738 non-null    float64
 27  eu_Close_last_day3   738 non-null    float64
 28  eu_Close_last_day2   738 non-null    float64
 29  eu_Close_last_day1   738 non-null    float64
 30  eu_Close_next_day1   738 non-null    float64
dtypes: float64(31)
memory usage: 184.5 KB

In [ ]:
#predict close
save_path='agModels-predictClose'
predictor = TabularPredictor(label=label_c, path=save_path)
predictor.fit(train_close, hyperparameters={ 'RF':{} } , presets='best_quality')
#predictor.fit(train_close, excluded_model_types=['CatBoost'], presets='optimize_for_deployment') #is slower

Warning: path already exists! This predictor may overwrite an existing predictor! path="agModels-predictClose"
Presets specified: ['best_quality']
Beginning AutoGluon training ...
AutoGluon will save models to "agModels-predictClose/"
AutoGluon Version:  0.4.0
Python Version:     3.7.13
Operating System:   Linux
Train Data Rows:    738
Train Data Columns: 30
Label Column: eu_Close_next_day1
Preprocessing data ...
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (133.93, 102.217, 115.55447, 6.08187)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11957.42 MB
	Train Data (Original)  Memory Usage: 0.18 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 30 | ['eu_Close_last_day30', 'eu_Close_last_day29', 'eu_Close_last_day28', 'eu_Close_last_day27', 'eu_Close_last_day26', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 30 | ['eu_Close_last_day30', 'eu_Close_last_day29', 'eu_Close_last_day28', 'eu_Close_last_day27', 'eu_Close_last_day26', ...]
	0.1s = Fit runtime
	30 features in original data used to generate 30 features in processed data.
	Train Data (Processed) Memory Usage: 0.18 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.17s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	To change this, specify the eval_metric parameter of Predictor()
Fitting 1 L1 models ...
Fitting model: RandomForest_BAG_L1 ...
	-0.8779	 = Validation score   (root_mean_squared_error)
	2.96s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	-0.8779	 = Validation score   (root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 3.4s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("agModels-predictClose/")

In [ ]:
#contrast leaderboard result of train and test data
predictor.leaderboard(train_close, silent=True)

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,RandomForest_BAG_L1,-0.322165,-0.877871,0.147599,0.138582,2.964798,0.147599,0.138582,2.964798,1,True,1
1,WeightedEnsemble_L2,-0.322165,-0.877871,0.149922,0.139096,2.968610,0.002324,0.000514,0.003811,2,True,2

In [ ]:
#predict close
test_close = TabularDataset(df_m_5_test_close)
y_test = test_close[label_c]
test_close_nolab = test_close.drop(columns=[label_c])
test_close_nolab.tail()

,eu_Close_last_day30,eu_Close_last_day29,eu_Close_last_day28,eu_Close_last_day27,eu_Close_last_day26,eu_Close_last_day25,eu_Close_last_day24,eu_Close_last_day23,eu_Close_last_day22,eu_Close_last_day21,...,eu_Close_last_day10,eu_Close_last_day9,eu_Close_last_day8,eu_Close_last_day7,eu_Close_last_day6,eu_Close_last_day5,eu_Close_last_day4,eu_Close_last_day3,eu_Close_last_day2,eu_Close_last_day1
2187,125.248,124.566,124.448,125.033,124.820,125.452,125.893,125.638,126.221,126.564,...,132.367,132.497,132.945,132.627,132.700,133.028,134.649,134.418,134.407,133.557
2188,124.566,124.448,125.033,124.820,125.452,125.893,125.638,126.221,126.564,127.875,...,132.497,132.945,132.627,132.700,133.028,134.649,134.418,134.407,133.557,133.890
2189,124.448,125.033,124.820,125.452,125.893,125.638,126.221,126.564,127.875,127.948,...,132.945,132.627,132.700,133.028,134.649,134.418,134.407,133.557,133.890,134.397
2190,125.033,124.820,125.452,125.893,125.638,126.221,126.564,127.875,127.948,129.478,...,132.627,132.700,133.028,134.649,134.418,134.407,133.557,133.890,134.397,135.348
2191,124.820,125.452,125.893,125.638,126.221,126.564,127.875,127.948,129.478,130.166,...,132.700,133.028,134.649,134.418,134.407,133.557,133.890,134.397,135.348,134.820

In [ ]:
#predict eu_Close_next_day1
predictor = TabularPredictor.load(save_path)
y_pred = predictor.predict(test_close_nolab)
print("Predictions: \n", y_pred)
perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

Evaluation: root_mean_squared_error on test data: -1.8221034913479033
	Note: Scores are always higher_is_better. This metric score can be multiplied by -1 to get the metric value.
Evaluations on test data:
{
    "root_mean_squared_error": -1.8221034913479033,
    "mean_squared_error": -3.320061133182219,
    "mean_absolute_error": -1.5927973327636706,
    "r2": -1.8250538247889496,
    "pearsonr": 0.8833919188075477,
    "median_absolute_error": -1.5043835449218648
}

Predictions:
 2172    131.549713
2173    131.555984
2174    131.598724
2175    131.684738
2176    131.584793
2177    131.678757
2178    131.680420
2179    131.652069
2180    131.859512
2181    131.726517
2182    131.882660
2183    132.170273
2184    132.070023
2185    131.849716
2186    131.880203
2187    131.988846
2188    132.049622
2189    132.216248
2190    132.266861
2191    132.193375
Name: eu_Close_next_day1, dtype: float32

In [ ]:
#predict high
train_high = df_m_5_train_high
train_high=train_high.sample(n=7900, replace=True)
train_high.head()

,eu_High_last_day30,eu_High_last_day29,eu_High_last_day28,eu_High_last_day27,eu_High_last_day26,eu_High_last_day25,eu_High_last_day24,eu_High_last_day23,eu_High_last_day22,eu_High_last_day21,...,eu_High_last_day9,eu_High_last_day8,eu_High_last_day7,eu_High_last_day6,eu_High_last_day5,eu_High_last_day4,eu_High_last_day3,eu_High_last_day2,eu_High_last_day1,eu_High_next_day1
1006,114.181,114.253,113.841,113.348,113.540,113.329,113.538,114.420,114.648,115.081,...,114.749,115.939,116.202,116.468,116.104,115.956,115.952,115.860,115.915,116.193
300,123.300,124.150,123.460,122.490,122.560,122.620,122.470,123.170,123.120,123.080,...,122.180,121.850,122.240,122.310,122.350,122.210,122.390,121.960,121.030,119.950
2056,120.311,120.418,120.129,120.354,120.021,119.839,120.092,119.730,119.649,119.270,...,119.622,120.262,120.261,120.248,120.376,121.104,122.340,122.324,122.716,123.877
613,118.441,116.626,116.249,116.355,116.297,115.609,115.138,114.146,113.995,113.265,...,115.514,115.962,115.935,115.642,115.387,115.451,115.403,115.468,115.726,115.709
824,113.151,113.011,113.787,113.408,113.293,113.206,113.332,114.194,114.092,114.908,...,115.144,115.009,114.949,115.178,115.408,114.578,114.313,113.874,114.100,113.324

In [ ]:
#predict high
label_h = 'eu_High_next_day1' 
print("Summary of class variable: \n", train_high[label_h].describe())

Summary of class variable:
 count    7900.000000
mean      116.275564
std         6.368088
min       103.205000
25%       111.888000
50%       114.674000
75%       120.248000
max       149.280000
Name: eu_High_next_day1, dtype: float64

In [ ]:
#predict high
save_path='agModels-predictHigh'
predictor = TabularPredictor(label=label_h, path=save_path).fit(train_high,hyperparameters={ 'NN':{} } , presets='high_quality_fast_inference_only_refit')#, presets='best_quality')
#.fit(presets='best_quality) is slower

Warning: path already exists! This predictor may overwrite an existing predictor! path="agModels-predictHigh"
Preset alias specified: 'high_quality_fast_inference_only_refit' maps to 'high_quality'.
Presets specified: ['high_quality_fast_inference_only_refit']

AssertionError: ignored

In [ ]:
#contrast leaderboard result of train and test data
predictor.leaderboard(train_high, silent=True)

In [ ]:
#predict high
test_high = TabularDataset(df_m_5_test_high)
y_test = test_high[label_h]
test_high_nolab = test_high.drop(columns=[label_h])
test_high_nolab.tail()

In [ ]:
#first run to predict eu_High_next_day1
predictor = TabularPredictor.load(save_path)
y_pred = predictor.predict(test_high_nolab)
print("Predictions: \n", y_pred) #try print more rows
perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

In [ ]:
#predict low
train_low = df_m_5_train_low
train_low=train_low.sample(n=7900, replace=True)
train_low.head()

In [ ]:
#predict low
label_l = 'eu_Low_next_day1' 
print("Summary of class variable: \n", train_low[label_l].describe())

In [ ]:
#predict low
save_path='agModels-predictLow'
predictor = TabularPredictor(label=label_l, path=save_path).fit(train_low,hyperparameters={ 'NN':{} } , presets='high_quality_fast_inference_only_refit')#, presets='best_quality')
#.fit(presets='best_quality) is slower

In [ ]:
#contrast leaderboard result of train and test data
predictor.leaderboard(train_low, silent=True)

In [ ]:
#predict low
test_low = TabularDataset(df_m_5_test_low)
y_test = test_low[label_l]
test_low_nolab = test_low.drop(columns=[label_l])
test_low_nolab.tail()

In [ ]:
#predict eu_Low_next_day1
predictor = TabularPredictor.load(save_path)
y_pred = predictor.predict(test_low_nolab)
print("Predictions: \n", y_pred)
perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

In [ ]:
# clears the model after a run so you can contrast new runs.
# predictor.unpersist_models('ag_predict_interval')
# predictor.save_space()
# predictor.delete_models(models_to_keep='best', dry_run=False)
%rm -rf AutogluonModels, ag_predict_interval
!ls