<a href="https://colab.research.google.com/github/gomlfx/ApiaryFund/blob/master/AutoGluonForecast_1_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [817]:
#License: GPL 
#Creator: Mike Smith https://github.com/gomlfx

In [818]:
 ##comment this out after installed
 #!pip install autogluon
 #!pip install --upgrade mxnet

In [819]:
#designed for Jupyter/kaggle/colab
import pandas as pd
import numpy as np
#import matplotlib for plotting 
import matplotlib.pyplot as plt
%matplotlib inline
#import normalization
from sklearn import preprocessing

#autogluon
from autogluon.tabular import TabularDataset, TabularPredictor

In [820]:
#metatrader5 file format
df=pd.read_csv('/content/EURUSD_M1_202101040001_202203112354.csv')

In [821]:
print(df.head())
print(df.tail())
df.info()

  <DATE>\t<TIME>\t<OPEN>\t<HIGH>\t<LOW>\t<CLOSE>\t<TICKVOL>\t<VOL>\t<SPREAD>
0  2021.01.04\t00:01:00\t1.22395\t1.22395\t1.2239...
1  2021.01.04\t00:02:00\t1.22393\t1.22396\t1.2237...
2  2021.01.04\t00:03:00\t1.22374\t1.22374\t1.2236...
3  2021.01.04\t00:04:00\t1.22374\t1.22374\t1.2228...
4  2021.01.04\t00:05:00\t1.22318\t1.22337\t1.2231...
       <DATE>\t<TIME>\t<OPEN>\t<HIGH>\t<LOW>\t<CLOSE>\t<TICKVOL>\t<VOL>\t<SPREAD>
445067  2022.03.11\t23:50:00\t1.09118\t1.09140\t1.0911...
445068  2022.03.11\t23:51:00\t1.09132\t1.09142\t1.0913...
445069  2022.03.11\t23:52:00\t1.09133\t1.09143\t1.0913...
445070  2022.03.11\t23:53:00\t1.09138\t1.09147\t1.0913...
445071  2022.03.11\t23:54:00\t1.09127\t1.09139\t1.0912...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445072 entries, 0 to 445071
Data columns (total 1 columns):
 #   Column                                                              Non-Null Count   Dtype
---  ------                                                              --------------   -----
 0   <DATE>	<TIME>	<OPEN>	<HIGH>	<LOW>	<CLOSE>	<TICKVOL>	<VOL>	<SPREAD>  445072 non-null  object
dtypes: object(1)
memory usage: 3.4+ MB

In [822]:
df.columns=['header']

In [823]:
df = df.header.str.split('\t', expand=True)

In [824]:
df

                 0         1        2        3        4        5   6  7   8
0       2021.01.04  00:01:00  1.22395  1.22395  1.22395  1.22395   1  0  60
1       2021.01.04  00:02:00  1.22393  1.22396  1.22373  1.22373   4  0  38
2       2021.01.04  00:03:00  1.22374  1.22374  1.22366  1.22373   4  0  30
3       2021.01.04  00:04:00  1.22374  1.22374  1.22280  1.22298   9  0  32
4       2021.01.04  00:05:00  1.22318  1.22337  1.22318  1.22330  19  0  28
...            ...       ...      ...      ...      ...      ...  .. ..  ..
445067  2022.03.11  23:50:00  1.09118  1.09140  1.09118  1.09132  38  0  14
445068  2022.03.11  23:51:00  1.09132  1.09142  1.09130  1.09133  27  0  15
445069  2022.03.11  23:52:00  1.09133  1.09143  1.09132  1.09137  15  0  15
445070  2022.03.11  23:53:00  1.09138  1.09147  1.09131  1.09131  27  0  15
445071  2022.03.11  23:54:00  1.09127  1.09139  1.09125  1.09137  12  0  15

[445072 rows x 9 columns]

In [825]:
#choose range of data for backtesting
df['date_time'] = df[0] + ' ' + df[1]
pd.to_datetime(df.date_time)
df.set_index('date_time',inplace=True)
df.drop(columns=[0,1], inplace=True)
df

                           2        3        4        5   6  7   8
date_time
2021.01.04 00:01:00  1.22395  1.22395  1.22395  1.22395   1  0  60
2021.01.04 00:02:00  1.22393  1.22396  1.22373  1.22373   4  0  38
2021.01.04 00:03:00  1.22374  1.22374  1.22366  1.22373   4  0  30
2021.01.04 00:04:00  1.22374  1.22374  1.22280  1.22298   9  0  32
2021.01.04 00:05:00  1.22318  1.22337  1.22318  1.22330  19  0  28
...                      ...      ...      ...      ...  .. ..  ..
2022.03.11 23:50:00  1.09118  1.09140  1.09118  1.09132  38  0  14
2022.03.11 23:51:00  1.09132  1.09142  1.09130  1.09133  27  0  15
2022.03.11 23:52:00  1.09133  1.09143  1.09132  1.09137  15  0  15
2022.03.11 23:53:00  1.09138  1.09147  1.09131  1.09131  27  0  15
2022.03.11 23:54:00  1.09127  1.09139  1.09125  1.09137  12  0  15

[445072 rows x 7 columns]

In [826]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 445072 entries, 2021.01.04 00:01:00 to 2022.03.11 23:54:00
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   2       445072 non-null  object
 1   3       445072 non-null  object
 2   4       445072 non-null  object
 3   5       445072 non-null  object
 4   6       445072 non-null  object
 5   7       445072 non-null  object
 6   8       445072 non-null  object
dtypes: object(7)
memory usage: 27.2+ MB

In [827]:
#Choose if you want tail or date_time range here for backtest
#df_close_col = pd.DataFrame(data=df.iloc[:,5].tail(350000))
df_backtest = pd.DataFrame(df.loc['2017.01.03 00:00:00':'2022.03.14 00:00:00',5])

In [828]:
df_backtest

                           5
date_time
2021.01.04 00:01:00  1.22395
2021.01.04 00:02:00  1.22373
2021.01.04 00:03:00  1.22373
2021.01.04 00:04:00  1.22298
2021.01.04 00:05:00  1.22330
...                      ...
2022.03.11 23:50:00  1.09132
2022.03.11 23:51:00  1.09133
2022.03.11 23:52:00  1.09137
2022.03.11 23:53:00  1.09131
2022.03.11 23:54:00  1.09137

[445072 rows x 1 columns]

In [829]:
#use df_backtest later on df_train
#separate variables
df_close_col = df_backtest

In [830]:
#separate variables
df_backtest_idx = df_backtest
#return index to int
df_backtest_idx.reset_index(level=['date_time'], inplace=True)
df_backtest_idx = df_backtest_idx.iloc[-1440:]
df_backtest_idx

                  date_time        5
443632  2022.03.10 23:55:00  1.09871
443633  2022.03.10 23:56:00  1.09873
443634  2022.03.10 23:57:00  1.09881
443635  2022.03.10 23:58:00  1.09882
443636  2022.03.10 23:59:00  1.09859
...                     ...      ...
445067  2022.03.11 23:50:00  1.09132
445068  2022.03.11 23:51:00  1.09133
445069  2022.03.11 23:52:00  1.09137
445070  2022.03.11 23:53:00  1.09131
445071  2022.03.11 23:54:00  1.09137

[1440 rows x 2 columns]

In [831]:
df_backtest_idx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 443632 to 445071
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date_time  1440 non-null   object
 1   5          1440 non-null   object
dtypes: object(2)
memory usage: 22.6+ KB

In [832]:
df_close_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445072 entries, 0 to 445071
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date_time  445072 non-null  object
 1   5          445072 non-null  object
dtypes: object(2)
memory usage: 6.8+ MB

In [833]:
df_close_col[5] = df_close_col[5].astype(float, errors = 'raise')

In [834]:
df_close_col.drop(['date_time'], axis=1,inplace=True)

In [835]:
df_close_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445072 entries, 0 to 445071
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   5       445072 non-null  float64
dtypes: float64(1)
memory usage: 3.4 MB

In [836]:
df_close_col.isnull().sum()

5    0
dtype: int64

In [837]:
df_close_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445072 entries, 0 to 445071
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   5       445072 non-null  float64
dtypes: float64(1)
memory usage: 3.4 MB

In [838]:
###df201 to df240###
df240 = pd.DataFrame(data=df_close_col.iloc[-347040:-345600])
df240['row_num']=np.arange(len(df240))
df240.set_index('row_num',inplace=True)
df240 = df240.rename(columns={5:'frame_240'})
print(df240)

df239 = pd.DataFrame(data=df_close_col.iloc[-345600:-344160])
df239['row_num']=np.arange(len(df239))
df239.set_index('row_num',inplace=True)
df239 = df239.rename(columns={5:'frame_239'})
print(df239)

df238 = pd.DataFrame(data=df_close_col.iloc[-344160:-342720])
df238['row_num']=np.arange(len(df238))
df238.set_index('row_num',inplace=True)
df238 = df238.rename(columns={5:'frame_238'})
print(df238)

df237 = pd.DataFrame(data=df_close_col.iloc[-342720:-341280])
df237['row_num']=np.arange(len(df237))
df237.set_index('row_num',inplace=True)
df237 = df237.rename(columns={5:'frame_237'})
print(df237)

df236 = pd.DataFrame(data=df_close_col.iloc[-341280:-339840])
df236['row_num']=np.arange(len(df236))
df236.set_index('row_num',inplace=True)
df236 = df236.rename(columns={5:'frame_236'})
print(df236)

df235 = pd.DataFrame(data=df_close_col.iloc[-339840:-338400])
df235['row_num']=np.arange(len(df235))
df235.set_index('row_num',inplace=True)
df235 = df235.rename(columns={5:'frame_235'})
print(df235)

df234 = pd.DataFrame(data=df_close_col.iloc[-338400:-336960])
df234['row_num']=np.arange(len(df234))
df234.set_index('row_num',inplace=True)
df234 = df234.rename(columns={5:'frame_234'})
print(df234)

df233 = pd.DataFrame(data=df_close_col.iloc[-336960:-335520])
df233['row_num']=np.arange(len(df233))
df233.set_index('row_num',inplace=True)
df233 = df233.rename(columns={5:'frame_233'})
print(df233)

df232 = pd.DataFrame(data=df_close_col.iloc[-335520:-334080])
df232['row_num']=np.arange(len(df232))
df232.set_index('row_num',inplace=True)
df232 = df232.rename(columns={5:'frame_232'})
print(df232)

df231 = pd.DataFrame(data=df_close_col.iloc[-334080:-332640])
df231['row_num']=np.arange(len(df231))
df231.set_index('row_num',inplace=True)
df231 = df231.rename(columns={5:'frame_231'})
print(df231)

df230 = pd.DataFrame(data=df_close_col.iloc[-332640:-331200])
df230['row_num']=np.arange(len(df230))
df230.set_index('row_num',inplace=True)
df230 = df230.rename(columns={5:'frame_230'})
print(df230)

df229 = pd.DataFrame(data=df_close_col.iloc[-331200:-329760])
df229['row_num']=np.arange(len(df229))
df229.set_index('row_num',inplace=True)
df229 = df229.rename(columns={5:'frame_229'})
print(df229)

df228 = pd.DataFrame(data=df_close_col.iloc[-329760:-328320])
df228['row_num']=np.arange(len(df228))
df228.set_index('row_num',inplace=True)
df228 = df228.rename(columns={5:'frame_228'})
print(df228)

df227 = pd.DataFrame(data=df_close_col.iloc[-328320:-326880])
df227['row_num']=np.arange(len(df227))
df227.set_index('row_num',inplace=True)
df227 = df227.rename(columns={5:'frame_227'})
print(df227)

df226 = pd.DataFrame(data=df_close_col.iloc[-326880:-325440])
df226['row_num']=np.arange(len(df226))
df226.set_index('row_num',inplace=True)
df226 = df226.rename(columns={5:'frame_226'})
print(df226)

df225 = pd.DataFrame(data=df_close_col.iloc[-325440:-324000])
df225['row_num']=np.arange(len(df225))
df225.set_index('row_num',inplace=True)
df225 = df225.rename(columns={5:'frame_225'})
print(df225)

df224 = pd.DataFrame(data=df_close_col.iloc[-324000:-322560])
df224['row_num']=np.arange(len(df224))
df224.set_index('row_num',inplace=True)
df224 = df224.rename(columns={5:'frame_224'})
print(df224)

df223 = pd.DataFrame(data=df_close_col.iloc[-322560:-321120])
df223['row_num']=np.arange(len(df223))
df223.set_index('row_num',inplace=True)
df223 = df223.rename(columns={5:'frame_223'})
print(df223)

df222 = pd.DataFrame(data=df_close_col.iloc[-321120:-319680])
df222['row_num']=np.arange(len(df222))
df222.set_index('row_num',inplace=True)
df222 = df222.rename(columns={5:'frame_222'})
print(df222)

df221 = pd.DataFrame(data=df_close_col.iloc[-319680:-318240])
df221['row_num']=np.arange(len(df221))
df221.set_index('row_num',inplace=True)
df221 = df221.rename(columns={5:'frame_221'})
print(df221)


df220 = pd.DataFrame(data=df_close_col.iloc[-318240:-316800])
df220['row_num']=np.arange(len(df220))
df220.set_index('row_num',inplace=True)
df220 = df220.rename(columns={5:'frame_220'})
print(df220)

df219 = pd.DataFrame(data=df_close_col.iloc[-316800:-315360])
df219['row_num']=np.arange(len(df219))
df219.set_index('row_num',inplace=True)
df219 = df219.rename(columns={5:'frame_219'})
print(df219)

df218 = pd.DataFrame(data=df_close_col.iloc[-315360:-313920])
df218['row_num']=np.arange(len(df218))
df218.set_index('row_num',inplace=True)
df218 = df218.rename(columns={5:'frame_218'})
print(df218)

df217 = pd.DataFrame(data=df_close_col.iloc[-313920:-312480])
df217['row_num']=np.arange(len(df217))
df217.set_index('row_num',inplace=True)
df217 = df217.rename(columns={5:'frame_217'})
print(df217)

df216 = pd.DataFrame(data=df_close_col.iloc[-312480:-311040])
df216['row_num']=np.arange(len(df216))
df216.set_index('row_num',inplace=True)
df216 = df216.rename(columns={5:'frame_216'})
print(df216)

df215 = pd.DataFrame(data=df_close_col.iloc[-311040:-309600])
df215['row_num']=np.arange(len(df215))
df215.set_index('row_num',inplace=True)
df215 = df215.rename(columns={5:'frame_215'})
print(df215)

df214 = pd.DataFrame(data=df_close_col.iloc[-309600:-308160])
df214['row_num']=np.arange(len(df214))
df214.set_index('row_num',inplace=True)
df214 = df214.rename(columns={5:'frame_214'})
print(df214)

df213 = pd.DataFrame(data=df_close_col.iloc[-308160:-306720])
df213['row_num']=np.arange(len(df213))
df213.set_index('row_num',inplace=True)
df213 = df213.rename(columns={5:'frame_213'})
print(df213)

df212 = pd.DataFrame(data=df_close_col.iloc[-306720:-305280])
df212['row_num']=np.arange(len(df212))
df212.set_index('row_num',inplace=True)
df212 = df212.rename(columns={5:'frame_212'})
print(df212)

df211 = pd.DataFrame(data=df_close_col.iloc[-305280:-303840])
df211['row_num']=np.arange(len(df211))
df211.set_index('row_num',inplace=True)
df211 = df211.rename(columns={5:'frame_211'})
print(df211)

df210 = pd.DataFrame(data=df_close_col.iloc[-303840:-302400])
df210['row_num']=np.arange(len(df210))
df210.set_index('row_num',inplace=True)
df210 = df210.rename(columns={5:'frame_210'})
print(df210)

df209 = pd.DataFrame(data=df_close_col.iloc[-302400:-300960])
df209['row_num']=np.arange(len(df209))
df209.set_index('row_num',inplace=True)
df209 = df209.rename(columns={5:'frame_209'})
print(df209)

df208 = pd.DataFrame(data=df_close_col.iloc[-300960:-299520])
df208['row_num']=np.arange(len(df208))
df208.set_index('row_num',inplace=True)
df208 = df208.rename(columns={5:'frame_208'})
print(df208)

df207 = pd.DataFrame(data=df_close_col.iloc[-299520:-298080])
df207['row_num']=np.arange(len(df207))
df207.set_index('row_num',inplace=True)
df207 = df207.rename(columns={5:'frame_207'})
print(df207)

df206 = pd.DataFrame(data=df_close_col.iloc[-298080:-296640])
df206['row_num']=np.arange(len(df206))
df206.set_index('row_num',inplace=True)
df206 = df206.rename(columns={5:'frame_206'})
print(df206)

df205 = pd.DataFrame(data=df_close_col.iloc[-296640:-295200])
df205['row_num']=np.arange(len(df205))
df205.set_index('row_num',inplace=True)
df205 = df205.rename(columns={5:'frame_205'})
print(df205)

df204 = pd.DataFrame(data=df_close_col.iloc[-295200:-293760])
df204['row_num']=np.arange(len(df204))
df204.set_index('row_num',inplace=True)
df204 = df204.rename(columns={5:'frame_204'})
print(df204)

df203 = pd.DataFrame(data=df_close_col.iloc[-293760:-292320])
df203['row_num']=np.arange(len(df203))
df203.set_index('row_num',inplace=True)
df203 = df203.rename(columns={5:'frame_203'})
print(df203)

df202 = pd.DataFrame(data=df_close_col.iloc[-292320:-290880])
df202['row_num']=np.arange(len(df202))
df202.set_index('row_num',inplace=True)
df202 = df202.rename(columns={5:'frame_202'})
print(df202)

df201 = pd.DataFrame(data=df_close_col.iloc[-290880:-289440])
df201['row_num']=np.arange(len(df201))
df201.set_index('row_num',inplace=True)
df201 = df201.rename(columns={5:'frame_201'})
print(df201)
###df201 to df 240###

         frame_240
row_num
0          1.18700
1          1.18698
2          1.18700
3          1.18702
4          1.18705
...            ...
1435       1.19059
1436       1.19059
1437       1.19053
1438       1.19054
1439       1.19054

[1440 rows x 1 columns]
         frame_239
row_num
0          1.19060
1          1.19052
2          1.19038
3          1.19040
4          1.19035
...            ...
1435       1.18878
1436       1.18882
1437       1.18883
1438       1.18883
1439       1.18886

[1440 rows x 1 columns]
         frame_238
row_num
0          1.18890
1          1.18877
2          1.18881
3          1.18901
4          1.18887
...            ...
1435       1.18985
1436       1.18976
1437       1.18980
1438       1.18981
1439       1.18985

[1440 rows x 1 columns]
         frame_237
row_num
0          1.18986
1          1.18985
2          1.18979
3          1.18971
4          1.18975
...            ...
1435       1.19594
1436       1.19595
1437       1.19597
1438       1.19592
1439       1.19590

[1440 rows x 1 columns]
         frame_236
row_num
0          1.19590
1          1.19587
2          1.19588
3          1.19582
4          1.19582
...            ...
1435       1.19740
1436       1.19733
1437       1.19738
1438       1.19735
1439       1.19740

[1440 rows x 1 columns]
         frame_235
row_num
0          1.19745
1          1.19750
2          1.19748
3          1.19749
4          1.19749
...            ...
1435       1.19525
1436       1.19524
1437       1.19526
1438       1.19527
1439       1.19532

[1440 rows x 1 columns]
         frame_234
row_num
0          1.19527
1          1.19529
2          1.19530
3          1.19530
4          1.19536
...            ...
1435       1.19538
1436       1.19538
1437       1.19536
1438       1.19538
1439       1.19539

[1440 rows x 1 columns]
         frame_233
row_num
0          1.19544
1          1.19544
2          1.19544
3          1.19544
4          1.19545
...            ...
1435       1.20584
1436       1.20593
1437       1.20592
1438       1.20676
1439       1.20680

[1440 rows x 1 columns]
         frame_232
row_num
0          1.20661
1          1.20671
2          1.20684
3          1.20687
4          1.20706
...            ...
1435       1.20320
1436       1.20320
1437       1.20319
1438       1.20318
1439       1.20314

[1440 rows x 1 columns]
         frame_231
row_num
0          1.20318
1          1.20313
2          1.20320
3          1.20310
4          1.20313
...            ...
1435       1.20453
1436       1.20452
1437       1.20454
1438       1.20449
1439       1.20447

[1440 rows x 1 columns]
         frame_230
row_num
0          1.20443
1          1.20443
2          1.20449
3          1.20454
4          1.20448
...            ...
1435       1.20230
1436       1.20228
1437       1.20220
1438       1.20217
1439       1.20229

[1440 rows x 1 columns]
         frame_229
row_num
0          1.20231
1          1.20224
2          1.20230
3          1.20235
4          1.20230
...            ...
1435       1.21161
1436       1.21158
1437       1.21145
1438       1.21142
1439       1.21142

[1440 rows x 1 columns]
         frame_228
row_num
0          1.21134
1          1.21133
2          1.21125
3          1.21130
4          1.21114
...            ...
1435       1.20708
1436       1.20710
1437       1.20705
1438       1.20704
1439       1.20700

[1440 rows x 1 columns]
         frame_227
row_num
0          1.20701
1          1.20702
2          1.20698
3          1.20693
4          1.20693
...            ...
1435       1.20765
1436       1.20767
1437       1.20763
1438       1.20768
1439       1.20766

[1440 rows x 1 columns]
         frame_226
row_num
0          1.20764
1          1.20763
2          1.20772
3          1.20778
4          1.20778
...            ...
1435       1.21366
1436       1.21365
1437       1.21365
1438       1.21368
1439       1.21364

[1440 rows x 1 columns]
         frame_225
row_num
0          1.21369
1          1.21364
2          1.21366
3          1.21353
4          1.21344
...            ...
1435       1.21196
1436       1.21195
1437       1.21189
1438       1.21189
1439       1.21174

[1440 rows x 1 columns]
         frame_224
row_num
0          1.21178
1          1.21174
2          1.21175
3          1.21169
4          1.21168
...            ...
1435       1.20219
1436       1.20220
1437       1.20219
1438       1.20216
1439       1.20214

[1440 rows x 1 columns]
         frame_223
row_num
0          1.20219
1          1.20213
2          1.20219
3          1.20220
4          1.20222
...            ...
1435       1.20400
1436       1.20401
1437       1.20401
1438       1.20401
1439       1.20401

[1440 rows x 1 columns]
         frame_222
row_num
0          1.20401
1          1.20404
2          1.20406
3          1.20413
4          1.20400
...            ...
1435       1.20260
1436       1.20255
1437       1.20255
1438       1.20256
1439       1.20256

[1440 rows x 1 columns]
         frame_221
row_num
0          1.20255
1          1.20254
2          1.20256
3          1.20256
4          1.20255
...            ...
1435       1.19991
1436       1.19995
1437       1.19990
1438       1.19983
1439       1.19981

[1440 rows x 1 columns]
         frame_220
row_num
0          1.19981
1          1.19980
2          1.19986
3          1.19985
4          1.19976
...            ...
1435       1.20692
1436       1.20687
1437       1.20692
1438       1.20688
1439       1.20683

[1440 rows x 1 columns]
         frame_219
row_num
0          1.20682
1          1.20681
2          1.20682
3          1.20679
4          1.20672
...            ...
1435       1.21562
1436       1.21558
1437       1.21553
1438       1.21557
1439       1.21558

[1440 rows x 1 columns]
         frame_218
row_num
0          1.21561
1          1.21562
2          1.21568
3          1.21559
4          1.21557
...            ...
1435       1.21446
1436       1.21453
1437       1.21461
1438       1.21462
1439       1.21453

[1440 rows x 1 columns]
         frame_217
row_num
0          1.21442
1          1.21427
2          1.21433
3          1.21438
4          1.21433
...            ...
1435       1.21262
1436       1.21263
1437       1.21259
1438       1.21263
1439       1.21257

[1440 rows x 1 columns]
         frame_216
row_num
0          1.21257
1          1.21239
2          1.21246
3          1.21242
4          1.21244
...            ...
1435       1.20769
1436       1.20758
1437       1.20756
1438       1.20760
1439       1.20760

[1440 rows x 1 columns]
         frame_215
row_num
0          1.20766
1          1.20761
2          1.20755
3          1.20757
4          1.20756
...            ...
1435       1.20828
1436       1.20834
1437       1.20826
1438       1.20823
1439       1.20828

[1440 rows x 1 columns]
         frame_214
row_num
0          1.20835
1          1.20844
2          1.20839
3          1.20839
4          1.20838
...            ...
1435       1.21338
1436       1.21344
1437       1.21345
1438       1.21344
1439       1.21346

[1440 rows x 1 columns]
         frame_213
row_num
0          1.21344
1          1.21335
2          1.21335
3          1.21338
4          1.21335
...            ...
1435       1.21682
1436       1.21681
1437       1.21681
1438       1.21687
1439       1.21687

[1440 rows x 1 columns]
         frame_212
row_num
0          1.21685
1          1.21671
2          1.21675
3          1.21665
4          1.21671
...            ...
1435       1.22295
1436       1.22295
1437       1.22292
1438       1.22290
1439       1.22286

[1440 rows x 1 columns]
         frame_211
row_num
0          1.22290
1          1.22292
2          1.22291
3          1.22296
4          1.22298
...            ...
1435       1.21840
1436       1.21836
1437       1.21836
1438       1.21841
1439       1.21837

[1440 rows x 1 columns]
         frame_210
row_num
0          1.21832
1          1.21827
2          1.21826
3          1.21827
4          1.21827
...            ...
1435       1.22325
1436       1.22321
1437       1.22319
1438       1.22316
1439       1.22313

[1440 rows x 1 columns]
         frame_209
row_num
0          1.22314
1          1.22312
2          1.22308
3          1.22305
4          1.22311
...            ...
1435       1.21804
1436       1.21815
1437       1.21820
1438       1.21821
1439       1.21820

[1440 rows x 1 columns]
         frame_208
row_num
0          1.21815
1          1.21821
2          1.21813
3          1.21813
4          1.21811
...            ...
1435       1.22256
1436       1.22267
1437       1.22266
1438       1.22261
1439       1.22260

[1440 rows x 1 columns]
         frame_207
row_num
0          1.22260
1          1.22266
2          1.22265
3          1.22267
4          1.22266
...            ...
1435       1.22577
1436       1.22582
1437       1.22586
1438       1.22592
1439       1.22588

[1440 rows x 1 columns]
         frame_206
row_num
0          1.22592
1          1.22596
2          1.22584
3          1.22576
4          1.22583
...            ...
1435       1.21926
1436       1.21923
1437       1.21929
1438       1.21922
1439       1.21927

[1440 rows x 1 columns]
         frame_205
row_num
0          1.21926
1          1.21939
2          1.21942
3          1.21940
4          1.21932
...            ...
1435       1.21883
1436       1.21878
1437       1.21877
1438       1.21877
1439       1.21872

[1440 rows x 1 columns]
         frame_204
row_num
0          1.21874
1          1.21878
2          1.21877
3          1.21873
4          1.21871
...            ...
1435       1.21990
1436       1.21986
1437       1.21991
1438       1.21987
1439       1.21989

[1440 rows x 1 columns]
         frame_203
row_num
0          1.21975
1          1.21981
2          1.21979
3          1.21984
4          1.21985
...            ...
1435       1.22295
1436       1.22295
1437       1.22295
1438       1.22302
1439       1.22296

[1440 rows x 1 columns]
         frame_202
row_num
0          1.22296
1          1.22296
2          1.22289
3          1.22285
4          1.22289
...            ...
1435       1.22228
1436       1.22225
1437       1.22229
1438       1.22229
1439       1.22230

[1440 rows x 1 columns]
         frame_201
row_num
0          1.22220
1          1.22226
2          1.22226
3          1.22225
4          1.22219
...            ...
1435       1.22063
1436       1.22061
1437       1.22063
1438       1.22065
1439       1.22059

[1440 rows x 1 columns]

In [839]:
###df161 to df200###
df200 = pd.DataFrame(data=df_close_col.iloc[-289440:-288000])
df200['row_num']=np.arange(len(df200))
df200.set_index('row_num',inplace=True)
df200 = df200.rename(columns={5:'frame_200'})
print(df200)

df199 = pd.DataFrame(data=df_close_col.iloc[-288000:-286560])
df199['row_num']=np.arange(len(df199))
df199.set_index('row_num',inplace=True)
df199 = df199.rename(columns={5:'frame_199'})
print(df199)

df198 = pd.DataFrame(data=df_close_col.iloc[-286560:-285120])
df198['row_num']=np.arange(len(df198))
df198.set_index('row_num',inplace=True)
df198 = df198.rename(columns={5:'frame_198'})
print(df198)

df197 = pd.DataFrame(data=df_close_col.iloc[-285120:-283680])
df197['row_num']=np.arange(len(df197))
df197.set_index('row_num',inplace=True)
df197 = df197.rename(columns={5:'frame_197'})
print(df197)

df196 = pd.DataFrame(data=df_close_col.iloc[-283680:-282240])
df196['row_num']=np.arange(len(df196))
df196.set_index('row_num',inplace=True)
df196 = df196.rename(columns={5:'frame_196'})
print(df196)

df195 = pd.DataFrame(data=df_close_col.iloc[-282240:-280800])
df195['row_num']=np.arange(len(df195))
df195.set_index('row_num',inplace=True)
df195 = df195.rename(columns={5:'frame_195'})
print(df195)

df194 = pd.DataFrame(data=df_close_col.iloc[-280800:-279360])
df194['row_num']=np.arange(len(df194))
df194.set_index('row_num',inplace=True)
df194 = df194.rename(columns={5:'frame_194'})
print(df194)

df193 = pd.DataFrame(data=df_close_col.iloc[-279360:-277920])
df193['row_num']=np.arange(len(df193))
df193.set_index('row_num',inplace=True)
df193 = df193.rename(columns={5:'frame_193'})
print(df193)

df192 = pd.DataFrame(data=df_close_col.iloc[-277920:-276480])
df192['row_num']=np.arange(len(df192))
df192.set_index('row_num',inplace=True)
df192 = df192.rename(columns={5:'frame_192'})
print(df192)

df191 = pd.DataFrame(data=df_close_col.iloc[-276480:-275040])
df191['row_num']=np.arange(len(df191))
df191.set_index('row_num',inplace=True)
df191 = df191.rename(columns={5:'frame_191'})
print(df191)

df190 = pd.DataFrame(data=df_close_col.iloc[-275040:-273600])
df190['row_num']=np.arange(len(df190))
df190.set_index('row_num',inplace=True)
df190 = df190.rename(columns={5:'frame_190'})
print(df190)

df189 = pd.DataFrame(data=df_close_col.iloc[-273600:-272160])
df189['row_num']=np.arange(len(df189))
df189.set_index('row_num',inplace=True)
df189 = df189.rename(columns={5:'frame_189'})
print(df189)

df188 = pd.DataFrame(data=df_close_col.iloc[-272160:-270720])
df188['row_num']=np.arange(len(df188))
df188.set_index('row_num',inplace=True)
df188 = df188.rename(columns={5:'frame_188'})
print(df188)

df187 = pd.DataFrame(data=df_close_col.iloc[-270720:-269280])
df187['row_num']=np.arange(len(df187))
df187.set_index('row_num',inplace=True)
df187 = df187.rename(columns={5:'frame_187'})
print(df187)

df186 = pd.DataFrame(data=df_close_col.iloc[-269280:-267840])
df186['row_num']=np.arange(len(df186))
df186.set_index('row_num',inplace=True)
df186 = df186.rename(columns={5:'frame_186'})
print(df186)

df185 = pd.DataFrame(data=df_close_col.iloc[-267840:-266400])
df185['row_num']=np.arange(len(df185))
df185.set_index('row_num',inplace=True)
df185 = df185.rename(columns={5:'frame_185'})
print(df185)

df184 = pd.DataFrame(data=df_close_col.iloc[-266400:-264960])
df184['row_num']=np.arange(len(df184))
df184.set_index('row_num',inplace=True)
df184 = df184.rename(columns={5:'frame_184'})
print(df184)

df183 = pd.DataFrame(data=df_close_col.iloc[-264960:-263520])
df183['row_num']=np.arange(len(df183))
df183.set_index('row_num',inplace=True)
df183 = df183.rename(columns={5:'frame_183'})
print(df183)

df182 = pd.DataFrame(data=df_close_col.iloc[-263520:-262080])
df182['row_num']=np.arange(len(df182))
df182.set_index('row_num',inplace=True)
df182 = df182.rename(columns={5:'frame_182'})
print(df182)

df181 = pd.DataFrame(data=df_close_col.iloc[-262080:-260640])
df181['row_num']=np.arange(len(df181))
df181.set_index('row_num',inplace=True)
df181 = df181.rename(columns={5:'frame_181'})
print(df181)


df180 = pd.DataFrame(data=df_close_col.iloc[-260640:-259200])
df180['row_num']=np.arange(len(df180))
df180.set_index('row_num',inplace=True)
df180 = df180.rename(columns={5:'frame_180'})
print(df180)

df179 = pd.DataFrame(data=df_close_col.iloc[-259200:-257760])
df179['row_num']=np.arange(len(df179))
df179.set_index('row_num',inplace=True)
df179 = df179.rename(columns={5:'frame_179'})
print(df179)

df178 = pd.DataFrame(data=df_close_col.iloc[-257760:-256320])
df178['row_num']=np.arange(len(df178))
df178.set_index('row_num',inplace=True)
df178 = df178.rename(columns={5:'frame_178'})
print(df178)

df177 = pd.DataFrame(data=df_close_col.iloc[-256320:-254880])
df177['row_num']=np.arange(len(df177))
df177.set_index('row_num',inplace=True)
df177 = df177.rename(columns={5:'frame_177'})
print(df177)

df176 = pd.DataFrame(data=df_close_col.iloc[-254880:-253440])
df176['row_num']=np.arange(len(df176))
df176.set_index('row_num',inplace=True)
df176 = df176.rename(columns={5:'frame_176'})
print(df176)

df175 = pd.DataFrame(data=df_close_col.iloc[-253440:-252000])
df175['row_num']=np.arange(len(df175))
df175.set_index('row_num',inplace=True)
df175 = df175.rename(columns={5:'frame_175'})
print(df175)

df174 = pd.DataFrame(data=df_close_col.iloc[-252000:-250560])
df174['row_num']=np.arange(len(df174))
df174.set_index('row_num',inplace=True)
df174 = df174.rename(columns={5:'frame_174'})
print(df174)

df173 = pd.DataFrame(data=df_close_col.iloc[-250560:-249120])
df173['row_num']=np.arange(len(df173))
df173.set_index('row_num',inplace=True)
df173 = df173.rename(columns={5:'frame_173'})
print(df173)

df172 = pd.DataFrame(data=df_close_col.iloc[-249120:-247680])
df172['row_num']=np.arange(len(df172))
df172.set_index('row_num',inplace=True)
df172 = df172.rename(columns={5:'frame_172'})
print(df172)

df171 = pd.DataFrame(data=df_close_col.iloc[-247680:-246240])
df171['row_num']=np.arange(len(df171))
df171.set_index('row_num',inplace=True)
df171 = df171.rename(columns={5:'frame_171'})
print(df171)

df170 = pd.DataFrame(data=df_close_col.iloc[-246240:-244800])
df170['row_num']=np.arange(len(df170))
df170.set_index('row_num',inplace=True)
df170 = df170.rename(columns={5:'frame_170'})
print(df170)

df169 = pd.DataFrame(data=df_close_col.iloc[-244800:-243360])
df169['row_num']=np.arange(len(df169))
df169.set_index('row_num',inplace=True)
df169 = df169.rename(columns={5:'frame_169'})
print(df169)

df168 = pd.DataFrame(data=df_close_col.iloc[-243360:-241920])
df168['row_num']=np.arange(len(df168))
df168.set_index('row_num',inplace=True)
df168 = df168.rename(columns={5:'frame_168'})
print(df168)

df167 = pd.DataFrame(data=df_close_col.iloc[-241920:-240480])
df167['row_num']=np.arange(len(df167))
df167.set_index('row_num',inplace=True)
df167 = df167.rename(columns={5:'frame_167'})
print(df167)

df166 = pd.DataFrame(data=df_close_col.iloc[-240480:-239040])
df166['row_num']=np.arange(len(df166))
df166.set_index('row_num',inplace=True)
df166 = df166.rename(columns={5:'frame_166'})
print(df166)

df165 = pd.DataFrame(data=df_close_col.iloc[-239040:-237600])
df165['row_num']=np.arange(len(df165))
df165.set_index('row_num',inplace=True)
df165 = df165.rename(columns={5:'frame_165'})
print(df165)

df164 = pd.DataFrame(data=df_close_col.iloc[-237600:-236160])
df164['row_num']=np.arange(len(df164))
df164.set_index('row_num',inplace=True)
df164 = df164.rename(columns={5:'frame_164'})
print(df164)

df163 = pd.DataFrame(data=df_close_col.iloc[-236160:-234720])
df163['row_num']=np.arange(len(df163))
df163.set_index('row_num',inplace=True)
df163 = df163.rename(columns={5:'frame_163'})
print(df163)

df162 = pd.DataFrame(data=df_close_col.iloc[-234720:-233280])
df162['row_num']=np.arange(len(df162))
df162.set_index('row_num',inplace=True)
df162 = df162.rename(columns={5:'frame_162'})
print(df162)

df161 = pd.DataFrame(data=df_close_col.iloc[-233280:-231840])
df161['row_num']=np.arange(len(df161))
df161.set_index('row_num',inplace=True)
df161 = df161.rename(columns={5:'frame_161'})
print(df161)
###df161 to df200###

         frame_200
row_num
0          1.22060
1          1.22065
2          1.22070
3          1.22070
4          1.22073
...            ...
1435       1.21165
1436       1.21166
1437       1.21154
1438       1.21151
1439       1.21155

[1440 rows x 1 columns]
         frame_199
row_num
0          1.21143
1          1.21145
2          1.21149
3          1.21150
4          1.21156
...            ...
1435       1.21670
1436       1.21670
1437       1.21669
1438       1.21669
1439       1.21669

[1440 rows x 1 columns]
         frame_198
row_num
0          1.21660
1          1.21655
2          1.21654
3          1.21655
4          1.21653
...            ...
1435       1.21776
1436       1.21782
1437       1.21779
1438       1.21778
1439       1.21783

[1440 rows x 1 columns]
         frame_197
row_num
0          1.21784
1          1.21778
2          1.21783
3          1.21783
4          1.21783
...            ...
1435       1.21800
1436       1.21798
1437       1.21796
1438       1.21796
1439       1.21794

[1440 rows x 1 columns]
         frame_196
row_num
0          1.21797
1          1.21801
2          1.21802
3          1.21801
4          1.21801
...            ...
1435       1.21671
1436       1.21671
1437       1.21663
1438       1.21657
1439       1.21658

[1440 rows x 1 columns]
         frame_195
row_num
0          1.21659
1          1.21658
2          1.21659
3          1.21660
4          1.21661
...            ...
1435       1.21898
1436       1.21899
1437       1.21898
1438       1.21898
1439       1.21898

[1440 rows x 1 columns]
         frame_194
row_num
0          1.21899
1          1.21903
2          1.21903
3          1.21903
4          1.21903
...            ...
1435       1.20985
1436       1.20989
1437       1.20988
1438       1.20989
1439       1.20984

[1440 rows x 1 columns]
         frame_193
row_num
0          1.20990
1          1.20989
2          1.20988
3          1.20977
4          1.20974
...            ...
1435       1.21251
1436       1.21251
1437       1.21252
1438       1.21252
1439       1.21252

[1440 rows x 1 columns]
         frame_192
row_num
0          1.21252
1          1.21268
2          1.21257
3          1.21258
4          1.21263
...            ...
1435       1.21288
1436       1.21294
1437       1.21289
1438       1.21294
1439       1.21293

[1440 rows x 1 columns]
         frame_191
row_num
0          1.21294
1          1.21293
2          1.21289
3          1.21293
4          1.21293
...            ...
1435       1.19687
1436       1.19638
1437       1.19621
1438       1.19624
1439       1.19603

[1440 rows x 1 columns]
         frame_190
row_num
0          1.19562
1          1.19552
2          1.19513
3          1.19517
4          1.19543
...            ...
1435       1.19147
1436       1.19174
1437       1.19180
1438       1.19195
1439       1.19187

[1440 rows x 1 columns]
         frame_189
row_num
0          1.19179
1          1.19185
2          1.19180
3          1.19199
4          1.19215
...            ...
1435       1.18970
1436       1.18973
1437       1.18974
1438       1.18970
1439       1.18969

[1440 rows x 1 columns]
         frame_188
row_num
0          1.18976
1          1.18971
2          1.18975
3          1.18975
4          1.18957
...            ...
1435       1.18880
1436       1.18896
1437       1.18898
1438       1.18897
1439       1.18908

[1440 rows x 1 columns]
         frame_187
row_num
0          1.18907
1          1.18910
2          1.18904
3          1.18901
4          1.18894
...            ...
1435       1.19388
1436       1.19373
1437       1.19368
1438       1.19377
1439       1.19368

[1440 rows x 1 columns]
         frame_186
row_num
0          1.19385
1          1.19412
2          1.19432
3          1.19435
4          1.19433
...            ...
1435       1.19424
1436       1.19416
1437       1.19422
1438       1.19428
1439       1.19422

[1440 rows x 1 columns]
         frame_185
row_num
0          1.19425
1          1.19428
2          1.19440
3          1.19449
4          1.19445
...            ...
1435       1.19408
1436       1.19406
1437       1.19414
1438       1.19408
1439       1.19415

[1440 rows x 1 columns]
         frame_184
row_num
0          1.19400
1          1.19403
2          1.19409
3          1.19400
4          1.19412
...            ...
1435       1.19380
1436       1.19385
1437       1.19389
1438       1.19382
1439       1.19397

[1440 rows x 1 columns]
         frame_183
row_num
0          1.19400
1          1.19391
2          1.19386
3          1.19385
4          1.19374
...            ...
1435       1.19079
1436       1.19075
1437       1.19070
1438       1.19063
1439       1.19064

[1440 rows x 1 columns]
         frame_182
row_num
0          1.19056
1          1.19051
2          1.19047
3          1.19026
4          1.19037
...            ...
1435       1.18853
1436       1.18845
1437       1.18855
1438       1.18850
1439       1.18869

[1440 rows x 1 columns]
         frame_181
row_num
0          1.18846
1          1.18850
2          1.18848
3          1.18853
4          1.18858
...            ...
1435       1.18527
1436       1.18540
1437       1.18541
1438       1.18537
1439       1.18543

[1440 rows x 1 columns]
         frame_180
row_num
0          1.18543
1          1.18545
2          1.18557
3          1.18541
4          1.18537
...            ...
1435       1.18249
1436       1.18267
1437       1.18262
1438       1.18266
1439       1.18274

[1440 rows x 1 columns]
         frame_179
row_num
0          1.18268
1          1.18257
2          1.18255
3          1.18245
4          1.18258
...            ...
1435       1.18711
1436       1.18730
1437       1.18729
1438       1.18752
1439       1.18722

[1440 rows x 1 columns]
         frame_178
row_num
0          1.18718
1          1.18732
2          1.18739
3          1.18747
4          1.18747
...            ...
1435       1.18449
1436       1.18441
1437       1.18438
1438       1.18431
1439       1.18420

[1440 rows x 1 columns]
         frame_177
row_num
0          1.18419
1          1.18418
2          1.18414
3          1.18417
4          1.18421
...            ...
1435       1.18231
1436       1.18221
1437       1.18238
1438       1.18232
1439       1.18235

[1440 rows x 1 columns]
         frame_176
row_num
0          1.18211
1          1.18189
2          1.18199
3          1.18212
4          1.18214
...            ...
1435       1.18263
1436       1.18259
1437       1.18260
1438       1.18267
1439       1.18266

[1440 rows x 1 columns]
         frame_175
row_num
0          1.18281
1          1.18282
2          1.18280
3          1.18272
4          1.18275
...            ...
1435       1.18589
1436       1.18597
1437       1.18602
1438       1.18587
1439       1.18576

[1440 rows x 1 columns]
         frame_174
row_num
0          1.18584
1          1.18581
2          1.18584
3          1.18605
4          1.18590
...            ...
1435       1.18546
1436       1.18549
1437       1.18529
1438       1.18552
1439       1.18554

[1440 rows x 1 columns]
         frame_173
row_num
0          1.18553
1          1.18534
2          1.18535
3          1.18524
4          1.18511
...            ...
1435       1.18440
1436       1.18451
1437       1.18452
1438       1.18445
1439       1.18450

[1440 rows x 1 columns]
         frame_172
row_num
0          1.18439
1          1.18433
2          1.18448
3          1.18455
4          1.18455
...            ...
1435       1.17948
1436       1.17936
1437       1.17936
1438       1.17932
1439       1.17948

[1440 rows x 1 columns]
         frame_171
row_num
0          1.17951
1          1.17973
2          1.17971
3          1.17973
4          1.17973
...            ...
1435       1.18267
1436       1.18284
1437       1.18282
1438       1.18276
1439       1.18277

[1440 rows x 1 columns]
         frame_170
row_num
0          1.18276
1          1.18279
2          1.18287
3          1.18282
4          1.18267
...            ...
1435       1.18048
1436       1.18044
1437       1.18054
1438       1.18055
1439       1.18055

[1440 rows x 1 columns]
         frame_169
row_num
0          1.18062
1          1.18060
2          1.18066
3          1.18050
4          1.18058
...            ...
1435       1.17743
1436       1.17753
1437       1.17759
1438       1.17758
1439       1.17763

[1440 rows x 1 columns]
         frame_168
row_num
0          1.17763
1          1.17736
2          1.17752
3          1.17750
4          1.17742
...            ...
1435       1.17856
1436       1.17869
1437       1.17864
1438       1.17851
1439       1.17847

[1440 rows x 1 columns]
         frame_167
row_num
0          1.17842
1          1.17844
2          1.17833
3          1.17831
4          1.17845
...            ...
1435       1.17735
1436       1.17714
1437       1.17730
1438       1.17729
1439       1.17723

[1440 rows x 1 columns]
         frame_166
row_num
0          1.17731
1          1.17739
2          1.17732
3          1.17741
4          1.17732
...            ...
1435       1.17942
1436       1.17939
1437       1.17936
1438       1.17924
1439       1.17921

[1440 rows x 1 columns]
         frame_165
row_num
0          1.17925
1          1.17915
2          1.17915
3          1.17911
4          1.17902
...            ...
1435       1.17677
1436       1.17693
1437       1.17684
1438       1.17679
1439       1.17683

[1440 rows x 1 columns]
         frame_164
row_num
0          1.17680
1          1.17674
2          1.17680
3          1.17663
4          1.17664
...            ...
1435       1.17934
1436       1.17922
1437       1.17921
1438       1.17922
1439       1.17931

[1440 rows x 1 columns]
         frame_163
row_num
0          1.17925
1          1.17917
2          1.17911
3          1.17887
4          1.17886
...            ...
1435       1.17884
1436       1.17880
1437       1.17878
1438       1.17884
1439       1.17898

[1440 rows x 1 columns]
         frame_162
row_num
0          1.17888
1          1.17887
2          1.17868
3          1.17877
4          1.17861
...            ...
1435       1.18032
1436       1.18015
1437       1.18029
1438       1.18028
1439       1.18039

[1440 rows x 1 columns]
         frame_161
row_num
0          1.18045
1          1.18043
2          1.18051
3          1.18044
4          1.18054
...            ...
1435       1.18742
1436       1.18740
1437       1.18739
1438       1.18744
1439       1.18742

[1440 rows x 1 columns]

In [840]:
###df121 to df160###
df160 = pd.DataFrame(data=df_close_col.iloc[-231840:-230400])
df160['row_num']=np.arange(len(df160))
df160.set_index('row_num',inplace=True)
df160 = df160.rename(columns={5:'frame_160'})
print(df160)

df159 = pd.DataFrame(data=df_close_col.iloc[-230400:-228960])
df159['row_num']=np.arange(len(df159))
df159.set_index('row_num',inplace=True)
df159 = df159.rename(columns={5:'frame_159'})
print(df159)

df158 = pd.DataFrame(data=df_close_col.iloc[-228960:-227520])
df158['row_num']=np.arange(len(df158))
df158.set_index('row_num',inplace=True)
df158 = df158.rename(columns={5:'frame_158'})
print(df158)

df157 = pd.DataFrame(data=df_close_col.iloc[-227520:-226080])
df157['row_num']=np.arange(len(df157))
df157.set_index('row_num',inplace=True)
df157 = df157.rename(columns={5:'frame_157'})
print(df157)

df156 = pd.DataFrame(data=df_close_col.iloc[-226080:-224640])
df156['row_num']=np.arange(len(df156))
df156.set_index('row_num',inplace=True)
df156 = df156.rename(columns={5:'frame_156'})
print(df156)

df155 = pd.DataFrame(data=df_close_col.iloc[-224640:-223200])
df155['row_num']=np.arange(len(df155))
df155.set_index('row_num',inplace=True)
df155 = df155.rename(columns={5:'frame_155'})
print(df155)

df154 = pd.DataFrame(data=df_close_col.iloc[-223200:-221760])
df154['row_num']=np.arange(len(df154))
df154.set_index('row_num',inplace=True)
df154 = df154.rename(columns={5:'frame_154'})
print(df154)

df153 = pd.DataFrame(data=df_close_col.iloc[-221760:-220320])
df153['row_num']=np.arange(len(df153))
df153.set_index('row_num',inplace=True)
df153 = df153.rename(columns={5:'frame_153'})
print(df153)

df152 = pd.DataFrame(data=df_close_col.iloc[-220320:-218880])
df152['row_num']=np.arange(len(df152))
df152.set_index('row_num',inplace=True)
df152 = df152.rename(columns={5:'frame_152'})
print(df152)

df151 = pd.DataFrame(data=df_close_col.iloc[-218880:-217440])
df151['row_num']=np.arange(len(df151))
df151.set_index('row_num',inplace=True)
df151 = df151.rename(columns={5:'frame_151'})
print(df151)

df150 = pd.DataFrame(data=df_close_col.iloc[-217440:-216000])
df150['row_num']=np.arange(len(df150))
df150.set_index('row_num',inplace=True)
df150 = df150.rename(columns={5:'frame_150'})
print(df150)

df149 = pd.DataFrame(data=df_close_col.iloc[-216000:-214560])
df149['row_num']=np.arange(len(df149))
df149.set_index('row_num',inplace=True)
df149 = df149.rename(columns={5:'frame_149'})
print(df149)

df148 = pd.DataFrame(data=df_close_col.iloc[-214560:-213120])
df148['row_num']=np.arange(len(df148))
df148.set_index('row_num',inplace=True)
df148 = df148.rename(columns={5:'frame_148'})
print(df148)

df147 = pd.DataFrame(data=df_close_col.iloc[-213120:-211680])
df147['row_num']=np.arange(len(df147))
df147.set_index('row_num',inplace=True)
df147 = df147.rename(columns={5:'frame_147'})
print(df147)

df146 = pd.DataFrame(data=df_close_col.iloc[-211680:-210240])
df146['row_num']=np.arange(len(df146))
df146.set_index('row_num',inplace=True)
df146 = df146.rename(columns={5:'frame_146'})
print(df146)

df145 = pd.DataFrame(data=df_close_col.iloc[-210240:-208800])
df145['row_num']=np.arange(len(df145))
df145.set_index('row_num',inplace=True)
df145 = df145.rename(columns={5:'frame_145'})
print(df145)

df144 = pd.DataFrame(data=df_close_col.iloc[-208800:-207360])
df144['row_num']=np.arange(len(df144))
df144.set_index('row_num',inplace=True)
df144 = df144.rename(columns={5:'frame_144'})
print(df144)

df143 = pd.DataFrame(data=df_close_col.iloc[-207360:-205920])
df143['row_num']=np.arange(len(df143))
df143.set_index('row_num',inplace=True)
df143 = df143.rename(columns={5:'frame_143'})
print(df143)

df142 = pd.DataFrame(data=df_close_col.iloc[-205920:-204480])
df142['row_num']=np.arange(len(df142))
df142.set_index('row_num',inplace=True)
df142 = df142.rename(columns={5:'frame_142'})
print(df142)

df141 = pd.DataFrame(data=df_close_col.iloc[-204480:-203040])
df141['row_num']=np.arange(len(df141))
df141.set_index('row_num',inplace=True)
df141 = df141.rename(columns={5:'frame_141'})
print(df141)


df140 = pd.DataFrame(data=df_close_col.iloc[-203040:-201600])
df140['row_num']=np.arange(len(df140))
df140.set_index('row_num',inplace=True)
df140 = df140.rename(columns={5:'frame_140'})
print(df140)

df139 = pd.DataFrame(data=df_close_col.iloc[-201600:-200160])
df139['row_num']=np.arange(len(df139))
df139.set_index('row_num',inplace=True)
df139 = df139.rename(columns={5:'frame_139'})
print(df139)

df138 = pd.DataFrame(data=df_close_col.iloc[-200160:-198720])
df138['row_num']=np.arange(len(df138))
df138.set_index('row_num',inplace=True)
df138 = df138.rename(columns={5:'frame_138'})
print(df138)

df137 = pd.DataFrame(data=df_close_col.iloc[-198720:-197280])
df137['row_num']=np.arange(len(df137))
df137.set_index('row_num',inplace=True)
df137 = df137.rename(columns={5:'frame_137'})
print(df137)

df136 = pd.DataFrame(data=df_close_col.iloc[-197280:-195840])
df136['row_num']=np.arange(len(df136))
df136.set_index('row_num',inplace=True)
df136 = df136.rename(columns={5:'frame_136'})
print(df136)

df135 = pd.DataFrame(data=df_close_col.iloc[-195840:-194400])
df135['row_num']=np.arange(len(df135))
df135.set_index('row_num',inplace=True)
df135 = df135.rename(columns={5:'frame_135'})
print(df135)

df134 = pd.DataFrame(data=df_close_col.iloc[-194400:-192960])
df134['row_num']=np.arange(len(df134))
df134.set_index('row_num',inplace=True)
df134 = df134.rename(columns={5:'frame_134'})
print(df134)

df133 = pd.DataFrame(data=df_close_col.iloc[-192960:-191520])
df133['row_num']=np.arange(len(df133))
df133.set_index('row_num',inplace=True)
df133 = df133.rename(columns={5:'frame_133'})
print(df133)

df132 = pd.DataFrame(data=df_close_col.iloc[-191520:-190080])
df132['row_num']=np.arange(len(df132))
df132.set_index('row_num',inplace=True)
df132 = df132.rename(columns={5:'frame_132'})
print(df132)

df131 = pd.DataFrame(data=df_close_col.iloc[-190080:-188640])
df131['row_num']=np.arange(len(df131))
df131.set_index('row_num',inplace=True)
df131 = df131.rename(columns={5:'frame_131'})
print(df131)

df130 = pd.DataFrame(data=df_close_col.iloc[-188640:-187200])
df130['row_num']=np.arange(len(df130))
df130.set_index('row_num',inplace=True)
df130 = df130.rename(columns={5:'frame_130'})
print(df130)

df129 = pd.DataFrame(data=df_close_col.iloc[-187200:-185760])
df129['row_num']=np.arange(len(df129))
df129.set_index('row_num',inplace=True)
df129 = df129.rename(columns={5:'frame_129'})
print(df129)

df128 = pd.DataFrame(data=df_close_col.iloc[-185760:-184320])
df128['row_num']=np.arange(len(df128))
df128.set_index('row_num',inplace=True)
df128 = df128.rename(columns={5:'frame_128'})
print(df128)

df127 = pd.DataFrame(data=df_close_col.iloc[-184320:-182880])
df127['row_num']=np.arange(len(df127))
df127.set_index('row_num',inplace=True)
df127 = df127.rename(columns={5:'frame_127'})
print(df127)

df126 = pd.DataFrame(data=df_close_col.iloc[-182880:-181440])
df126['row_num']=np.arange(len(df126))
df126.set_index('row_num',inplace=True)
df126 = df126.rename(columns={5:'frame_126'})
print(df126)

df125 = pd.DataFrame(data=df_close_col.iloc[-181440:-180000])
df125['row_num']=np.arange(len(df125))
df125.set_index('row_num',inplace=True)
df125 = df125.rename(columns={5:'frame_125'})
print(df125)

df124 = pd.DataFrame(data=df_close_col.iloc[-180000:-178560])
df124['row_num']=np.arange(len(df124))
df124.set_index('row_num',inplace=True)
df124 = df124.rename(columns={5:'frame_124'})
print(df124)

df123 = pd.DataFrame(data=df_close_col.iloc[-178560:-177120])
df123['row_num']=np.arange(len(df123))
df123.set_index('row_num',inplace=True)
df123 = df123.rename(columns={5:'frame_123'})
print(df123)

###
#left out a day here, still need to fix it -177120:-175680
###

df122 = pd.DataFrame(data=df_close_col.iloc[-175680:-174240])
df122['row_num']=np.arange(len(df122))
df122.set_index('row_num',inplace=True)
df122 = df122.rename(columns={5:'frame_122'})
print(df122)

df121 = pd.DataFrame(data=df_close_col.iloc[-174240:-172800])
df121['row_num']=np.arange(len(df121))
df121.set_index('row_num',inplace=True)
df121 = df121.rename(columns={5:'frame_121'})
print(df121)
###df121 to df160###

         frame_160
row_num
0          1.18736
1          1.18752
2          1.18756
3          1.18762
4          1.18730
...            ...
1435       1.19009
1436       1.18993
1437       1.18985
1438       1.18995
1439       1.18969

[1440 rows x 1 columns]
         frame_159
row_num
0          1.18979
1          1.19009
2          1.19037
3          1.19037
4          1.19020
...            ...
1435       1.18885
1436       1.18888
1437       1.18909
1438       1.18918
1439       1.18914

[1440 rows x 1 columns]
         frame_158
row_num
0          1.18927
1          1.18916
2          1.18921
3          1.18917
4          1.18904
...            ...
1435       1.18871
1436       1.18868
1437       1.18869
1438       1.18883
1439       1.18880

[1440 rows x 1 columns]
         frame_157
row_num
0          1.18882
1          1.18870
2          1.18872
3          1.18883
4          1.18888
...            ...
1435       1.18547
1436       1.18554
1437       1.18550
1438       1.18555
1439       1.18554

[1440 rows x 1 columns]
         frame_156
row_num
0          1.18557
1          1.18556
2          1.18558
3          1.18551
4          1.18556
...            ...
1435       1.18451
1436       1.18466
1437       1.18466
1438       1.18462
1439       1.18460

[1440 rows x 1 columns]
         frame_155
row_num
0          1.18468
1          1.18474
2          1.18459
3          1.18459
4          1.18462
...            ...
1435       1.18048
1436       1.18052
1437       1.18052
1438       1.18060
1439       1.18063

[1440 rows x 1 columns]
         frame_154
row_num
0          1.18067
1          1.18057
2          1.18058
3          1.18057
4          1.18053
...            ...
1435       1.17583
1436       1.17599
1437       1.17607
1438       1.17605
1439       1.17608

[1440 rows x 1 columns]
         frame_153
row_num
0          1.17606
1          1.17621
2          1.17623
3          1.17634
4          1.17629
...            ...
1435       1.17242
1436       1.17226
1437       1.17228
1438       1.17221
1439       1.17219

[1440 rows x 1 columns]
         frame_152
row_num
0          1.17223
1          1.17243
2          1.17243
3          1.17236
4          1.17244
...            ...
1435       1.17139
1436       1.17143
1437       1.17150
1438       1.17152
1439       1.17157

[1440 rows x 1 columns]
         frame_151
row_num
0          1.17141
1          1.17147
2          1.17157
3          1.17155
4          1.17145
...            ...
1435       1.17358
1436       1.17366
1437       1.17372
1438       1.17367
1439       1.17368

[1440 rows x 1 columns]
         frame_150
row_num
0          1.17367
1          1.17372
2          1.17373
3          1.17378
4          1.17374
...            ...
1435       1.17514
1436       1.17515
1437       1.17518
1438       1.17550
1439       1.17543

[1440 rows x 1 columns]
         frame_149
row_num
0          1.17552
1          1.17545
2          1.17546
3          1.17540
4          1.17530
...            ...
1435       1.17753
1436       1.17768
1437       1.17763
1438       1.17746
1439       1.17742

[1440 rows x 1 columns]
         frame_148
row_num
0          1.17747
1          1.17745
2          1.17739
3          1.17729
4          1.17735
...            ...
1435       1.17696
1436       1.17687
1437       1.17680
1438       1.17681
1439       1.17691

[1440 rows x 1 columns]
         frame_147
row_num
0          1.17694
1          1.17710
2          1.17707
3          1.17708
4          1.17717
...            ...
1435       1.17072
1436       1.17074
1437       1.17088
1438       1.17101
1439       1.17102

[1440 rows x 1 columns]
         frame_146
row_num
0          1.17106
1          1.17110
2          1.17103
3          1.17090
4          1.17101
...            ...
1435       1.16959
1436       1.16950
1437       1.16954
1438       1.16958
1439       1.16954

[1440 rows x 1 columns]
         frame_145
row_num
0          1.16954
1          1.16959
2          1.16976
3          1.16984
4          1.16979
...            ...
1435       1.16769
1436       1.16767
1437       1.16752
1438       1.16755
1439       1.16760

[1440 rows x 1 columns]
         frame_144
row_num
0          1.16754
1          1.16755
2          1.16750
3          1.16743
4          1.16743
...            ...
1435       1.17230
1436       1.17232
1437       1.17229
1438       1.17222
1439       1.17222

[1440 rows x 1 columns]
         frame_143
row_num
0          1.17246
1          1.17236
2          1.17226
3          1.17226
4          1.17210
...            ...
1435       1.17387
1436       1.17403
1437       1.17420
1438       1.17423
1439       1.17407

[1440 rows x 1 columns]
         frame_142
row_num
0          1.17410
1          1.17405
2          1.17404
3          1.17418
4          1.17406
...            ...
1435       1.17353
1436       1.17361
1437       1.17362
1438       1.17376
1439       1.17388

[1440 rows x 1 columns]
         frame_141
row_num
0          1.17389
1          1.17386
2          1.17373
3          1.17374
4          1.17381
...            ...
1435       1.17714
1436       1.17712
1437       1.17703
1438       1.17724
1439       1.17750

[1440 rows x 1 columns]
         frame_140
row_num
0          1.17735
1          1.17728
2          1.17727
3          1.17730
4          1.17734
...            ...
1435       1.17597
1436       1.17620
1437       1.17640
1438       1.17640
1439       1.17651

[1440 rows x 1 columns]
         frame_139
row_num
0          1.17654
1          1.17658
2          1.17649
3          1.17646
4          1.17650
...            ...
1435       1.17977
1436       1.17971
1437       1.17970
1438       1.17978
1439       1.17977

[1440 rows x 1 columns]
         frame_138
row_num
0          1.17981
1          1.17987
2          1.17992
3          1.17996
4          1.17991
...            ...
1435       1.18397
1436       1.18403
1437       1.18427
1438       1.18400
1439       1.18410

[1440 rows x 1 columns]
         frame_137
row_num
0          1.18397
1          1.18402
2          1.18402
3          1.18416
4          1.18407
...            ...
1435       1.18157
1436       1.18160
1437       1.18163
1438       1.18152
1439       1.18148

[1440 rows x 1 columns]
         frame_136
row_num
0          1.18148
1          1.18139
2          1.18150
3          1.18146
4          1.18141
...            ...
1435       1.18518
1436       1.18518
1437       1.18515
1438       1.18511
1439       1.18504

[1440 rows x 1 columns]
         frame_135
row_num
0          1.18496
1          1.18494
2          1.18475
3          1.18505
4          1.18510
...            ...
1435       1.18751
1436       1.18740
1437       1.18735
1438       1.18735
1439       1.18723

[1440 rows x 1 columns]
         frame_134
row_num
0          1.18715
1          1.18716
2          1.18729
3          1.18728
4          1.18746
...            ...
1435       1.18650
1436       1.18655
1437       1.18655
1438       1.18650
1439       1.18639

[1440 rows x 1 columns]
         frame_133
row_num
0          1.18638
1          1.18624
2          1.18618
3          1.18619
4          1.18603
...            ...
1435       1.18602
1436       1.18594
1437       1.18596
1438       1.18590
1439       1.18597

[1440 rows x 1 columns]
         frame_132
row_num
0          1.18613
1          1.18612
2          1.18620
3          1.18615
4          1.18612
...            ...
1435       1.18208
1436       1.18219
1437       1.18225
1438       1.18224
1439       1.18252

[1440 rows x 1 columns]
         frame_131
row_num
0          1.18245
1          1.18266
2          1.18265
3          1.18255
4          1.18244
...            ...
1435       1.18368
1436       1.18390
1437       1.18399
1438       1.18397
1439       1.18388

[1440 rows x 1 columns]
         frame_130
row_num
0          1.18397
1          1.18381
2          1.18394
3          1.18402
4          1.18375
...            ...
1435       1.18327
1436       1.18328
1437       1.18335
1438       1.18345
1439       1.18354

[1440 rows x 1 columns]
         frame_129
row_num
0          1.18370
1          1.18368
2          1.18368
3          1.18383
4          1.18393
...            ...
1435       1.17778
1436       1.17790
1437       1.17805
1438       1.17813
1439       1.17814

[1440 rows x 1 columns]
         frame_128
row_num
0          1.17801
1          1.17795
2          1.17800
3          1.17793
4          1.17777
...            ...
1435       1.18115
1436       1.18117
1437       1.18126
1438       1.18128
1439       1.18138

[1440 rows x 1 columns]
         frame_127
row_num
0          1.18135
1          1.18135
2          1.18135
3          1.18140
4          1.18145
...            ...
1435       1.18237
1436       1.18261
1437       1.18231
1438       1.18228
1439       1.18227

[1440 rows x 1 columns]
         frame_126
row_num
0          1.18216
1          1.18240
2          1.18262
3          1.18274
4          1.18265
...            ...
1435       1.17663
1436       1.17647
1437       1.17654
1438       1.17645
1439       1.17636

[1440 rows x 1 columns]
         frame_125
row_num
0          1.17632
1          1.17629
2          1.17618
3          1.17599
4          1.17599
...            ...
1435       1.17822
1436       1.17821
1437       1.17829
1438       1.17829
1439       1.17807

[1440 rows x 1 columns]
         frame_124
row_num
0          1.17805
1          1.17793
2          1.17804
3          1.17807
4          1.17813
...            ...
1435       1.17098
1436       1.17117
1437       1.17104
1438       1.17104
1439       1.17118

[1440 rows x 1 columns]
         frame_123
row_num
0          1.17120
1          1.17114
2          1.17122
3          1.17104
4          1.17098
...            ...
1435       1.17377
1436       1.17380
1437       1.17423
1438       1.17417
1439       1.17366

[1440 rows x 1 columns]
         frame_122
row_num
0          1.17266
1          1.17267
2          1.17263
3          1.17282
4          1.17295
...            ...
1435       1.17170
1436       1.17181
1437       1.17167
1438       1.17156
1439       1.17174

[1440 rows x 1 columns]
         frame_121
row_num
0          1.17180
1          1.17168
2          1.17166
3          1.17152
4          1.17172
...            ...
1435       1.17186
1436       1.17188
1437       1.17181
1438       1.17179
1439       1.17188

[1440 rows x 1 columns]

In [841]:
###df80 to df120###
df120 = pd.DataFrame(data=df_close_col.iloc[-172800:-171360])
df120['row_num']=np.arange(len(df120))
df120.set_index('row_num',inplace=True)
df120 = df120.rename(columns={5:'frame_120'})
print(df120)

df119 = pd.DataFrame(data=df_close_col.iloc[-171360:-169920])
df119['row_num']=np.arange(len(df119))
df119.set_index('row_num',inplace=True)
df119 = df119.rename(columns={5:'frame_119'})
print(df119)

df118 = pd.DataFrame(data=df_close_col.iloc[-169920:-168480])
df118['row_num']=np.arange(len(df118))
df118.set_index('row_num',inplace=True)
df118 = df118.rename(columns={5:'frame_118'})
print(df118)

df117 = pd.DataFrame(data=df_close_col.iloc[-168480:-167040])
df117['row_num']=np.arange(len(df117))
df117.set_index('row_num',inplace=True)
df117 = df117.rename(columns={5:'frame_117'})
print(df117)

df116 = pd.DataFrame(data=df_close_col.iloc[-167040:-165600])
df116['row_num']=np.arange(len(df116))
df116.set_index('row_num',inplace=True)
df116 = df116.rename(columns={5:'frame_116'})
print(df116)

df115 = pd.DataFrame(data=df_close_col.iloc[-165600:-164160])
df115['row_num']=np.arange(len(df115))
df115.set_index('row_num',inplace=True)
df115 = df115.rename(columns={5:'frame_115'})
print(df115)

df114 = pd.DataFrame(data=df_close_col.iloc[-164160:-162720])
df114['row_num']=np.arange(len(df114))
df114.set_index('row_num',inplace=True)
df114 = df114.rename(columns={5:'frame_114'})
print(df114)

df113 = pd.DataFrame(data=df_close_col.iloc[-162720:-161280])
df113['row_num']=np.arange(len(df113))
df113.set_index('row_num',inplace=True)
df113 = df113.rename(columns={5:'frame_113'})
print(df113)

df112 = pd.DataFrame(data=df_close_col.iloc[-161280:-159840])
df112['row_num']=np.arange(len(df112))
df112.set_index('row_num',inplace=True)
df112 = df112.rename(columns={5:'frame_112'})
print(df112)

df111 = pd.DataFrame(data=df_close_col.iloc[-159840:-158400])
df111['row_num']=np.arange(len(df111))
df111.set_index('row_num',inplace=True)
df111 = df111.rename(columns={5:'frame_111'})
print(df111)

df110 = pd.DataFrame(data=df_close_col.iloc[-158400:-156960])
df110['row_num']=np.arange(len(df110))
df110.set_index('row_num',inplace=True)
df110 = df110.rename(columns={5:'frame_110'})
print(df110)

df109 = pd.DataFrame(data=df_close_col.iloc[-156960:-155520])
df109['row_num']=np.arange(len(df109))
df109.set_index('row_num',inplace=True)
df109 = df109.rename(columns={5:'frame_109'})
print(df109)

df108 = pd.DataFrame(data=df_close_col.iloc[-155520:-154080])
df108['row_num']=np.arange(len(df108))
df108.set_index('row_num',inplace=True)
df108 = df108.rename(columns={5:'frame_108'})
print(df108)

df107 = pd.DataFrame(data=df_close_col.iloc[-154080:-152640])
df107['row_num']=np.arange(len(df107))
df107.set_index('row_num',inplace=True)
df107 = df107.rename(columns={5:'frame_107'})
print(df107)

df106 = pd.DataFrame(data=df_close_col.iloc[-152640:-151200])
df106['row_num']=np.arange(len(df106))
df106.set_index('row_num',inplace=True)
df106 = df106.rename(columns={5:'frame_106'})
print(df106)

df105 = pd.DataFrame(data=df_close_col.iloc[-151200:-149760])
df105['row_num']=np.arange(len(df105))
df105.set_index('row_num',inplace=True)
df105 = df105.rename(columns={5:'frame_105'})
print(df105)

df104 = pd.DataFrame(data=df_close_col.iloc[-149760:-148320])
df104['row_num']=np.arange(len(df104))
df104.set_index('row_num',inplace=True)
df104 = df104.rename(columns={5:'frame_104'})
print(df104)

df103 = pd.DataFrame(data=df_close_col.iloc[-148320:-146880])
df103['row_num']=np.arange(len(df103))
df103.set_index('row_num',inplace=True)
df103 = df103.rename(columns={5:'frame_103'})
print(df103)

df102 = pd.DataFrame(data=df_close_col.iloc[-146880:-145440])
df102['row_num']=np.arange(len(df102))
df102.set_index('row_num',inplace=True)
df102 = df102.rename(columns={5:'frame_102'})
print(df102)

df101 = pd.DataFrame(data=df_close_col.iloc[-145440:-144000])
df101['row_num']=np.arange(len(df101))
df101.set_index('row_num',inplace=True)
df101 = df101.rename(columns={5:'frame_101'})
print(df101)


df100 = pd.DataFrame(data=df_close_col.iloc[-144000:-142560])
df100['row_num']=np.arange(len(df100))
df100.set_index('row_num',inplace=True)
df100 = df100.rename(columns={5:'frame_100'})
print(df100)

df99 = pd.DataFrame(data=df_close_col.iloc[-142560:-141120])
df99['row_num']=np.arange(len(df99))
df99.set_index('row_num',inplace=True)
df99 = df99.rename(columns={5:'frame_99'})
print(df99)

df98 = pd.DataFrame(data=df_close_col.iloc[-141120:-139680])
df98['row_num']=np.arange(len(df98))
df98.set_index('row_num',inplace=True)
df98 = df98.rename(columns={5:'frame_98'})
print(df98)

df97 = pd.DataFrame(data=df_close_col.iloc[-139680:-138240])
df97['row_num']=np.arange(len(df97))
df97.set_index('row_num',inplace=True)
df97 = df97.rename(columns={5:'frame_97'})
print(df97)

df96 = pd.DataFrame(data=df_close_col.iloc[-138240:-136800])
df96['row_num']=np.arange(len(df96))
df96.set_index('row_num',inplace=True)
df96 = df96.rename(columns={5:'frame_96'})
print(df96)

df95 = pd.DataFrame(data=df_close_col.iloc[-136800:-135360])
df95['row_num']=np.arange(len(df95))
df95.set_index('row_num',inplace=True)
df95 = df95.rename(columns={5:'frame_95'})
print(df95)

df94 = pd.DataFrame(data=df_close_col.iloc[-135360:-133920])
df94['row_num']=np.arange(len(df94))
df94.set_index('row_num',inplace=True)
df94 = df94.rename(columns={5:'frame_94'})
print(df94)

df93 = pd.DataFrame(data=df_close_col.iloc[-133920:-132480])
df93['row_num']=np.arange(len(df93))
df93.set_index('row_num',inplace=True)
df93 = df93.rename(columns={5:'frame_93'})
print(df93)

df92 = pd.DataFrame(data=df_close_col.iloc[-132480:-131040])
df92['row_num']=np.arange(len(df92))
df92.set_index('row_num',inplace=True)
df92 = df92.rename(columns={5:'frame_92'})
print(df92)

df91 = pd.DataFrame(data=df_close_col.iloc[-131040:-129600])
df91['row_num']=np.arange(len(df91))
df91.set_index('row_num',inplace=True)
df91 = df91.rename(columns={5:'frame_91'})
print(df91)

df90 = pd.DataFrame(data=df_close_col.iloc[-129600:-128160])
df90['row_num']=np.arange(len(df90))
df90.set_index('row_num',inplace=True)
df90 = df90.rename(columns={5:'frame_90'})
print(df90)

df89 = pd.DataFrame(data=df_close_col.iloc[-128160:-126720])
df89['row_num']=np.arange(len(df89))
df89.set_index('row_num',inplace=True)
df89 = df89.rename(columns={5:'frame_89'})
print(df89)

df88 = pd.DataFrame(data=df_close_col.iloc[-126720:-125280])
df88['row_num']=np.arange(len(df88))
df88.set_index('row_num',inplace=True)
df88 = df88.rename(columns={5:'frame_88'})
print(df88)

df87 = pd.DataFrame(data=df_close_col.iloc[-125280:-123840])
df87['row_num']=np.arange(len(df87))
df87.set_index('row_num',inplace=True)
df87 = df87.rename(columns={5:'frame_87'})
print(df87)

df86 = pd.DataFrame(data=df_close_col.iloc[-123840:-122400])
df86['row_num']=np.arange(len(df86))
df86.set_index('row_num',inplace=True)
df86 = df86.rename(columns={5:'frame_86'})
print(df86)

df85 = pd.DataFrame(data=df_close_col.iloc[-122400:-120960])
df85['row_num']=np.arange(len(df85))
df85.set_index('row_num',inplace=True)
df85 = df85.rename(columns={5:'frame_85'})
print(df85)

df84 = pd.DataFrame(data=df_close_col.iloc[-120960:-119520])
df84['row_num']=np.arange(len(df84))
df84.set_index('row_num',inplace=True)
df84 = df84.rename(columns={5:'frame_84'})
print(df84)

df83 = pd.DataFrame(data=df_close_col.iloc[-119520:-118080])
df83['row_num']=np.arange(len(df83))
df83.set_index('row_num',inplace=True)
df83 = df83.rename(columns={5:'frame_83'})
print(df83)

df82 = pd.DataFrame(data=df_close_col.iloc[-118080:-116640])
df82['row_num']=np.arange(len(df82))
df82.set_index('row_num',inplace=True)
df82 = df82.rename(columns={5:'frame_82'})
print(df82)

df81 = pd.DataFrame(data=df_close_col.iloc[-116640:-115200])
df81['row_num']=np.arange(len(df81))
df81.set_index('row_num',inplace=True)
df81 = df81.rename(columns={5:'frame_81'})
print(df81)
###df80 to df 120###

         frame_120
row_num
0          1.17171
1          1.17156
2          1.17160
3          1.17156
4          1.17155
...            ...
1435       1.16973
1436       1.16962
1437       1.16954
1438       1.16951
1439       1.16947

[1440 rows x 1 columns]
         frame_119
row_num
0          1.16947
1          1.16943
2          1.16958
3          1.16963
4          1.16975
...            ...
1435       1.16797
1436       1.16795
1437       1.16802
1438       1.16822
1439       1.16826

[1440 rows x 1 columns]
         frame_118
row_num
0          1.16822
1          1.16836
2          1.16838
3          1.16823
4          1.16813
...            ...
1435       1.16569
1436       1.16579
1437       1.16586
1438       1.16555
1439       1.16543

[1440 rows x 1 columns]
         frame_117
row_num
0          1.16529
1          1.16522
2          1.16520
3          1.16530
4          1.16528
...            ...
1435       1.15785
1436       1.15777
1437       1.15795
1438       1.15833
1439       1.15856

[1440 rows x 1 columns]
         frame_116
row_num
0          1.15807
1          1.15841
2          1.15858
3          1.15856
4          1.15837
...            ...
1435       1.16002
1436       1.16003
1437       1.16003
1438       1.16031
1439       1.16054

[1440 rows x 1 columns]
         frame_115
row_num
0          1.16060
1          1.16068
2          1.16049
3          1.16057
4          1.16048
...            ...
1435       1.16363
1436       1.16387
1437       1.16378
1438       1.16368
1439       1.16369

[1440 rows x 1 columns]
         frame_114
row_num
0          1.16368
1          1.16363
2          1.16377
3          1.16363
4          1.16368
...            ...
1435       1.15996
1436       1.15991
1437       1.15991
1438       1.16001
1439       1.16013

[1440 rows x 1 columns]
         frame_113
row_num
0          1.16011
1          1.16027
2          1.16011
3          1.16009
4          1.16017
...            ...
1435       1.15462
1436       1.15468
1437       1.15444
1438       1.15420
1439       1.15417

[1440 rows x 1 columns]
         frame_112
row_num
0          1.15400
1          1.15417
2          1.15443
3          1.15453
4          1.15440
...            ...
1435       1.15540
1436       1.15537
1437       1.15535
1438       1.15546
1439       1.15550

[1440 rows x 1 columns]
         frame_111
row_num
0          1.15522
1          1.15528
2          1.15510
3          1.15531
4          1.15516
...            ...
1435       1.15703
1436       1.15715
1437       1.15759
1438       1.15800
1439       1.15800

[1440 rows x 1 columns]
         frame_110
row_num
0          1.15836
1          1.15810
2          1.15768
3          1.15784
4          1.15763
...            ...
1435       1.15668
1436       1.15652
1437       1.15625
1438       1.15648
1439       1.15644

[1440 rows x 1 columns]
         frame_109
row_num
0          1.15640
1          1.15628
2          1.15632
3          1.15632
4          1.15634
...            ...
1435       1.15338
1436       1.15352
1437       1.15358
1438       1.15352
1439       1.15344

[1440 rows x 1 columns]
         frame_108
row_num
0          1.15340
1          1.15339
2          1.15340
3          1.15347
4          1.15354
...            ...
1435       1.15387
1436       1.15441
1437       1.15438
1438       1.15435
1439       1.15426

[1440 rows x 1 columns]
         frame_107
row_num
0          1.15420
1          1.15436
2          1.15441
3          1.15475
4          1.15450
...            ...
1435       1.16023
1436       1.16002
1437       1.16027
1438       1.16044
1439       1.16047

[1440 rows x 1 columns]
         frame_106
row_num
0          1.16042
1          1.16031
2          1.16057
3          1.16069
4          1.16085
...            ...
1435       1.15985
1436       1.16010
1437       1.16007
1438       1.16033
1439       1.16029

[1440 rows x 1 columns]
         frame_105
row_num
0          1.16012
1          1.16043
2          1.16021
3          1.16010
4          1.15955
...            ...
1435       1.16031
1436       1.16032
1437       1.16030
1438       1.16025
1439       1.16007

[1440 rows x 1 columns]
         frame_104
row_num
0          1.16016
1          1.16016
2          1.16011
3          1.16041
4          1.16030
...            ...
1435       1.16485
1436       1.16483
1437       1.16471
1438       1.16475
1439       1.16490

[1440 rows x 1 columns]
         frame_103
row_num
0          1.16475
1          1.16466
2          1.16467
3          1.16479
4          1.16483
...            ...
1435       1.16408
1436       1.16403
1437       1.16411
1438       1.16416
1439       1.16422

[1440 rows x 1 columns]
         frame_102
row_num
0          1.16421
1          1.16420
2          1.16415
3          1.16386
4          1.16388
...            ...
1435       1.16478
1436       1.16466
1437       1.16454
1438       1.16486
1439       1.16465

[1440 rows x 1 columns]
         frame_101
row_num
0          1.16467
1          1.16451
2          1.16425
3          1.16418
4          1.16427
...            ...
1435       1.16368
1436       1.16366
1437       1.16357
1438       1.16332
1439       1.16355

[1440 rows x 1 columns]
         frame_100
row_num
0          1.16343
1          1.16340
2          1.16362
3          1.16385
4          1.16358
...            ...
1435       1.15937
1436       1.15949
1437       1.15959
1438       1.15954
1439       1.15949

[1440 rows x 1 columns]
         frame_99
row_num
0         1.15954
1         1.15955
2         1.15957
3         1.15978
4         1.15997
...           ...
1435      1.16171
1436      1.16175
1437      1.16172
1438      1.16178
1439      1.16174

[1440 rows x 1 columns]
         frame_98
row_num
0         1.16200
1         1.16206
2         1.16222
3         1.16218
4         1.16204
...           ...
1435      1.16164
1436      1.16181
1437      1.16155
1438      1.16163
1439      1.16164

[1440 rows x 1 columns]
         frame_97
row_num
0         1.16172
1         1.16191
2         1.16194
3         1.16198
4         1.16179
...           ...
1435      1.16300
1436      1.16297
1437      1.16372
1438      1.16314
1439      1.16301

[1440 rows x 1 columns]
         frame_96
row_num
0         1.16269
1         1.16307
2         1.16355
3         1.16326
4         1.16347
...           ...
1435      1.16257
1436      1.16240
1437      1.16240
1438      1.16244
1439      1.16242

[1440 rows x 1 columns]
         frame_95
row_num
0         1.16239
1         1.16242
2         1.16217
3         1.16220
4         1.16237
...           ...
1435      1.15663
1436      1.15665
1437      1.15673
1438      1.15684
1439      1.15678

[1440 rows x 1 columns]
         frame_94
row_num
0         1.15661
1         1.15696
2         1.15700
3         1.15700
4         1.15720
...           ...
1435      1.15918
1436      1.15899
1437      1.15871
1438      1.15854
1439      1.15848

[1440 rows x 1 columns]
         frame_93
row_num
0         1.15840
1         1.15835
2         1.15826
3         1.15848
4         1.15846
...           ...
1435      1.15674
1436      1.15679
1437      1.15675
1438      1.15647
1439      1.15646

[1440 rows x 1 columns]
         frame_92
row_num
0         1.15639
1         1.15648
2         1.15638
3         1.15632
4         1.15632
...           ...
1435      1.15501
1436      1.15480
1437      1.15495
1438      1.15508
1439      1.15499

[1440 rows x 1 columns]
         frame_91
row_num
0         1.15488
1         1.15501
2         1.15501
3         1.15496
4         1.15515
...           ...
1435      1.15221
1436      1.15201
1437      1.15199
1438      1.15211
1439      1.15203

[1440 rows x 1 columns]
         frame_90
row_num
0         1.15188
1         1.15200
2         1.15210
3         1.15194
4         1.15202
...           ...
1435      1.15858
1436      1.15877
1437      1.15838
1438      1.15861
1439      1.15888

[1440 rows x 1 columns]
         frame_89
row_num
0         1.15893
1         1.15894
2         1.15891
3         1.15893
4         1.15893
...           ...
1435      1.15837
1436      1.15830
1437      1.15831
1438      1.15848
1439      1.15835

[1440 rows x 1 columns]
         frame_88
row_num
0         1.15809
1         1.15773
2         1.15818
3         1.15821
4         1.15820
...           ...
1435      1.15457
1436      1.15435
1437      1.15459
1438      1.15469
1439      1.15452

[1440 rows x 1 columns]
         frame_87
row_num
0         1.15431
1         1.15467
2         1.15445
3         1.15422
4         1.15431
...           ...
1435      1.14690
1436      1.14672
1437      1.14654
1438      1.14646
1439      1.14630

[1440 rows x 1 columns]
         frame_86
row_num
0         1.14654
1         1.14666
2         1.14650
3         1.14627
4         1.14629
...           ...
1435      1.14486
1436      1.14541
1437      1.14536
1438      1.14567
1439      1.14538

[1440 rows x 1 columns]
         frame_85
row_num
0         1.14559
1         1.14601
2         1.14564
3         1.14542
4         1.14541
...           ...
1435      1.14353
1436      1.14358
1437      1.14371
1438      1.14367
1439      1.14350

[1440 rows x 1 columns]
         frame_84
row_num
0         1.14320
1         1.14323
2         1.14288
3         1.14284
4         1.14260
...           ...
1435      1.13498
1436      1.13532
1437      1.13528
1438      1.13501
1439      1.13490

[1440 rows x 1 columns]
         frame_83
row_num
0         1.13481
1         1.13470
2         1.13445
3         1.13456
4         1.13481
...           ...
1435      1.13113
1436      1.13117
1437      1.13112
1438      1.13131
1439      1.13120

[1440 rows x 1 columns]
         frame_82
row_num
0         1.13101
1         1.13096
2         1.13086
3         1.13096
4         1.13087
...           ...
1435      1.13572
1436      1.13572
1437      1.13548
1438      1.13561
1439      1.13535

[1440 rows x 1 columns]
         frame_81
row_num
0         1.13532
1         1.13505
2         1.13529
3         1.13536
4         1.13530
...           ...
1435      1.13093
1436      1.13088
1437      1.13072
1438      1.13059
1439      1.13051

[1440 rows x 1 columns]

In [842]:
###df40 to df80###
df80 = pd.DataFrame(data=df_close_col.iloc[-115200:-113760])
df80['row_num']=np.arange(len(df80))
df80.set_index('row_num',inplace=True)
df80 = df80.rename(columns={5:'frame_80'})
print(df80)

df79 = pd.DataFrame(data=df_close_col.iloc[-113760:-112320])
df79['row_num']=np.arange(len(df79))
df79.set_index('row_num',inplace=True)
df79 = df79.rename(columns={5:'frame_79'})
print(df79)

df78 = pd.DataFrame(data=df_close_col.iloc[-112320:-110880])
df78['row_num']=np.arange(len(df78))
df78.set_index('row_num',inplace=True)
df78 = df78.rename(columns={5:'frame_78'})
print(df78)

df77 = pd.DataFrame(data=df_close_col.iloc[-110880:-109440])
df77['row_num']=np.arange(len(df77))
df77.set_index('row_num',inplace=True)
df77 = df77.rename(columns={5:'frame_77'})
print(df77)

df76 = pd.DataFrame(data=df_close_col.iloc[-109440:-108000])
df76['row_num']=np.arange(len(df76))
df76.set_index('row_num',inplace=True)
df76 = df76.rename(columns={5:'frame_76'})
print(df76)

df75 = pd.DataFrame(data=df_close_col.iloc[-108000:-106560])
df75['row_num']=np.arange(len(df75))
df75.set_index('row_num',inplace=True)
df75 = df75.rename(columns={5:'frame_75'})
print(df75)

df74 = pd.DataFrame(data=df_close_col.iloc[-106560:-105120])
df74['row_num']=np.arange(len(df74))
df74.set_index('row_num',inplace=True)
df74 = df74.rename(columns={5:'frame_74'})
print(df74)

df73 = pd.DataFrame(data=df_close_col.iloc[-105120:-103680])
df73['row_num']=np.arange(len(df73))
df73.set_index('row_num',inplace=True)
df73 = df73.rename(columns={5:'frame_73'})
print(df73)

df72 = pd.DataFrame(data=df_close_col.iloc[-103680:-102240])
df72['row_num']=np.arange(len(df72))
df72.set_index('row_num',inplace=True)
df72 = df72.rename(columns={5:'frame_72'})
print(df72)

df71 = pd.DataFrame(data=df_close_col.iloc[-102240:-100800])
df71['row_num']=np.arange(len(df71))
df71.set_index('row_num',inplace=True)
df71 = df71.rename(columns={5:'frame_71'})
print(df71)

df70 = pd.DataFrame(data=df_close_col.iloc[-100800:-99360])
df70['row_num']=np.arange(len(df70))
df70.set_index('row_num',inplace=True)
df70 = df70.rename(columns={5:'frame_70'})
print(df70)

df69 = pd.DataFrame(data=df_close_col.iloc[-99360:-97920])
df69['row_num']=np.arange(len(df69))
df69.set_index('row_num',inplace=True)
df69 = df69.rename(columns={5:'frame_69'})
print(df69)

df68 = pd.DataFrame(data=df_close_col.iloc[-97920:-96480])
df68['row_num']=np.arange(len(df68))
df68.set_index('row_num',inplace=True)
df68 = df68.rename(columns={5:'frame_68'})
print(df68)

df67 = pd.DataFrame(data=df_close_col.iloc[-96480:-95040])
df67['row_num']=np.arange(len(df67))
df67.set_index('row_num',inplace=True)
df67 = df67.rename(columns={5:'frame_67'})
print(df67)

df66 = pd.DataFrame(data=df_close_col.iloc[-95040:-93600])
df66['row_num']=np.arange(len(df66))
df66.set_index('row_num',inplace=True)
df66 = df66.rename(columns={5:'frame_66'})
print(df66)

df65 = pd.DataFrame(data=df_close_col.iloc[-93600:-92160])
df65['row_num']=np.arange(len(df65))
df65.set_index('row_num',inplace=True)
df65 = df65.rename(columns={5:'frame_65'})
print(df65)

df64 = pd.DataFrame(data=df_close_col.iloc[-92160:-90720])
df64['row_num']=np.arange(len(df64))
df64.set_index('row_num',inplace=True)
df64 = df64.rename(columns={5:'frame_64'})
print(df64)

df63 = pd.DataFrame(data=df_close_col.iloc[-90720:-89280])
df63['row_num']=np.arange(len(df63))
df63.set_index('row_num',inplace=True)
df63 = df63.rename(columns={5:'frame_63'})
print(df63)

df62 = pd.DataFrame(data=df_close_col.iloc[-89280:-87840])
df62['row_num']=np.arange(len(df62))
df62.set_index('row_num',inplace=True)
df62 = df62.rename(columns={5:'frame_62'})
print(df62)

df61 = pd.DataFrame(data=df_close_col.iloc[-87840:-86400])
df61['row_num']=np.arange(len(df61))
df61.set_index('row_num',inplace=True)
df61 = df61.rename(columns={5:'frame_61'})
print(df61)


df60 = pd.DataFrame(data=df_close_col.iloc[-86400:-84960])
df60['row_num']=np.arange(len(df60))
df60.set_index('row_num',inplace=True)
df60 = df60.rename(columns={5:'frame_60'})
print(df60)

df59 = pd.DataFrame(data=df_close_col.iloc[-84960:-83520])
df59['row_num']=np.arange(len(df59))
df59.set_index('row_num',inplace=True)
df59 = df59.rename(columns={5:'frame_59'})
print(df59)

df58 = pd.DataFrame(data=df_close_col.iloc[-83520:-82080])
df58['row_num']=np.arange(len(df58))
df58.set_index('row_num',inplace=True)
df58 = df58.rename(columns={5:'frame_58'})
print(df58)

df57 = pd.DataFrame(data=df_close_col.iloc[-82080:-80640])
df57['row_num']=np.arange(len(df57))
df57.set_index('row_num',inplace=True)
df57 = df57.rename(columns={5:'frame_57'})
print(df57)

df56 = pd.DataFrame(data=df_close_col.iloc[-80640:-79200])
df56['row_num']=np.arange(len(df56))
df56.set_index('row_num',inplace=True)
df56 = df56.rename(columns={5:'frame_56'})
print(df56)

df55 = pd.DataFrame(data=df_close_col.iloc[-79200:-77760])
df55['row_num']=np.arange(len(df55))
df55.set_index('row_num',inplace=True)
df55 = df55.rename(columns={5:'frame_55'})
print(df55)

df54 = pd.DataFrame(data=df_close_col.iloc[-77760:-76320])
df54['row_num']=np.arange(len(df54))
df54.set_index('row_num',inplace=True)
df54 = df54.rename(columns={5:'frame_54'})
print(df54)

df53 = pd.DataFrame(data=df_close_col.iloc[-76320:-74880])
df53['row_num']=np.arange(len(df53))
df53.set_index('row_num',inplace=True)
df53 = df53.rename(columns={5:'frame_53'})
print(df53)

df52 = pd.DataFrame(data=df_close_col.iloc[-74880:-73440])
df52['row_num']=np.arange(len(df52))
df52.set_index('row_num',inplace=True)
df52 = df52.rename(columns={5:'frame_52'})
print(df52)

df51 = pd.DataFrame(data=df_close_col.iloc[-73440:-72000])
df51['row_num']=np.arange(len(df51))
df51.set_index('row_num',inplace=True)
df51 = df51.rename(columns={5:'frame_51'})
print(df51)

df50 = pd.DataFrame(data=df_close_col.iloc[-72000:-70560])
df50['row_num']=np.arange(len(df50))
df50.set_index('row_num',inplace=True)
df50 = df50.rename(columns={5:'frame_50'})
print(df50)

df49 = pd.DataFrame(data=df_close_col.iloc[-70560:-69120])
df49['row_num']=np.arange(len(df49))
df49.set_index('row_num',inplace=True)
df49 = df49.rename(columns={5:'frame_49'})
print(df49)

df48 = pd.DataFrame(data=df_close_col.iloc[-69120:-67680])
df48['row_num']=np.arange(len(df48))
df48.set_index('row_num',inplace=True)
df48 = df48.rename(columns={5:'frame_48'})
print(df48)

df47 = pd.DataFrame(data=df_close_col.iloc[-67680:-66240])
df47['row_num']=np.arange(len(df47))
df47.set_index('row_num',inplace=True)
df47 = df47.rename(columns={5:'frame_47'})
print(df47)

df46 = pd.DataFrame(data=df_close_col.iloc[-66240:-64800])
df46['row_num']=np.arange(len(df46))
df46.set_index('row_num',inplace=True)
df46 = df46.rename(columns={5:'frame_46'})
print(df46)

df45 = pd.DataFrame(data=df_close_col.iloc[-64800:-63360])
df45['row_num']=np.arange(len(df45))
df45.set_index('row_num',inplace=True)
df45 = df45.rename(columns={5:'frame_45'})
print(df45)

df44 = pd.DataFrame(data=df_close_col.iloc[-63360:-61920])
df44['row_num']=np.arange(len(df44))
df44.set_index('row_num',inplace=True)
df44 = df44.rename(columns={5:'frame_44'})
print(df44)

df43 = pd.DataFrame(data=df_close_col.iloc[-61920:-60480])
df43['row_num']=np.arange(len(df43))
df43.set_index('row_num',inplace=True)
df43 = df43.rename(columns={5:'frame_43'})
print(df43)

df42 = pd.DataFrame(data=df_close_col.iloc[-60480:-59040])
df42['row_num']=np.arange(len(df42))
df42.set_index('row_num',inplace=True)
df42 = df42.rename(columns={5:'frame_42'})
print(df42)

df41 = pd.DataFrame(data=df_close_col.iloc[-59040:-57600])
df41['row_num']=np.arange(len(df41))
df41.set_index('row_num',inplace=True)
df41 = df41.rename(columns={5:'frame_41'})
print(df41)
###df40 to df80###

         frame_80
row_num
0         1.13051
1         1.13080
2         1.13086
3         1.13107
4         1.13141
...           ...
1435      1.12519
1436      1.12521
1437      1.12507
1438      1.12503
1439      1.12489

[1440 rows x 1 columns]
         frame_79
row_num
0         1.12505
1         1.12476
2         1.12482
3         1.12474
4         1.12449
...           ...
1435      1.12509
1436      1.12515
1437      1.12507
1438      1.12508
1439      1.12493

[1440 rows x 1 columns]
         frame_78
row_num
0         1.12484
1         1.12482
2         1.12493
3         1.12503
4         1.12504
...           ...
1435      1.11976
1436      1.11973
1437      1.11989
1438      1.11966
1439      1.11975

[1440 rows x 1 columns]
         frame_77
row_num
0         1.11973
1         1.11973
2         1.11954
3         1.11957
4         1.11978
...           ...
1435      1.12109
1436      1.12095
1437      1.12093
1438      1.12112
1439      1.12109

[1440 rows x 1 columns]
         frame_76
row_num
0         1.12109
1         1.12133
2         1.12118
3         1.12095
4         1.12098
...           ...
1435      1.13030
1436      1.13029
1437      1.13049
1438      1.13072
1439      1.13090

[1440 rows x 1 columns]
         frame_75
row_num
0         1.13089
1         1.13088
2         1.13085
3         1.13092
4         1.13104
...           ...
1435      1.12651
1436      1.12666
1437      1.12667
1438      1.12671
1439      1.12665

[1440 rows x 1 columns]
         frame_74
row_num
0         1.12666
1         1.12686
2         1.12702
3         1.12692
4         1.12699
...           ...
1435      1.13211
1436      1.13190
1437      1.13143
1438      1.13112
1439      1.13120

[1440 rows x 1 columns]
         frame_73
row_num
0         1.13047
1         1.12915
2         1.12828
3         1.12660
4         1.12882
...           ...
1435      1.13446
1436      1.13431
1437      1.13409
1438      1.13378
1439      1.13377

[1440 rows x 1 columns]
         frame_72
row_num
0         1.13383
1         1.13403
2         1.13443
3         1.13391
4         1.13414
...           ...
1435      1.13244
1436      1.13240
1437      1.13214
1438      1.13221
1439      1.13228

[1440 rows x 1 columns]
         frame_71
row_num
0         1.13187
1         1.13160
2         1.13160
3         1.13154
4         1.13164
...           ...
1435      1.12776
1436      1.12778
1437      1.12724
1438      1.12723
1439      1.12749

[1440 rows x 1 columns]
         frame_70
row_num
0         1.12756
1         1.12772
2         1.12779
3         1.12805
4         1.12791
...           ...
1435      1.12691
1436      1.12678
1437      1.12685
1438      1.12695
1439      1.12727

[1440 rows x 1 columns]
         frame_69
row_num
0         1.12706
1         1.12694
2         1.12724
3         1.12706
4         1.12705
...           ...
1435      1.12475
1436      1.12473
1437      1.12452
1438      1.12411
1439      1.12442

[1440 rows x 1 columns]
         frame_68
row_num
0         1.12457
1         1.12477
2         1.12460
3         1.12473
4         1.12474
...           ...
1435      1.13298
1436      1.13276
1437      1.13333
1438      1.13315
1439      1.13303

[1440 rows x 1 columns]
         frame_67
row_num
0         1.13292
1         1.13324
2         1.13338
3         1.13314
4         1.13321
...           ...
1435      1.12850
1436      1.12849
1437      1.12859
1438      1.12843
1439      1.12834

[1440 rows x 1 columns]
         frame_66
row_num
0         1.12843
1         1.12861
2         1.12868
3         1.12870
4         1.12850
...           ...
1435      1.13011
1436      1.13011
1437      1.13032
1438      1.13044
1439      1.13039

[1440 rows x 1 columns]
         frame_65
row_num
0         1.13016
1         1.13011
2         1.13046
3         1.13036
4         1.13045
...           ...
1435      1.12758
1436      1.12786
1437      1.12782
1438      1.12778
1439      1.12795

[1440 rows x 1 columns]
         frame_64
row_num
0         1.12788
1         1.12789
2         1.12806
3         1.12806
4         1.12834
...           ...
1435      1.12744
1436      1.12750
1437      1.12745
1438      1.12754
1439      1.12753

[1440 rows x 1 columns]
         frame_63
row_num
0         1.12751
1         1.12743
2         1.12751
3         1.12731
4         1.12736
...           ...
1435      1.12561
1436      1.12578
1437      1.12568
1438      1.12580
1439      1.12595

[1440 rows x 1 columns]
         frame_62
row_num
0         1.12587
1         1.12600
2         1.12602
3         1.12610
4         1.12619
...           ...
1435      1.13039
1436      1.13040
1437      1.13018
1438      1.13040
1439      1.13068

[1440 rows x 1 columns]
         frame_61
row_num
0         1.13075
1         1.13081
2         1.13091
3         1.13097
4         1.13099
...           ...
1435      1.12744
1436      1.12730
1437      1.12717
1438      1.12741
1439      1.12729

[1440 rows x 1 columns]
         frame_60
row_num
0         1.12721
1         1.12728
2         1.12706
3         1.12675
4         1.12713
...           ...
1435      1.12953
1436      1.12948
1437      1.12968
1438      1.12964
1439      1.12960

[1440 rows x 1 columns]
         frame_59
row_num
0         1.12955
1         1.13000
2         1.12989
3         1.13000
4         1.12985
...           ...
1435      1.12685
1436      1.12683
1437      1.12679
1438      1.12681
1439      1.12711

[1440 rows x 1 columns]
         frame_58
row_num
0         1.12727
1         1.12723
2         1.12719
3         1.12724
4         1.12706
...           ...
1435      1.13367
1436      1.13360
1437      1.13342
1438      1.13371
1439      1.13378

[1440 rows x 1 columns]
         frame_57
row_num
0         1.13384
1         1.13353
2         1.13385
3         1.13377
4         1.13366
...           ...
1435      1.13166
1436      1.13150
1437      1.13161
1438      1.13179
1439      1.13175

[1440 rows x 1 columns]
         frame_56
row_num
0         1.13165
1         1.13171
2         1.13173
3         1.13167
4         1.13148
...           ...
1435      1.13083
1436      1.13085
1437      1.13089
1438      1.13090
1439      1.13092

[1440 rows x 1 columns]
         frame_55
row_num
0         1.13086
1         1.13082
2         1.13082
3         1.13082
4         1.13081
...           ...
1435      1.13239
1436      1.13232
1437      1.13219
1438      1.13218
1439      1.13227

[1440 rows x 1 columns]
         frame_54
row_num
0         1.13227
1         1.13230
2         1.13238
3         1.13240
4         1.13241
...           ...
1435      1.12999
1436      1.13018
1437      1.13011
1438      1.13018
1439      1.13011

[1440 rows x 1 columns]
         frame_53
row_num
0         1.13006
1         1.13004
2         1.13008
3         1.13002
4         1.13004
...           ...
1435      1.13420
1436      1.13420
1437      1.13421
1438      1.13417
1439      1.13412

[1440 rows x 1 columns]
         frame_52
row_num
0         1.13408
1         1.13411
2         1.13411
3         1.13407
4         1.13406
...           ...
1435      1.13106
1436      1.13106
1437      1.13118
1438      1.13110
1439      1.13106

[1440 rows x 1 columns]
         frame_51
row_num
0         1.13106
1         1.13116
2         1.13128
3         1.13136
4         1.13131
...           ...
1435      1.13846
1436      1.13845
1437      1.13839
1438      1.13837
1439      1.13837

[1440 rows x 1 columns]
         frame_50
row_num
0         1.13828
1         1.13826
2         1.13825
3         1.13822
4         1.13821
...           ...
1435      1.12961
1436      1.12965
1437      1.12960
1438      1.12971
1439      1.12978

[1440 rows x 1 columns]
         frame_49
row_num
0         1.12966
1         1.12978
2         1.12983
3         1.12992
4         1.12991
...           ...
1435      1.12843
1436      1.12836
1437      1.12829
1438      1.12829
1439      1.12828

[1440 rows x 1 columns]
         frame_48
row_num
0         1.12821
1         1.12821
2         1.12822
3         1.12826
4         1.12835
...           ...
1435      1.13093
1436      1.13086
1437      1.13106
1438      1.13099
1439      1.13111

[1440 rows x 1 columns]
         frame_47
row_num
0         1.13110
1         1.13099
2         1.13087
3         1.13080
4         1.13086
...           ...
1435      1.12901
1436      1.12890
1437      1.12891
1438      1.12911
1439      1.12900

[1440 rows x 1 columns]
         frame_46
row_num
0         1.12905
1         1.12906
2         1.12901
3         1.12905
4         1.12908
...           ...
1435      1.13618
1436      1.13619
1437      1.13619
1438      1.13613
1439      1.13614

[1440 rows x 1 columns]
         frame_45
row_num
0         1.13617
1         1.13605
2         1.13598
3         1.13591
4         1.13593
...           ...
1435      1.13285
1436      1.13274
1437      1.13271
1438      1.13278
1439      1.13283

[1440 rows x 1 columns]
         frame_44
row_num
0         1.13288
1         1.13292
2         1.13291
3         1.13294
4         1.13294
...           ...
1435      1.13691
1436      1.13681
1437      1.13678
1438      1.13683
1439      1.13674

[1440 rows x 1 columns]
         frame_43
row_num
0         1.13673
1         1.13677
2         1.13676
3         1.13668
4         1.13677
...           ...
1435      1.14444
1436      1.14452
1437      1.14458
1438      1.14460
1439      1.14464

[1440 rows x 1 columns]
         frame_42
row_num
0         1.14456
1         1.14454
2         1.14459
3         1.14461
4         1.14457
...           ...
1435      1.14579
1436      1.14579
1437      1.14578
1438      1.14586
1439      1.14573

[1440 rows x 1 columns]
         frame_41
row_num
0         1.14562
1         1.14568
2         1.14573
3         1.14559
4         1.14562
...           ...
1435      1.14153
1436      1.14156
1437      1.14153
1438      1.14162
1439      1.14162

[1440 rows x 1 columns]

In [ ]:
###df1 to df40###
df40 = pd.DataFrame(data=df_close_col.iloc[-57600:-56160])
df40['row_num']=np.arange(len(df40))
df40.set_index('row_num',inplace=True)
df40 = df40.rename(columns={5:'frame_40'})
print(df40)

df39 = pd.DataFrame(data=df_close_col.iloc[-56160:-54720])
df39['row_num']=np.arange(len(df39))
df39.set_index('row_num',inplace=True)
df39 = df39.rename(columns={5:'frame_39'})
print(df39)

df38 = pd.DataFrame(data=df_close_col.iloc[-54720:-53280])
df38['row_num']=np.arange(len(df38))
df38.set_index('row_num',inplace=True)
df38 = df38.rename(columns={5:'frame_38'})
print(df38)

df37 = pd.DataFrame(data=df_close_col.iloc[-53280:-51840])
df37['row_num']=np.arange(len(df37))
df37.set_index('row_num',inplace=True)
df37 = df37.rename(columns={5:'frame_37'})
print(df37)

df36 = pd.DataFrame(data=df_close_col.iloc[-51840:-50400])
df36['row_num']=np.arange(len(df36))
df36.set_index('row_num',inplace=True)
df36 = df36.rename(columns={5:'frame_36'})
print(df36)

df35 = pd.DataFrame(data=df_close_col.iloc[-50400:-48960])
df35['row_num']=np.arange(len(df35))
df35.set_index('row_num',inplace=True)
df35 = df35.rename(columns={5:'frame_35'})
print(df35)

df34 = pd.DataFrame(data=df_close_col.iloc[-48960:-47520])
df34['row_num']=np.arange(len(df34))
df34.set_index('row_num',inplace=True)
df34 = df34.rename(columns={5:'frame_34'})
print(df34)

df33 = pd.DataFrame(data=df_close_col.iloc[-47520:-46080])
df33['row_num']=np.arange(len(df33))
df33.set_index('row_num',inplace=True)
df33 = df33.rename(columns={5:'frame_33'})
print(df33)

df32 = pd.DataFrame(data=df_close_col.iloc[-46080:-44640])
df32['row_num']=np.arange(len(df32))
df32.set_index('row_num',inplace=True)
df32 = df32.rename(columns={5:'frame_32'})
print(df32)

df31 = pd.DataFrame(data=df_close_col.iloc[-44640:-43200])
df31['row_num']=np.arange(len(df31))
df31.set_index('row_num',inplace=True)
df31 = df31.rename(columns={5:'frame_31'})
print(df31)

df30 = pd.DataFrame(data=df_close_col.iloc[-43200:-41760])
df30['row_num']=np.arange(len(df30))
df30.set_index('row_num',inplace=True)
df30 = df30.rename(columns={5:'frame_30'})
print(df30)

df29 = pd.DataFrame(data=df_close_col.iloc[-41760:-40320])
df29['row_num']=np.arange(len(df29))
df29.set_index('row_num',inplace=True)
df29 = df29.rename(columns={5:'frame_29'})
print(df29)

df28 = pd.DataFrame(data=df_close_col.iloc[-40320:-38880])
df28['row_num']=np.arange(len(df28))
df28.set_index('row_num',inplace=True)
df28 = df28.rename(columns={5:'frame_28'})
print(df28)

df27 = pd.DataFrame(data=df_close_col.iloc[-38880:-37440])
df27['row_num']=np.arange(len(df27))
df27.set_index('row_num',inplace=True)
df27 = df27.rename(columns={5:'frame_27'})
print(df27)

df26 = pd.DataFrame(data=df_close_col.iloc[-37440:-36000])
df26['row_num']=np.arange(len(df26))
df26.set_index('row_num',inplace=True)
df26 = df26.rename(columns={5:'frame_26'})
print(df26)

df25 = pd.DataFrame(data=df_close_col.iloc[-36000:-34560])
df25['row_num']=np.arange(len(df25))
df25.set_index('row_num',inplace=True)
df25 = df25.rename(columns={5:'frame_25'})
print(df25)

df24 = pd.DataFrame(data=df_close_col.iloc[-34560:-33120])
df24['row_num']=np.arange(len(df24))
df24.set_index('row_num',inplace=True)
df24 = df24.rename(columns={5:'frame_24'})
print(df24)

df23 = pd.DataFrame(data=df_close_col.iloc[-33120:-31680])
df23['row_num']=np.arange(len(df23))
df23.set_index('row_num',inplace=True)
df23 = df23.rename(columns={5:'frame_23'})
print(df23)

df22 = pd.DataFrame(data=df_close_col.iloc[-31680:-30240])
df22['row_num']=np.arange(len(df22))
df22.set_index('row_num',inplace=True)
df22 = df22.rename(columns={5:'frame_22'})
print(df22)

df21 = pd.DataFrame(data=df_close_col.iloc[-30240:-28800])
df21['row_num']=np.arange(len(df21))
df21.set_index('row_num',inplace=True)
df21 = df21.rename(columns={5:'frame_21'})
print(df21)


df20 = pd.DataFrame(data=df_close_col.iloc[-28800:-27360])
df20['row_num']=np.arange(len(df20))
df20.set_index('row_num',inplace=True)
df20 = df20.rename(columns={5:'frame_20'})
print(df20)

df19 = pd.DataFrame(data=df_close_col.iloc[-27360:-25920])
df19['row_num']=np.arange(len(df19))
df19.set_index('row_num',inplace=True)
df19 = df19.rename(columns={5:'frame_19'})
print(df19)

df18 = pd.DataFrame(data=df_close_col.iloc[-25920:-24480])
df18['row_num']=np.arange(len(df18))
df18.set_index('row_num',inplace=True)
df18 = df18.rename(columns={5:'frame_18'})
print(df18)

df17 = pd.DataFrame(data=df_close_col.iloc[-24480:-23040])
df17['row_num']=np.arange(len(df17))
df17.set_index('row_num',inplace=True)
df17 = df17.rename(columns={5:'frame_17'})
print(df17)

df16 = pd.DataFrame(data=df_close_col.iloc[-23040:-21600])
df16['row_num']=np.arange(len(df16))
df16.set_index('row_num',inplace=True)
df16 = df16.rename(columns={5:'frame_16'})
print(df16)

df15 = pd.DataFrame(data=df_close_col.iloc[-21600:-20160])
df15['row_num']=np.arange(len(df15))
df15.set_index('row_num',inplace=True)
df15 = df15.rename(columns={5:'frame_15'})
print(df15)

df14 = pd.DataFrame(data=df_close_col.iloc[-20160:-18720])
df14['row_num']=np.arange(len(df14))
df14.set_index('row_num',inplace=True)
df14 = df14.rename(columns={5:'frame_14'})
print(df14)

df13 = pd.DataFrame(data=df_close_col.iloc[-18720:-17280])
df13['row_num']=np.arange(len(df13))
df13.set_index('row_num',inplace=True)
df13 = df13.rename(columns={5:'frame_13'})
print(df13)

df12 = pd.DataFrame(data=df_close_col.iloc[-17280:-15840])
df12['row_num']=np.arange(len(df12))
df12.set_index('row_num',inplace=True)
df12 = df12.rename(columns={5:'frame_12'})
print(df12)

df11 = pd.DataFrame(data=df_close_col.iloc[-15840:-14400])
df11['row_num']=np.arange(len(df11))
df11.set_index('row_num',inplace=True)
df11 = df11.rename(columns={5:'frame_11'})
print(df11)

df10 = pd.DataFrame(data=df_close_col.iloc[-14400:-12960])
df10['row_num']=np.arange(len(df10))
df10.set_index('row_num',inplace=True)
df10 = df10.rename(columns={5:'frame_10'})
print(df10)

df9 = pd.DataFrame(data=df_close_col.iloc[-12960:-11520])
df9['row_num']=np.arange(len(df9))
df9.set_index('row_num',inplace=True)
df9 = df9.rename(columns={5:'frame_9'})
print(df9)

df8 = pd.DataFrame(data=df_close_col.iloc[-11520:-10080])
df8['row_num']=np.arange(len(df8))
df8.set_index('row_num',inplace=True)
df8 = df8.rename(columns={5:'frame_8'})
print(df8)

df7 = pd.DataFrame(data=df_close_col.iloc[-10080:-8640])
df7['row_num']=np.arange(len(df7))
df7.set_index('row_num',inplace=True)
df7 = df7.rename(columns={5:'frame_7'})
print(df7)

df6 = pd.DataFrame(data=df_close_col.iloc[-8640:-7200])
df6['row_num']=np.arange(len(df6))
df6.set_index('row_num',inplace=True)
df6 = df6.rename(columns={5:'frame_6'})
print(df6)

df5 = pd.DataFrame(data=df_close_col.iloc[-7200:-5760])
df5['row_num']=np.arange(len(df5))
df5.set_index('row_num',inplace=True)
df5 = df5.rename(columns={5:'frame_5'})
print(df5)

df4 = pd.DataFrame(data=df_close_col.iloc[-5760:-4320])
df4['row_num']=np.arange(len(df4))
df4.set_index('row_num',inplace=True)
df4 = df4.rename(columns={5:'frame_4'})
print(df4)

df3 = pd.DataFrame(data=df_close_col.iloc[-4320:-2880])
df3['row_num']=np.arange(len(df3))
df3.set_index('row_num',inplace=True)
df3 = df3.rename(columns={5:'frame_3'})
print(df3)

df2 = pd.DataFrame(data=df_close_col.iloc[-2880:-1440])
df2['row_num']=np.arange(len(df2))
df2.set_index('row_num',inplace=True)
df2 = df2.rename(columns={5:'frame_2'})
print(df2)

df1 = pd.DataFrame(data=df_close_col.iloc[-1440:])
df1['row_num']=np.arange(len(df1))
df1.set_index('row_num',inplace=True)
df1 = df1.rename(columns={5:'frame_1'})
print(df1)
###df1 to df40###

In [ ]:
#return index to int
df_backtest_idx.reset_index(inplace=True)

In [ ]:
df_backtest_idx

In [ ]:
date_time = pd.DataFrame(data=df_backtest_idx.date_time)

In [ ]:
date_time = pd.to_datetime(date_time.date_time)

In [ ]:
date_time

In [ ]:
idx_dt_as_feature = pd.DataFrame(data=date_time)

In [ ]:
df_train = pd.concat([date_time,df240,df239,df238,df237,df236,df235,df234,df233,df232,df231,df230,df229,df228,df227,df226,df225,df224,df223,df222,df221,df220,df219,df218,df217,df216,df215,df214,df213,df212,df211,df210,df209,df208,df207,df206,df205,df204,df203,df202,df201,df200,df199,df198,df197,df196,df195,df194,df193,df192,df191,df190,df189,df188,df187,df186,df185,df184,df183,df182,df181,df180,df179,df178,df177,df176,df175,df174,df173,df172,df171,df170,df169,df168,df167,df166,df165,df164,df163,df162,df161,df160,df159,df158,df157,df156,df155,df154,df153,df152,df151,df150,df149,df148,df147,df146,df145,df144,df143,df142,df141,df140,df139,df138,df137,df136,df135,df134,df133,df132,df131,df130,df129,df128,df127,df126,df125,df124,df123,df122,df121,df120,df119,df118,df117,df116,df115,df114,df113,df112,df111,df110,df109,df108,df107,df106,df105,df104,df103,df102,df101,df100,df99,df98,df97,df96,df95,df94,df93,df92,df91,df90,df89,df88,df87,df86,df85,df84,df83,df82,df81,df80,df79,df78,df77,df76,df75,df74,df73,df72,df71,df70,df69,df68,df67,df66,df65,df64,df63,df62,df61,df60,df59,df58,df57,df56,df55,df54,df53,df52,df51,df50,df49,df48,df47,df46,df45,df44,df43,df42,df41,df40,df39,df38,df37,df36,df35,df34,df33,df32,df31,df30,df29,df28,df27,df26,df25,df24,df23,df22,df21,df20,df19,df18,df17,df16,df15,df14,df13,df12,df11,df10,df9,df8,df7,df6,df5,df4,df3,df2,df1], axis=1)
df_train = pd.DataFrame(data=df_train)
df_train.set_index('date_time',inplace=True)
df_train['idx_dt_as_feature'] = df_train.index
df_train

In [ ]:
df_train.info()

In [ ]:
df_train.isnull().sum()

In [ ]:
df_test = pd.concat([
                     date_time,df239,df238,df237,df236,df235,df234,df233,df232,df231,df230,df229,df228,df227,df226,df225,df224,df223,df222,df221,df220,df219,df218,df217,df216,df215,df214,df213,df212,df211,df210,df209,df208,df207,df206,df205,df204,df203,df202,df201,
                     df200,df199,df198,df197,df196,df195,df194,df193,df192,df191,df190,df189,df188,df187,df186,df185,df184,df183,df182,df181,df180,df179,df178,df177,df176,df175,df174,df173,df172,df171,df170,df169,df168,df167,df166,df165,df164,df163,df162,df161,
                     df160,df159,df158,df157,df156,df155,df154,df153,df152,df151,df150,df149,df148,df147,df146,df145,df144,df143,df142,df141,df140,df139,df138,df137,df136,df135,df134,df133,df132,df131,df130,df129,df128,df127,df126,df125,df124,df123,df122,df121,
                     df120,df119,df118,df117,df116,df115,df114,df113,df112,df111,df110,df109,df108,df107,df106,df105,df104,df103,df102,df101,df100,df99,df98,df97,df96,df95,df94,df93,df92,df91,df90,df89,df88,df87,df86,df85,df84,df83,df82,df81,
                     df80,df79,df78,df77,df76,df75,df74,df73,df72,df71,df70,df69,df68,df67,df66,df65,df64,df63,df62,df61,df60,df59,df58,df57,df56,df55,df54,df53,df52,df51,df50,df49,df48,df47,df46,df45,df44,df43,df42,df41,
                     df40,df39,df38,df37,df36,df35,df34,df33,df32,df31,df30,df29,df28,df27,df26,df25,df24,df23,df22,df21,df20,df19,df18,df17,df16,df15,df14,df13,df12,df11,df10,df9,df8,df7,df6,df5,df4,df3,df2,df1], axis=1)
df_test['pred_col'] =0
df_test.rename(columns={
                        'frame_239':'frame_240','frame_238':'frame_239','frame_237':'frame_238','frame_236':'frame_237','frame_235':'frame_236','frame_234':'frame_235','frame_233':'frame_234','frame_232':'frame_233','frame_231':'frame_232','frame_230':'frame_231','frame_229':'frame_230','frame_228':'frame_229','frame_227':'frame_228','frame_226':'frame_227','frame_225':'frame_226','frame_224':'frame_225','frame_223':'frame_224','frame_222':'frame_223','frame_221':'frame_222','frame_220':'frame_221','frame_219':'frame_220','frame_218':'frame_219','frame_217':'frame_218','frame_216':'frame_217','frame_215':'frame_216','frame_214':'frame_215','frame_213':'frame_214','frame_212':'frame_213','frame_211':'frame_212','frame_210':'frame_211','frame_209':'frame_210','frame_208':'frame_209','frame_207':'frame_208','frame_206':'frame_207','frame_205':'frame_206','frame_204':'frame_205','frame_203': 'frame_204','frame_202':'frame_203','frame_201':'frame_202','frame_200':'frame_201',
                        'frame_199':'frame_200','frame_198':'frame_199','frame_197':'frame_198','frame_196':'frame_197','frame_195':'frame_196','frame_194':'frame_195','frame_193':'frame_194','frame_192':'frame_193','frame_191':'frame_192','frame_190':'frame_191','frame_189':'frame_190','frame_188':'frame_189','frame_187':'frame_188','frame_186':'frame_187','frame_185':'frame_186','frame_184':'frame_185','frame_183':'frame_184','frame_182':'frame_183','frame_181':'frame_182','frame_180':'frame_181','frame_179':'frame_180','frame_178':'frame_179','frame_177':'frame_178','frame_176':'frame_177','frame_175':'frame_176','frame_174':'frame_175','frame_173':'frame_174','frame_172':'frame_173','frame_171':'frame_172','frame_170':'frame_171','frame_169':'frame_170','frame_168':'frame_169','frame_167':'frame_168','frame_166':'frame_167','frame_165':'frame_166','frame_164':'frame_165','frame_163': 'frame_164', 'frame_162': 'frame_163','frame_161':'frame_162','frame_160':'frame_161',
                        'frame_159':'frame_160','frame_158':'frame_159','frame_157':'frame_158','frame_156':'frame_157','frame_155':'frame_156','frame_154':'frame_155','frame_153':'frame_154','frame_152':'frame_153','frame_151':'frame_152','frame_150':'frame_151','frame_149':'frame_150','frame_148':'frame_149','frame_147':'frame_148','frame_146':'frame_147','frame_145':'frame_146','frame_144':'frame_145','frame_143':'frame_144','frame_142':'frame_143','frame_141':'frame_142','frame_140':'frame_141','frame_139':'frame_140','frame_138':'frame_139','frame_137':'frame_138','frame_136':'frame_137','frame_135':'frame_136','frame_134':'frame_135','frame_133':'frame_134','frame_132':'frame_133','frame_131':'frame_132','frame_130':'frame_131','frame_129':'frame_130','frame_128':'frame_129','frame_127':'frame_128','frame_126':'frame_127','frame_125':'frame_126','frame_124':'frame_125','frame_123': 'frame_124', 'frame_122': 'frame_123','frame_121':'frame_122','frame_120':'frame_121',
                        'frame_119':'frame_120','frame_118':'frame_119','frame_117':'frame_118','frame_116':'frame_117','frame_115':'frame_116','frame_114':'frame_115','frame_113':'frame_114','frame_112':'frame_113','frame_111':'frame_112','frame_110':'frame_111','frame_109':'frame_110','frame_108':'frame_109','frame_107':'frame_108','frame_106':'frame_107','frame_105':'frame_106','frame_104':'frame_105','frame_103':'frame_104','frame_102':'frame_103','frame_101':'frame_102','frame_100':'frame_101','frame_99':'frame_100','frame_98':'frame_99','frame_97':'frame_98','frame_96':'frame_97','frame_95':'frame_96','frame_94':'frame_95','frame_93':'frame_94','frame_92':'frame_93','frame_91':'frame_92','frame_90':'frame_91','frame_89':'frame_90','frame_88':'frame_89','frame_87':'frame_88','frame_86':'frame_87','frame_85':'frame_86','frame_84':'frame_85','frame_83': 'frame_84','frame_82':'frame_83','frame_81':'frame_82','frame_80':'frame_81',
                        'frame_79':'frame_80','frame_78':'frame_79','frame_77':'frame_78','frame_76':'frame_77','frame_75':'frame_76','frame_74':'frame_75','frame_73':'frame_74','frame_72':'frame_73','frame_71':'frame_72','frame_70':'frame_71','frame_69':'frame_70','frame_68':'frame_69','frame_67':'frame_68','frame_66':'frame_67','frame_65':'frame_66','frame_64':'frame_65','frame_63':'frame_64','frame_62':'frame_63','frame_61':'frame_62','frame_60':'frame_61','frame_59':'frame_60','frame_58':'frame_59','frame_57':'frame_58','frame_56':'frame_57','frame_55':'frame_56','frame_54':'frame_55','frame_53':'frame_54','frame_52':'frame_53','frame_51':'frame_52','frame_50':'frame_51','frame_49':'frame_50','frame_48':'frame_49','frame_47':'frame_48','frame_46':'frame_47','frame_45':'frame_46','frame_44':'frame_45','frame_43': 'frame_44', 'frame_42': 'frame_43','frame_41':'frame_42','frame_40':'frame_41',
                        'frame_39':'frame_40','frame_38':'frame_39','frame_37':'frame_38','frame_36':'frame_37','frame_35':'frame_36','frame_34':'frame_35','frame_33':'frame_34','frame_32':'frame_33','frame_31':'frame_32','frame_30':'frame_31','frame_29':'frame_30','frame_28':'frame_29','frame_27':'frame_28','frame_26':'frame_27','frame_25':'frame_26','frame_24':'frame_25','frame_23':'frame_24','frame_22':'frame_23','frame_21':'frame_22','frame_20':'frame_21','frame_19':'frame_20','frame_18':'frame_19','frame_17':'frame_18','frame_16':'frame_17','frame_15':'frame_16','frame_14':'frame_15','frame_13':'frame_14','frame_12':'frame_13','frame_11':'frame_12','frame_10':'frame_11','frame_9':'frame_10','frame_8':'frame_9','frame_7':'frame_8','frame_6':'frame_7','frame_5':'frame_6','frame_4':'frame_5','frame_3': 'frame_4', 'frame_2': 'frame_3','frame_1':'frame_2','pred_col':'frame_1'}, inplace=True)
df_test = pd.DataFrame(data=df_test)
df_test.set_index('date_time',inplace=True)
df_test['idx_dt_as_feature'] = df_test.index
df_test

In [ ]:
df_test.info()

In [ ]:
df_test.isnull().sum()

In [ ]:
for col in df_test.columns:
    print(col)

In [ ]:
#predict new interval
label_new_interval = 'frame_1' #this is any interval you wish to predict.
print("Summary of class variable: \n", df_train[label_new_interval].describe())

In [ ]:
#from autogluon.core.searcher import RLSearcher 
#from autogluon.core.scheduler import RLScheduler

In [ ]:
#HPO
import autogluon.core as ag

nn_options = {  # specifies non-default hyperparameter values for neural network models
     'num_epochs': 10,  # number of training epochs (controls training time of NN models)
    'learning_rate': ag.space.Real(1e-4, 1e-2, default=5e-4, log=True),  # learning rate used in training (real-valued hyperparameter searched on log-scale)
     'activation': ag.space.Categorical('relu', 'softrelu', 'tanh'),  # activation function used in NN (categorical hyperparameter, default = first entry)
     'dropout_prob': ag.space.Real(0.0, 0.5, default=0.1),  # dropout probability (real-valued hyperparameter)
# }
# # gbm_options = {  # specifies non-default hyperparameter values for lightGBM gradient boosted trees
# #     'num_boost_round': 1000,  # number of boosting rounds (controls training time of GBM models)
# #     'num_leaves': ag.space.Int(lower=26, upper=66, default=36),  # number of leaves in trees (integer hyperparameter)
}

hyperparameters = {  # hyperparameters of each model type
                    
                    'NN': nn_options,  # NOTE: comment this line out if you get errors on Mac OSX
                   } 
# time_limit = 2*60  # train various models for ~2 min
# num_trials = 10  # try at most 5 different hyperparameter configurations for each type of model
# search_strategy = 'bayesopt'  # to tune hyperparameters using bayesian optimisation search routine with a local scheduler

hyperparameter_tune_kwargs = {  # HPO is not performed unless hyperparameter_tune_kwargs is specified
 #    'num_trials': num_trials,
     'scheduler' : 'RLScheduler',
     'searcher': 'RLSearcher',
}

#choose models, and predict next interval
save_path='ag_predict_interval'

predictor = TabularPredictor(label=label_new_interval, path=save_path)

#predictor.fit(df_train, hyperparameters=hyperparameters, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs)

predictor.fit(df_train, hyperparameters={'LR':{}}, presets='best_quality')

#predictor.fit(df_train, presets='optimize_for_deployment')

In [ ]:
#predictor.feature_importance(data=df_train)

In [ ]:
#predict close
test_data = TabularDataset(df_test)
y_test = df_test[label_new_interval]
test_data_nolab = df_test.drop(columns=[label_new_interval])
test_data_nolab

In [ ]:
#predict new interval
predictor = TabularPredictor.load(save_path)
y_pred = predictor.predict(test_data_nolab)
print("Predictions: \n", y_pred)
perf = predictor.evaluate_predictions(y_true = y_test, y_pred = y_pred, auxiliary_metrics=True)

In [ ]:
#make sure to run train several times to get consensus result
#never mind the y,x axis scaling. I need to fix it. I'm looking at the shape of the forecast.
import matplotlib as mpl
mpl.rcParams['savefig.dpi'] = 100

ax = y_pred.plot(figsize = (10, 10))

In [ ]:
#contrast leaderboard result of train and test data
predictor.leaderboard(df_train, silent=True)

In [ ]:
# clears the model after a run so you can contrast new runs.
# predictor.unpersist_models('ag_predict_interval')
# predictor.save_space()
# predictor.delete_models(models_to_keep='best', dry_run=False)
%rm -rf AutogluonModels, ag_predict_interval
!ls